/**
 * Thematic mini-packs — opt-in extras, not part of the frequency starter.
 * Enable from Library → Themes. Cards merge by unique foreign form.
 * Ranks start at 1001 so day-one hook mix stays on the core deck;
 * enabled packs get a small daily intro bias after the early phase.
 */
(function (root) {
  const packs = {
    airport: {
      id: "airport",
      title: "Airport & travel",
      blurb: "Gates, bags, delays, and asking for help.",
      // categoryId → entries (foreign, native, category, band)
      byCategory: {},
    },
  };

  const AIRPORT_EN = [
    'airport',
    'flight',
    'boarding pass',
    'passport',
    'suitcase',
    'luggage',
    'gate',
    'departure',
    'arrival',
    'check-in',
    'security',
    'customs',
    'baggage claim',
    'delayed',
    'cancelled',
    'on time',
    'ticket',
    'seat',
    'window seat',
    'aisle seat',
    'boarding',
    'to take off',
    'to land',
    'Where is the gate?',
    'I have a reservation',
    'one-way ticket',
    'return ticket',
    'My suitcase is missing',
    'How much does it cost?',
    'terminal',
    'flight attendant',
    'overhead bin',
    'hand luggage',
    'taxi',
    'bus',
    'train',
    'hotel',
    'I need help',
    'Is there Wi‑Fi?',
    'exit',
    'entrance',
    'Do you speak English?',
    'I don\'t understand',
    'Please speak more slowly',
    'Where is the bathroom?',
    'lost and found',
    'transfer',
    'connection',
    'boarding time',
    'passport control',
  ];

  function buildEntries(forms) {
    return forms.map(([foreign, native]) => {
      const f = String(foreign || "").trim();
      const isPhrase = /\s|[?!]/.test(f);
      return {
        foreign: f,
        native: String(native || "").trim(),
        category: isPhrase ? "phrase" : (String(native).startsWith("to ") ? "verb" : "noun"),
        band: isPhrase ? "phrase" : "C",
      };
    });
  }

  packs.airport.byCategory["nb-bokmal"] = buildEntries([
    ['flyplass', 'airport'],
    ['fly', 'flight'],
    ['boardingkort', 'boarding pass'],
    ['pass', 'passport'],
    ['koffert', 'suitcase'],
    ['bagasje', 'luggage'],
    ['gate', 'gate'],
    ['avgang', 'departure'],
    ['ankomst', 'arrival'],
    ['innsjekking', 'check-in'],
    ['sikkerhetskontroll', 'security'],
    ['toll', 'customs'],
    ['bagasjebånd', 'baggage claim'],
    ['forsinket', 'delayed'],
    ['kansellert', 'cancelled'],
    ['i rute', 'on time'],
    ['billett', 'ticket'],
    ['sete', 'seat'],
    ['vindusplass', 'window seat'],
    ['midtgangsplass', 'aisle seat'],
    ['ombordstigning', 'boarding'],
    ['å ta av', 'to take off'],
    ['å lande', 'to land'],
    ['Hvor er gaten?', 'Where is the gate?'],
    ['Jeg har en reservasjon', 'I have a reservation'],
    ['enveisbillett', 'one-way ticket'],
    ['tur-retur', 'return ticket'],
    ['Kofferten min er borte', 'My suitcase is missing'],
    ['Hvor mye koster det?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['kabinansatt', 'flight attendant'],
    ['hattehylle', 'overhead bin'],
    ['håndbagasje', 'hand luggage'],
    ['taxi', 'taxi'],
    ['buss', 'bus'],
    ['tog', 'train'],
    ['hotell', 'hotel'],
    ['Jeg trenger hjelp', 'I need help'],
    ['Finnes det wifi?', 'Is there Wi‑Fi?'],
    ['utgang', 'exit'],
    ['inngang', 'entrance'],
    ['Snakker du engelsk?', 'Do you speak English?'],
    ['Jeg forstår ikke', 'I don\'t understand'],
    ['Snakk saktere, er du snill', 'Please speak more slowly'],
    ['Hvor er toalettet?', 'Where is the bathroom?'],
    ['hittegods', 'lost and found'],
    ['bytte', 'transfer'],
    ['korrespondanse', 'connection'],
    ['ombordstigningstid', 'boarding time'],
    ['passkontroll', 'passport control'],
  ]);

  packs.airport.byCategory["sv"] = buildEntries([
    ['flygplats', 'airport'],
    ['flyg', 'flight'],
    ['boardingkort', 'boarding pass'],
    ['pass', 'passport'],
    ['resväska', 'suitcase'],
    ['bagage', 'luggage'],
    ['gate', 'gate'],
    ['avgång', 'departure'],
    ['ankomst', 'arrival'],
    ['incheckning', 'check-in'],
    ['säkerhetskontroll', 'security'],
    ['tull', 'customs'],
    ['bagageband', 'baggage claim'],
    ['försenad', 'delayed'],
    ['inställd', 'cancelled'],
    ['i tid', 'on time'],
    ['biljett', 'ticket'],
    ['säte', 'seat'],
    ['fönsterplats', 'window seat'],
    ['gångplats', 'aisle seat'],
    ['ombordstigning', 'boarding'],
    ['att lyfta', 'to take off'],
    ['att landa', 'to land'],
    ['Var är gaten?', 'Where is the gate?'],
    ['Jag har en reservation', 'I have a reservation'],
    ['enkel biljett', 'one-way ticket'],
    ['tur och retur', 'return ticket'],
    ['Min resväska är borta', 'My suitcase is missing'],
    ['Hur mycket kostar det?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['kabinpersonal', 'flight attendant'],
    ['hatthylla', 'overhead bin'],
    ['handbagage', 'hand luggage'],
    ['taxi', 'taxi'],
    ['buss', 'bus'],
    ['tåg', 'train'],
    ['hotell', 'hotel'],
    ['Jag behöver hjälp', 'I need help'],
    ['Finns det wifi?', 'Is there Wi‑Fi?'],
    ['utgång', 'exit'],
    ['ingång', 'entrance'],
    ['Talar du engelska?', 'Do you speak English?'],
    ['Jag förstår inte', 'I don\'t understand'],
    ['Kan du tala långsammare?', 'Please speak more slowly'],
    ['Var är toaletten?', 'Where is the bathroom?'],
    ['hittegods', 'lost and found'],
    ['byte', 'transfer'],
    ['anslutning', 'connection'],
    ['ombordstigningstid', 'boarding time'],
    ['passkontroll', 'passport control'],
  ]);

  packs.airport.byCategory["da"] = buildEntries([
    ['lufthavn', 'airport'],
    ['fly', 'flight'],
    ['boardingkort', 'boarding pass'],
    ['pas', 'passport'],
    ['kuffert', 'suitcase'],
    ['bagage', 'luggage'],
    ['gate', 'gate'],
    ['afgang', 'departure'],
    ['ankomst', 'arrival'],
    ['check-in', 'check-in'],
    ['sikkerhedskontrol', 'security'],
    ['told', 'customs'],
    ['bagagebånd', 'baggage claim'],
    ['forsinket', 'delayed'],
    ['aflyst', 'cancelled'],
    ['til tiden', 'on time'],
    ['billet', 'ticket'],
    ['sæde', 'seat'],
    ['vinduesplads', 'window seat'],
    ['midtergangsplads', 'aisle seat'],
    ['boarding', 'boarding'],
    ['at lette', 'to take off'],
    ['at lande', 'to land'],
    ['Hvor er gaten?', 'Where is the gate?'],
    ['Jeg har en reservation', 'I have a reservation'],
    ['enkeltbillet', 'one-way ticket'],
    ['tur-retur', 'return ticket'],
    ['Min kuffert er væk', 'My suitcase is missing'],
    ['Hvor meget koster det?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['kabinepersonale', 'flight attendant'],
    ['hattehylde', 'overhead bin'],
    ['håndbagage', 'hand luggage'],
    ['taxa', 'taxi'],
    ['bus', 'bus'],
    ['tog', 'train'],
    ['hotel', 'hotel'],
    ['Jeg har brug for hjælp', 'I need help'],
    ['Er der wifi?', 'Is there Wi‑Fi?'],
    ['udgang', 'exit'],
    ['indgang', 'entrance'],
    ['Taler du engelsk?', 'Do you speak English?'],
    ['Jeg forstår ikke', 'I don\'t understand'],
    ['Tal langsommere, tak', 'Please speak more slowly'],
    ['Hvor er toilettet?', 'Where is the bathroom?'],
    ['hittegods', 'lost and found'],
    ['skift', 'transfer'],
    ['forbindelse', 'connection'],
    ['boardingtid', 'boarding time'],
    ['paskontrol', 'passport control'],
  ]);

  packs.airport.byCategory["de"] = buildEntries([
    ['Flughafen', 'airport'],
    ['Flug', 'flight'],
    ['Bordkarte', 'boarding pass'],
    ['Reisepass', 'passport'],
    ['Koffer', 'suitcase'],
    ['Gepäck', 'luggage'],
    ['Gate', 'gate'],
    ['Abflug', 'departure'],
    ['Ankunft', 'arrival'],
    ['Check-in', 'check-in'],
    ['Sicherheitskontrolle', 'security'],
    ['Zoll', 'customs'],
    ['Gepäckausgabe', 'baggage claim'],
    ['verspätet', 'delayed'],
    ['gestrichen', 'cancelled'],
    ['pünktlich', 'on time'],
    ['Ticket', 'ticket'],
    ['Sitzplatz', 'seat'],
    ['Fensterplatz', 'window seat'],
    ['Gangplatz', 'aisle seat'],
    ['Boarding', 'boarding'],
    ['abheben', 'to take off'],
    ['landen', 'to land'],
    ['Wo ist das Gate?', 'Where is the gate?'],
    ['Ich habe eine Reservierung', 'I have a reservation'],
    ['einfache Fahrkarte', 'one-way ticket'],
    ['Hin- und Rückfahrt', 'return ticket'],
    ['Mein Koffer ist weg', 'My suitcase is missing'],
    ['Was kostet das?', 'How much does it cost?'],
    ['Terminal', 'terminal'],
    ['Flugbegleiter', 'flight attendant'],
    ['Gepäckfach', 'overhead bin'],
    ['Handgepäck', 'hand luggage'],
    ['Taxi', 'taxi'],
    ['Bus', 'bus'],
    ['Zug', 'train'],
    ['Hotel', 'hotel'],
    ['Ich brauche Hilfe', 'I need help'],
    ['Gibt es WLAN?', 'Is there Wi‑Fi?'],
    ['Ausgang', 'exit'],
    ['Eingang', 'entrance'],
    ['Sprechen Sie Englisch?', 'Do you speak English?'],
    ['Ich verstehe nicht', 'I don\'t understand'],
    ['Sprechen Sie bitte langsamer', 'Please speak more slowly'],
    ['Wo ist die Toilette?', 'Where is the bathroom?'],
    ['Fundbüro', 'lost and found'],
    ['Umstieg', 'transfer'],
    ['Anschluss', 'connection'],
    ['Boardingzeit', 'boarding time'],
    ['Passkontrolle', 'passport control'],
  ]);

  packs.airport.byCategory["fr"] = buildEntries([
    ['aéroport', 'airport'],
    ['vol', 'flight'],
    ['carte d\'embarquement', 'boarding pass'],
    ['passeport', 'passport'],
    ['valise', 'suitcase'],
    ['bagages', 'luggage'],
    ['porte d\'embarquement', 'gate'],
    ['départ', 'departure'],
    ['arrivée', 'arrival'],
    ['enregistrement', 'check-in'],
    ['contrôle de sécurité', 'security'],
    ['douane', 'customs'],
    ['livraison des bagages', 'baggage claim'],
    ['retardé', 'delayed'],
    ['annulé', 'cancelled'],
    ['à l\'heure', 'on time'],
    ['billet', 'ticket'],
    ['siège', 'seat'],
    ['place côté fenêtre', 'window seat'],
    ['place côté couloir', 'aisle seat'],
    ['embarquement', 'boarding'],
    ['décoller', 'to take off'],
    ['atterrir', 'to land'],
    ['Où est la porte d\'embarquement ?', 'Where is the gate?'],
    ['J\'ai une réservation', 'I have a reservation'],
    ['aller simple', 'one-way ticket'],
    ['aller-retour', 'return ticket'],
    ['Ma valise a disparu', 'My suitcase is missing'],
    ['Combien ça coûte ?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['agent de bord', 'flight attendant'],
    ['coffre à bagages', 'overhead bin'],
    ['bagage à main', 'hand luggage'],
    ['taxi', 'taxi'],
    ['bus', 'bus'],
    ['train', 'train'],
    ['hôtel', 'hotel'],
    ['J\'ai besoin d\'aide', 'I need help'],
    ['Y a-t-il du Wi-Fi ?', 'Is there Wi‑Fi?'],
    ['sortie', 'exit'],
    ['entrée', 'entrance'],
    ['Parlez-vous anglais ?', 'Do you speak English?'],
    ['Je ne comprends pas', 'I don\'t understand'],
    ['Parlez plus lentement, s\'il vous plaît', 'Please speak more slowly'],
    ['Où sont les toilettes ?', 'Where is the bathroom?'],
    ['objets trouvés', 'lost and found'],
    ['correspondance', 'transfer'],
    ['connexion', 'connection'],
    ['heure d\'embarquement', 'boarding time'],
    ['contrôle des passeports', 'passport control'],
  ]);

  packs.airport.byCategory["es"] = buildEntries([
    ['aeropuerto', 'airport'],
    ['vuelo', 'flight'],
    ['tarjeta de embarque', 'boarding pass'],
    ['pasaporte', 'passport'],
    ['maleta', 'suitcase'],
    ['equipaje', 'luggage'],
    ['puerta de embarque', 'gate'],
    ['salida', 'departure'],
    ['llegada', 'arrival'],
    ['facturación', 'check-in'],
    ['control de seguridad', 'security'],
    ['aduana', 'customs'],
    ['recogida de equipajes', 'baggage claim'],
    ['retrasado', 'delayed'],
    ['cancelado', 'cancelled'],
    ['a tiempo', 'on time'],
    ['billete', 'ticket'],
    ['asiento', 'seat'],
    ['asiento de ventanilla', 'window seat'],
    ['asiento de pasillo', 'aisle seat'],
    ['embarque', 'boarding'],
    ['despegar', 'to take off'],
    ['aterrizar', 'to land'],
    ['¿Dónde está la puerta?', 'Where is the gate?'],
    ['Tengo una reserva', 'I have a reservation'],
    ['billete de ida', 'one-way ticket'],
    ['ida y vuelta', 'return ticket'],
    ['Falta mi maleta', 'My suitcase is missing'],
    ['¿Cuánto cuesta?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['auxiliar de vuelo', 'flight attendant'],
    ['compartimento superior', 'overhead bin'],
    ['equipaje de mano', 'hand luggage'],
    ['taxi', 'taxi'],
    ['autobús', 'bus'],
    ['tren', 'train'],
    ['hotel', 'hotel'],
    ['Necesito ayuda', 'I need help'],
    ['¿Hay wifi?', 'Is there Wi‑Fi?'],
    ['salida del edificio', 'exit'],
    ['entrada', 'entrance'],
    ['¿Habla inglés?', 'Do you speak English?'],
    ['No entiendo', 'I don\'t understand'],
    ['Hable más despacio, por favor', 'Please speak more slowly'],
    ['¿Dónde está el baño?', 'Where is the bathroom?'],
    ['objetos perdidos', 'lost and found'],
    ['transbordo', 'transfer'],
    ['conexión', 'connection'],
    ['hora de embarque', 'boarding time'],
    ['control de pasaportes', 'passport control'],
  ]);

  packs.airport.byCategory["it"] = buildEntries([
    ['aeroporto', 'airport'],
    ['volo', 'flight'],
    ['carta d\'imbarco', 'boarding pass'],
    ['passaporto', 'passport'],
    ['valigia', 'suitcase'],
    ['bagaglio', 'luggage'],
    ['gate', 'gate'],
    ['partenza', 'departure'],
    ['arrivo', 'arrival'],
    ['check-in', 'check-in'],
    ['controlli di sicurezza', 'security'],
    ['dogana', 'customs'],
    ['ritiro bagagli', 'baggage claim'],
    ['in ritardo', 'delayed'],
    ['cancellato', 'cancelled'],
    ['in orario', 'on time'],
    ['biglietto', 'ticket'],
    ['posto', 'seat'],
    ['posto finestrino', 'window seat'],
    ['posto corridoio', 'aisle seat'],
    ['imbarco', 'boarding'],
    ['decollare', 'to take off'],
    ['atterrare', 'to land'],
    ['Dov\'è il gate?', 'Where is the gate?'],
    ['Ho una prenotazione', 'I have a reservation'],
    ['andata', 'one-way ticket'],
    ['andata e ritorno', 'return ticket'],
    ['Manca la mia valigia', 'My suitcase is missing'],
    ['Quanto costa?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['assistente di volo', 'flight attendant'],
    ['vano bagagli', 'overhead bin'],
    ['bagaglio a mano', 'hand luggage'],
    ['taxi', 'taxi'],
    ['autobus', 'bus'],
    ['treno', 'train'],
    ['hotel', 'hotel'],
    ['Ho bisogno di aiuto', 'I need help'],
    ['C\'è il Wi-Fi?', 'Is there Wi‑Fi?'],
    ['uscita', 'exit'],
    ['entrata', 'entrance'],
    ['Parla inglese?', 'Do you speak English?'],
    ['Non capisco', 'I don\'t understand'],
    ['Parli più lentamente, per favore', 'Please speak more slowly'],
    ['Dov\'è il bagno?', 'Where is the bathroom?'],
    ['oggetti smarriti', 'lost and found'],
    ['coincidenza', 'transfer'],
    ['collegamento', 'connection'],
    ['ora d\'imbarco', 'boarding time'],
    ['controllo passaporti', 'passport control'],
  ]);

  packs.airport.byCategory["nl"] = buildEntries([
    ['luchthaven', 'airport'],
    ['vlucht', 'flight'],
    ['boardingpass', 'boarding pass'],
    ['paspoort', 'passport'],
    ['koffer', 'suitcase'],
    ['bagage', 'luggage'],
    ['gate', 'gate'],
    ['vertrek', 'departure'],
    ['aankomst', 'arrival'],
    ['inchecken', 'check-in'],
    ['veiligheidscontrole', 'security'],
    ['douane', 'customs'],
    ['bagageband', 'baggage claim'],
    ['vertraagd', 'delayed'],
    ['geannuleerd', 'cancelled'],
    ['op tijd', 'on time'],
    ['kaartje', 'ticket'],
    ['stoel', 'seat'],
    ['raamstoel', 'window seat'],
    ['gangpadstoel', 'aisle seat'],
    ['boarding', 'boarding'],
    ['opstijgen', 'to take off'],
    ['landen', 'to land'],
    ['Waar is de gate?', 'Where is the gate?'],
    ['Ik heb een reservering', 'I have a reservation'],
    ['enkele reis', 'one-way ticket'],
    ['retourtje', 'return ticket'],
    ['Mijn koffer is zoek', 'My suitcase is missing'],
    ['Hoeveel kost het?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['stewardess', 'flight attendant'],
    ['bagagevak', 'overhead bin'],
    ['handbagage', 'hand luggage'],
    ['taxi', 'taxi'],
    ['bus', 'bus'],
    ['trein', 'train'],
    ['hotel', 'hotel'],
    ['Ik heb hulp nodig', 'I need help'],
    ['Is er wifi?', 'Is there Wi‑Fi?'],
    ['uitgang', 'exit'],
    ['ingang', 'entrance'],
    ['Spreekt u Engels?', 'Do you speak English?'],
    ['Ik begrijp het niet', 'I don\'t understand'],
    ['Kunt u langzamer praten?', 'Please speak more slowly'],
    ['Waar is het toilet?', 'Where is the bathroom?'],
    ['gevonden voorwerpen', 'lost and found'],
    ['overstap', 'transfer'],
    ['aansluiting', 'connection'],
    ['boardingtijd', 'boarding time'],
    ['paspoortcontrole', 'passport control'],
  ]);

  packs.airport.byCategory["pt"] = buildEntries([
    ['aeroporto', 'airport'],
    ['voo', 'flight'],
    ['cartão de embarque', 'boarding pass'],
    ['passaporte', 'passport'],
    ['mala', 'suitcase'],
    ['bagagem', 'luggage'],
    ['portão', 'gate'],
    ['partida', 'departure'],
    ['chegada', 'arrival'],
    ['check-in', 'check-in'],
    ['segurança', 'security'],
    ['alfândega', 'customs'],
    ['esteira de bagagem', 'baggage claim'],
    ['atrasado', 'delayed'],
    ['cancelado', 'cancelled'],
    ['no horário', 'on time'],
    ['passagem', 'ticket'],
    ['assento', 'seat'],
    ['janela', 'window seat'],
    ['corredor', 'aisle seat'],
    ['embarque', 'boarding'],
    ['decolar', 'to take off'],
    ['pousar', 'to land'],
    ['Onde fica o portão?', 'Where is the gate?'],
    ['Tenho uma reserva', 'I have a reservation'],
    ['só ida', 'one-way ticket'],
    ['ida e volta', 'return ticket'],
    ['Minha mala sumiu', 'My suitcase is missing'],
    ['Quanto custa?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['comissário de bordo', 'flight attendant'],
    ['compartimento superior', 'overhead bin'],
    ['bagagem de mão', 'hand luggage'],
    ['táxi', 'taxi'],
    ['ônibus', 'bus'],
    ['trem', 'train'],
    ['hotel', 'hotel'],
    ['Preciso de ajuda', 'I need help'],
    ['Tem wi-fi?', 'Is there Wi‑Fi?'],
    ['saída', 'exit'],
    ['entrada', 'entrance'],
    ['Você fala inglês?', 'Do you speak English?'],
    ['Não entendo', 'I don\'t understand'],
    ['Fale mais devagar, por favor', 'Please speak more slowly'],
    ['Onde fica o banheiro?', 'Where is the bathroom?'],
    ['achados e perdidos', 'lost and found'],
    ['conexão', 'transfer'],
    ['ligação', 'connection'],
    ['horário de embarque', 'boarding time'],
    ['controle de passaporte', 'passport control'],
  ]);

  packs.airport.byCategory["pl"] = buildEntries([
    ['lotnisko', 'airport'],
    ['lot', 'flight'],
    ['karta pokładowa', 'boarding pass'],
    ['paszport', 'passport'],
    ['walizka', 'suitcase'],
    ['bagaż', 'luggage'],
    ['bramka', 'gate'],
    ['odlot', 'departure'],
    ['przylot', 'arrival'],
    ['odprawa', 'check-in'],
    ['kontrola bezpieczeństwa', 'security'],
    ['cło', 'customs'],
    ['odbiór bagażu', 'baggage claim'],
    ['opóźniony', 'delayed'],
    ['odwołany', 'cancelled'],
    ['na czas', 'on time'],
    ['bilet', 'ticket'],
    ['miejsce', 'seat'],
    ['miejsce przy oknie', 'window seat'],
    ['miejsce przy przejściu', 'aisle seat'],
    ['boarding', 'boarding'],
    ['startować', 'to take off'],
    ['lądować', 'to land'],
    ['Gdzie jest bramka?', 'Where is the gate?'],
    ['Mam rezerwację', 'I have a reservation'],
    ['bilet w jedną stronę', 'one-way ticket'],
    ['bilet w obie strony', 'return ticket'],
    ['Zginęła moja walizka', 'My suitcase is missing'],
    ['Ile to kosztuje?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['stewardesa', 'flight attendant'],
    ['półka na bagaż', 'overhead bin'],
    ['bagaż podręczny', 'hand luggage'],
    ['taksi', 'taxi'],
    ['autobus', 'bus'],
    ['pociąg', 'train'],
    ['hotel', 'hotel'],
    ['Potrzebuję pomocy', 'I need help'],
    ['Czy jest wi-fi?', 'Is there Wi‑Fi?'],
    ['wyjście', 'exit'],
    ['wejście', 'entrance'],
    ['Czy mówi pan po angielsku?', 'Do you speak English?'],
    ['Nie rozumiem', 'I don\'t understand'],
    ['Proszę mówić wolniej', 'Please speak more slowly'],
    ['Gdzie jest toaleta?', 'Where is the bathroom?'],
    ['biuro rzeczy znalezionych', 'lost and found'],
    ['przesiadka', 'transfer'],
    ['połączenie', 'connection'],
    ['godzina boardingu', 'boarding time'],
    ['kontrola paszportowa', 'passport control'],
  ]);

  root.THEMATIC_PACKS = packs;
  root.THEMATIC_PACK_LIST = Object.values(packs);
})(typeof window !== "undefined" ? window : globalThis);
