/**
 * Thematic mini-packs — opt-in extras (ranks 1001+).
 * Content law: 10 themes × 20 forms = 200 next-tier essentials per language.
 * One-word theme titles, mutually clear (no Travel/Transit confusables).
 * Norwegian curated first; other languages hold parallel concepts until their pass.
 */
(function (root) {
  const packs = {
    airport: {
      id: "airport",
      title: "Airport",
      blurb: "Flights, bags, and the gate.",
      byCategory: {},
    },
    transit: {
      id: "transit",
      title: "Transport",
      blurb: "Local rides, stops, and passes.",
      byCategory: {},
    },
    cafe: {
      id: "cafe",
      title: "Dining",
      blurb: "Ordering food and the bill.",
      byCategory: {},
    },
    campus: {
      id: "campus",
      title: "Studies",
      blurb: "Class, homework, and exams.",
      byCategory: {},
    },
    doctor: {
      id: "doctor",
      title: "Health",
      blurb: "Symptoms, care, and the pharmacy.",
      byCategory: {},
    },
    housing: {
      id: "housing",
      title: "Home",
      blurb: "Rent, rooms, and neighbors.",
      byCategory: {},
    },
    work: {
      id: "work",
      title: "Work",
      blurb: "Office, pay, and meetings.",
      byCategory: {},
    },
    shopping: {
      id: "shopping",
      title: "Shop",
      blurb: "Stores, sizes, and checkout.",
      byCategory: {},
    },
    social: {
      id: "social",
      title: "People",
      blurb: "Plans, parties, and friends.",
      byCategory: {},
    },
    money: {
      id: "money",
      title: "Bank",
      blurb: "Cards, cash, and accounts.",
      byCategory: {},
    },
  };

  function buildEntries(forms) {
    return forms.map((row) => {
      const foreign = String(row[0] || "").trim();
      const native = String(row[1] || "").trim();
      const exampleForeign = row[2] != null ? String(row[2]).trim() : "";
      const exampleNative = row[3] != null ? String(row[3]).trim() : "";
      const isPhrase = /\s|[?!…]/.test(foreign);
      const entry = {
        foreign,
        native,
        category: isPhrase ? "phrase" : native.startsWith("to ") ? "verb" : "noun",
        band: isPhrase ? "phrase" : "C",
      };
      if (exampleForeign && exampleNative) {
        entry.exampleForeign = exampleForeign;
        entry.exampleNative = exampleNative;
      } else if (isPhrase) {
        entry.exampleForeign = foreign;
        entry.exampleNative = native;
      }
      return entry;
    });
  }

  packs.airport.byCategory["nb-bokmal"] = buildEntries([
    ['boardingkort', 'boarding pass'],
    ['pass', 'passport'],
    ['koffert', 'suitcase'],
    ['bagasje', 'luggage'],
    ['avgang', 'departure'],
    ['ankomst', 'arrival'],
    ['innsjekking', 'check-in'],
    ['sikkerhetskontroll', 'security'],
    ['forsinket', 'delayed'],
    ['kansellert', 'cancelled'],
    ['sete', 'seat'],
    ['ombordstigning', 'boarding'],
    ['terminal', 'terminal'],
    ['håndbagasje', 'hand luggage'],
    ['passkontroll', 'passport control'],
    ['tur-retur', 'round-trip'],
    ['enveisbillett', 'one-way ticket'],
    ['å lande', 'to land'],
    ['plattform', 'platform'],
    ['spor', 'track / platform number'],
  ]);

  packs.airport.byCategory["sv"] = buildEntries([
    ['boardingkort', 'boarding pass'],
    ['pass', 'passport'],
    ['resväska', 'suitcase'],
    ['bagage', 'luggage'],
    ['avgång', 'departure'],
    ['ankomst', 'arrival'],
    ['incheckning', 'check-in'],
    ['säkerhetskontroll', 'security'],
    ['försenad', 'delayed'],
    ['inställd', 'cancelled'],
    ['säte', 'seat'],
    ['ombordstigning', 'boarding'],
    ['terminal', 'terminal'],
    ['handbagage', 'hand luggage'],
    ['passkontroll', 'passport control'],
    ['tur och retur', 'round-trip'],
    ['enkel biljett', 'one-way ticket'],
    ['att landa', 'to land'],
    ['plattform', 'platform'],
    ['spår', 'track / platform number'],
  ]);

  packs.airport.byCategory["da"] = buildEntries([
    ['boardingkort', 'boarding pass'],
    ['pas', 'passport'],
    ['flyselskab', 'airline'],
    ['bagagebånd', 'baggage carousel'],
    ['afgangstid', 'departure time'],
    ['ankomsttid', 'arrival time'],
    ['check-in', 'check-in'],
    ['sikkerhedskontrol', 'security'],
    ['forsinket', 'delayed'],
    ['aflyst', 'cancelled'],
    ['sæde', 'seat'],
    ['boarding', 'boarding'],
    ['terminal', 'terminal'],
    ['håndbagage', 'hand luggage'],
    ['paskontrol', 'passport control'],
    ['tur-retur', 'round-trip'],
    ['enkeltbillet', 'one-way ticket'],
    ['at lande', 'to land'],
    ['boardinggate', 'boarding gate'],
    ['spor', 'track / platform number'],
  ]);

  packs.airport.byCategory["de"] = buildEntries([
    ['Bordkarte', 'boarding pass'],
    ['Reisepass', 'passport'],
    ['Fluggesellschaft', 'airline'],
    ['Gepäckband', 'baggage carousel'],
    ['Abflugzeit', 'departure time'],
    ['Ankunftszeit', 'arrival time'],
    ['Check-in', 'check-in'],
    ['Sicherheitskontrolle', 'security'],
    ['verspätet', 'delayed'],
    ['gestrichen', 'cancelled'],
    ['Sitzplatz', 'seat'],
    ['Boarding', 'boarding'],
    ['Terminal', 'terminal'],
    ['Handgepäck', 'hand luggage'],
    ['Passkontrolle', 'passport control'],
    ['Hin und zurück', 'round-trip'],
    ['Einfache Fahrt', 'one-way ticket'],
    ['landen', 'to land'],
    ['Bahnsteig', 'platform'],
    ['Gleis', 'track / platform number'],
  ]);

  packs.airport.byCategory["fr"] = buildEntries([
    ['zone d\'embarquement', 'boarding area'],
    ['contrôle de sécurité', 'security check'],
    ['tapis roulant', 'baggage carousel'],
    ['chariot à bagages', 'luggage cart'],
    ['enregistrement des bagages', 'baggage check-in'],
    ['vol retardé', 'delayed flight'],
    ['porte d\'embarquement', 'boarding gate'],
    ['passeport biométrique', 'biometric passport'],
    ['duty free', 'duty-free shop'],
    ['navette aéroport', 'airport shuttle'],
    ['comptoir d\'information', 'information desk'],
    ['hall d\'embarquement', 'boarding lounge'],
    ['retrait des bagages', 'baggage claim'],
    ['vol en correspondance', 'connecting flight'],
    ['carte d\'embarquement', 'boarding pass'],
    ['détecteur de métaux', 'metal detector'],
    ['escale', 'layover'],
    ['terminal 2', 'terminal 2'],
    ['douane', 'customs'],
    ['bus Air France', 'Air France bus'],
  ]);

  packs.airport.byCategory["es"] = buildEntries([
    ['tarjeta de embarque', 'boarding pass'],
    ['pasaporte', 'passport'],
    ['aerolínea', 'airline'],
    ['equipaje', 'luggage'],
    ['hora de salida', 'departure time'],
    ['llegada', 'arrival'],
    ['facturación', 'check-in'],
    ['control de seguridad', 'security'],
    ['retrasado', 'delayed'],
    ['cancelado', 'cancelled'],
    ['puerta de embarque', 'boarding gate'],
    ['embarque', 'boarding'],
    ['terminal', 'terminal'],
    ['equipaje de mano', 'hand luggage'],
    ['control de pasaportes', 'passport control'],
    ['ida y vuelta', 'round-trip'],
    ['solo ida', 'one-way ticket'],
    ['aterrizar', 'to land'],
    ['andén', 'platform'],
    ['vía', 'track / platform number'],
  ]);

  packs.airport.byCategory["it"] = buildEntries([
    ['carta d\'imbarco', 'boarding pass'],
    ['controllo di sicurezza', 'security check'],
    ['nastro trasportatore', 'baggage carousel'],
    ['carrello bagagli', 'luggage cart'],
    ['check-in bagagli', 'baggage check-in'],
    ['volo in ritardo', 'delayed flight'],
    ['gate di imbarco', 'boarding gate'],
    ['passaporto biometrico', 'biometric passport'],
    ['duty free', 'duty-free shop'],
    ['navetta aeroporto', 'airport shuttle'],
    ['banco informazioni', 'information desk'],
    ['ritiro bagagli', 'baggage claim'],
    ['volo in coincidenza', 'connecting flight'],
    ['metal detector', 'metal detector'],
    ['scalo', 'layover'],
    ['terminal', 'terminal'],
    ['dogana', 'customs'],
    ['area partenze', 'departures area'],
    ['area arrivi', 'arrivals area'],
    ['bus di linea', 'airport bus'],
  ]);

  packs.airport.byCategory["nl"] = buildEntries([
    ['boardingkaart', 'boarding pass'],
    ['veiligheidscontrole', 'security check'],
    ['bagageband', 'baggage carousel'],
    ['bagagekar', 'luggage cart'],
    ['inchecken bagage', 'baggage check-in'],
    ['vertraagde vlucht', 'delayed flight'],
    ['boardinggate', 'boarding gate'],
    ['biometrisch paspoort', 'biometric passport'],
    ['dutyfree', 'duty-free shop'],
    ['luchthavenbus', 'airport shuttle'],
    ['informatiebalie', 'information desk'],
    ['bagageafhaal', 'baggage claim'],
    ['aansluitende vlucht', 'connecting flight'],
    ['metaaldetector', 'metal detector'],
    ['tussenlanding', 'layover'],
    ['terminal', 'terminal'],
    ['douane', 'customs'],
    ['vertrekhal', 'departures hall'],
    ['aankomsthal', 'arrivals hall'],
    ['luchthaventaxi', 'airport taxi'],
  ]);

  packs.airport.byCategory["pt"] = buildEntries([
    ['cartão de embarque', 'boarding pass'],
    ['passaporte', 'passport'],
    ['mala', 'suitcase'],
    ['bagagem', 'luggage'],
    ['partida', 'departure'],
    ['chegada', 'arrival'],
    ['check-in', 'check-in'],
    ['controle de segurança', 'security'],
    ['atrasado', 'delayed'],
    ['cancelado', 'cancelled'],
    ['assento', 'seat'],
    ['embarque', 'boarding'],
    ['terminal', 'terminal'],
    ['bagagem de mão', 'hand luggage'],
    ['controle de passaporte', 'passport control'],
    ['ida e volta', 'round-trip'],
    ['só ida', 'one-way ticket'],
    ['pousar', 'to land'],
    ['plataforma', 'platform'],
    ['plataforma', 'track / platform number'],
  ]);

  packs.airport.byCategory["pl"] = buildEntries([
    ['karta pokładowa', 'boarding pass'],
    ['paszport', 'passport'],
    ['walizka', 'suitcase'],
    ['bagaż', 'luggage'],
    ['odlot', 'departure'],
    ['przylot', 'arrival'],
    ['odprawa', 'check-in'],
    ['kontrola bezpieczeństwa', 'security'],
    ['opóźniony', 'delayed'],
    ['odwołany', 'cancelled'],
    ['miejsce', 'seat'],
    ['wejście na pokład', 'boarding'],
    ['terminal', 'terminal'],
    ['bagaż podręczny', 'hand luggage'],
    ['kontrola paszportowa', 'passport control'],
    ['w obie strony', 'round-trip'],
    ['w jedną stronę', 'one-way ticket'],
    ['lądować', 'to land'],
    ['peron', 'platform'],
    ['tor', 'track / platform number'],
  ]);

  packs.transit.byCategory["nb-bokmal"] = buildEntries([
    ['trikk', 'tram'],
    ['t-bane', 'subway / metro'],
    ['holdeplass', 'stop (bus/tram)'],
    ['rutetabell', 'timetable'],
    ['månedskort', 'monthly pass'],
    ['bysykkel', 'city bike'],
    ['fortau', 'sidewalk'],
    ['veikryss', 'intersection'],
    ['rundkjøring', 'roundabout'],
    ['forsinkelse', 'delay'],
    ['endestasjon', 'last stop / terminus'],
    ['billettautomat', 'ticket machine'],
    ['sone', 'zone (fare)'],
    ['rushtid', 'rush hour'],
    ['gågate', 'pedestrian street'],
    ['overgang', 'transfer / crossing'],
    ['byttebuss', 'connecting bus'],
    ['rute', 'route'],
    ['taxi', 'taxi'],
    ['parkeringsplass', 'parking space'],
  ]);

  packs.transit.byCategory["sv"] = buildEntries([
    ['spårvagn', 'tram'],
    ['tunnelbana', 'subway / metro'],
    ['hållplats', 'stop (bus/tram)'],
    ['tidtabell', 'timetable'],
    ['månadskort', 'monthly pass'],
    ['stadscykel', 'city bike'],
    ['trottoar', 'sidewalk'],
    ['korsning', 'intersection'],
    ['rondell', 'roundabout'],
    ['försening', 'delay'],
    ['ändhållplats', 'last stop / terminus'],
    ['biljettautomat', 'ticket machine'],
    ['zon', 'zone (fare)'],
    ['rusningstid', 'rush hour'],
    ['gågata', 'pedestrian street'],
    ['byte', 'transfer / crossing'],
    ['bytesbuss', 'connecting bus'],
    ['linje', 'route'],
    ['taxi', 'taxi'],
    ['parkeringsplats', 'parking space'],
  ]);

  packs.transit.byCategory["da"] = buildEntries([
    ['letbane', 'light rail'],
    ['S-tog', 'S-train'],
    ['stoppested', 'stop (bus/tram)'],
    ['afgangstavle', 'departure board'],
    ['rejsekort', 'travel card'],
    ['bycykel', 'city bike'],
    ['fortov', 'sidewalk'],
    ['vejkryds', 'intersection'],
    ['rundkørsel', 'roundabout'],
    ['sparebus', 'replacement bus'],
    ['endestation', 'last stop / terminus'],
    ['billetautomat', 'ticket machine'],
    ['zone', 'zone (fare)'],
    ['myldretid', 'rush hour'],
    ['gågade', 'pedestrian street'],
    ['skift', 'transfer / crossing'],
    ['skiftebus', 'connecting bus'],
    ['rute', 'route'],
    ['taxa', 'taxi'],
    ['parkeringsplads', 'parking space'],
  ]);

  packs.transit.byCategory["de"] = buildEntries([
    ['Stadtbahn', 'light rail / city train'],
    ['S-Bahn', 'S-train / suburban rail'],
    ['Haltestelle', 'stop (bus/tram)'],
    ['Abfahrtstafel', 'departure board'],
    ['Deutschlandticket', 'Germany-wide transit pass'],
    ['Stadtrad', 'city bike'],
    ['Bürgersteig', 'sidewalk'],
    ['Kreuzung', 'intersection'],
    ['Kreisverkehr', 'roundabout'],
    ['Ersatzbus', 'replacement bus'],
    ['Endhaltestelle', 'last stop / terminus'],
    ['Pendlerausweis', 'commuter pass'],
    ['Zone', 'zone (fare)'],
    ['Rushhour', 'rush hour'],
    ['Fußgängerzone', 'pedestrian street'],
    ['Umstieg', 'transfer / crossing'],
    ['Anschlussbus', 'connecting bus'],
    ['Linie', 'route'],
    ['Taxi', 'taxi'],
    ['Parkhaus', 'parking garage'],
  ]);

  packs.transit.byCategory["fr"] = buildEntries([
    ['ligne 1 du métro', 'metro line 1'],
    ['ticket t+', 't+ ticket'],
    ['carte Navigo', 'Navigo pass'],
    ['RER', 'RER regional train'],
    ['changement de ligne', 'line change'],
    ['interconnexion', 'line interconnection'],
    ['composteur', 'ticket validator'],
    ['quai numéro 3', 'platform number 3'],
    ['grève des transports', 'transport strike'],
    ['Vélib\'', 'Vélib\' bike share'],
    ['autobus 27', 'bus 27'],
    ['borne de recharge', 'charging station'],
    ['covoiturage', 'carpooling'],
    ['tramway', 'tram'],
    ['gare SNCF', 'SNCF station'],
    ['pass Navigo Mois', 'monthly Navigo pass'],
    ['validation', 'ticket validation'],
    ['retard de train', 'train delay'],
    ['sortie du métro', 'metro exit'],
    ['billet aller-retour', 'round-trip ticket'],
  ]);

  packs.transit.byCategory["es"] = buildEntries([
    ['tranvía', 'tram'],
    ['cercanías', 'commuter rail'],
    ['cabecera de línea', 'end of the line / terminus'],
    ['horario', 'timetable'],
    ['abono mensual', 'monthly pass'],
    ['bici pública', 'city bike'],
    ['acera', 'sidewalk'],
    ['cruce', 'intersection'],
    ['rotonda', 'roundabout'],
    ['retraso', 'delay'],
    ['última parada', 'last stop'],
    ['máquina de billetes', 'ticket machine'],
    ['zona', 'zone (fare)'],
    ['hora punta', 'rush hour'],
    ['calle peatonal', 'pedestrian street'],
    ['transbordo', 'transfer / crossing'],
    ['bus de enlace', 'connecting bus'],
    ['línea', 'route'],
    ['VTC', 'ride-hail / private hire'],
    ['plaza de aparcamiento', 'parking space'],
  ]);

  packs.transit.byCategory["it"] = buildEntries([
    ['biglietto ordinario', 'ordinary ticket'],
    ['abbonamento mensile', 'monthly pass'],
    ['linea metro', 'metro line'],
    ['cambio linea', 'line change'],
    ['coincidenza', 'connection'],
    ['validatrice', 'ticket validator'],
    ['binario', 'platform'],
    ['sciopero mezzi', 'transport strike'],
    ['bike sharing', 'bike share'],
    ['stazione Trenitalia', 'Trenitalia station'],
    ['Freccia Rossa', 'high-speed train'],
    ['biglietto regionale', 'regional ticket'],
    ['tessera ATM', 'ATM transport card'],
    ['orario dei treni', 'train timetable'],
    ['ritardo treno', 'train delay'],
    ['uscita metro', 'metro exit'],
    ['biglietto andata e ritorno', 'round-trip ticket'],
    ['autobus urbano', 'city bus'],
    ['tram', 'tram'],
    ['parcheggio di scambio', 'park-and-ride'],
  ]);

  packs.transit.byCategory["nl"] = buildEntries([
    ['OV-chipkaart', 'public transport chip card'],
    ['NS-kaartje', 'NS train ticket'],
    ['metrolijn', 'metro line'],
    ['overstap', 'transfer / change of line'],
    ['aansluiting', 'connection'],
    ['incheckpaal', 'check-in pole'],
    ['perron', 'platform'],
    ['staking openbaar vervoer', 'public transport strike'],
    ['deelfiets', 'shared bike'],
    ['NS-station', 'NS station'],
    ['Intercity', 'Intercity train'],
    ['streekbus', 'regional bus'],
    ['dienstregeling', 'timetable'],
    ['vertraging', 'delay'],
    ['metro-uitgang', 'metro exit'],
    ['retourticket', 'return ticket'],
    ['tram', 'tram'],
    ['P+R', 'park and ride'],
    ['ov-chipkaart opladen', 'top up OV-chipkaart'],
    ['sprinter', 'local train'],
  ]);

  packs.transit.byCategory["pt"] = buildEntries([
    ['bonde', 'tram'],
    ['metrô', 'subway / metro'],
    ['ponto', 'stop (bus/tram)'],
    ['horário', 'timetable'],
    ['passe mensal', 'monthly pass'],
    ['bike compartilhada', 'city bike'],
    ['calçada', 'sidewalk'],
    ['cruzamento', 'intersection'],
    ['rotatória', 'roundabout'],
    ['atraso', 'delay'],
    ['ponto final', 'last stop / terminus'],
    ['máquina de bilhetes', 'ticket machine'],
    ['zona', 'zone (fare)'],
    ['hora do rush', 'rush hour'],
    ['rua de pedestres', 'pedestrian street'],
    ['baldeação', 'transfer / crossing'],
    ['ônibus de conexão', 'connecting bus'],
    ['linha', 'route'],
    ['táxi', 'taxi'],
    ['vaga de estacionamento', 'parking space'],
  ]);

  packs.transit.byCategory["pl"] = buildEntries([
    ['tramwaj', 'tram'],
    ['metro', 'subway / metro'],
    ['przystanek', 'stop (bus/tram)'],
    ['rozkład jazdy', 'timetable'],
    ['bilet miesięczny', 'monthly pass'],
    ['rower miejski', 'city bike'],
    ['chodnik', 'sidewalk'],
    ['skrzyżowanie', 'intersection'],
    ['rondo', 'roundabout'],
    ['opóźnienie', 'delay'],
    ['pętla', 'last stop / terminus'],
    ['biletomat', 'ticket machine'],
    ['strefa', 'zone (fare)'],
    ['godziny szczytu', 'rush hour'],
    ['ulica piesza', 'pedestrian street'],
    ['przesiadka', 'transfer / crossing'],
    ['autobus przesiadkowy', 'connecting bus'],
    ['linia', 'route'],
    ['taksówka', 'taxi'],
    ['miejsce parkingowe', 'parking space'],
  ]);

  packs.cafe.byCategory["nb-bokmal"] = buildEntries([
    ['kafe', 'café'],
    ['meny', 'menu'],
    ['kelner', 'waiter'],
    ['regning', 'bill / check'],
    ['frokost', 'breakfast'],
    ['lunsj', 'lunch'],
    ['vegetarisk', 'vegetarian'],
    ['å bestille', 'to order'],
    ['te', 'tea'],
    ['øl', 'beer'],
    ['vin', 'wine'],
    ['tips', 'tip'],
    ['stengt', 'closed'],
    ['takeaway', 'takeaway'],
    ['reservasjon', 'reservation'],
    ['krydret', 'spicy'],
    ['mett', 'full (from food)'],
    ['uten melk', 'without milk'],
    ['dessert', 'dessert'],
    ['Hva anbefaler du?', 'What do you recommend?'],
  ]);

  packs.cafe.byCategory["sv"] = buildEntries([
    ['café', 'café'],
    ['meny', 'menu'],
    ['servitör', 'waiter'],
    ['nota', 'bill / check'],
    ['frukost', 'breakfast'],
    ['lunch', 'lunch'],
    ['vegetarisk', 'vegetarian'],
    ['att beställa', 'to order'],
    ['te', 'tea'],
    ['öl', 'beer'],
    ['vin', 'wine'],
    ['dricks', 'tip'],
    ['stängt', 'closed'],
    ['takeaway', 'takeaway'],
    ['reservation', 'reservation'],
    ['stark', 'spicy'],
    ['mätt', 'full (from food)'],
    ['utan mjölk', 'without milk'],
    ['efterrätt', 'dessert'],
    ['Vad rekommenderar du?', 'What do you recommend?'],
  ]);

  packs.cafe.byCategory["da"] = buildEntries([
    ['café', 'café'],
    ['menu', 'menu'],
    ['tjener', 'waiter'],
    ['kassebon', 'receipt'],
    ['brunch', 'brunch'],
    ['dagens ret', 'dish of the day'],
    ['laktosefri', 'lactose-free'],
    ['at bestille', 'to order'],
    ['te', 'tea'],
    ['mineralvand', 'sparkling water'],
    ['cappuccino', 'cappuccino'],
    ['serviceafgift', 'service charge'],
    ['bordbestilling', 'table reservation'],
    ['takeaway', 'takeaway'],
    ['reservation', 'reservation'],
    ['stærk', 'spicy'],
    ['mæt', 'full (from food)'],
    ['uden mælk', 'without milk'],
    ['forretter', 'starters / appetizers'],
    ['Hvad anbefaler du?', 'What do you recommend?'],
  ]);

  packs.cafe.byCategory["de"] = buildEntries([
    ['Café', 'café'],
    ['Speisekarte', 'menu'],
    ['Kellner', 'waiter'],
    ['Kassenquittung', 'receipt'],
    ['Brunch', 'brunch'],
    ['Tagesgericht', 'dish of the day'],
    ['laktosefrei', 'lactose-free'],
    ['bestellen', 'to order'],
    ['Tee', 'tea'],
    ['Mineralwasser', 'sparkling water'],
    ['Cappuccino', 'cappuccino'],
    ['Servicegebühr', 'service charge'],
    ['Tischreservierung', 'table reservation'],
    ['zum Mitnehmen', 'takeaway'],
    ['Reservierung', 'reservation'],
    ['scharf', 'spicy'],
    ['satt', 'full (from food)'],
    ['ohne Milch', 'without milk'],
    ['Vorspeisen', 'starters / appetizers'],
    ['Was empfehlen Sie?', 'What do you recommend?'],
  ]);

  packs.cafe.byCategory["fr"] = buildEntries([
    ['café crème', 'coffee with milk'],
    ['addition s\'il vous plaît', 'the check please'],
    ['terrasse', 'outdoor seating'],
    ['plat du jour', 'dish of the day'],
    ['serveur', 'waiter'],
    ['carte des vins', 'wine list'],
    ['croissant aux amandes', 'almond croissant'],
    ['menu déjeuner', 'lunch set menu'],
    ['eau gazeuse', 'sparkling water'],
    ['formule entrée-plat', 'starter + main set'],
    ['pain perdu', 'French toast'],
    ['pourboire', 'tip'],
    ['brasserie', 'brasserie'],
    ['expresso serré', 'strong espresso'],
    ['salade niçoise', 'Niçoise salad'],
    ['fromage blanc', 'fromage blanc'],
    ['omelette aux fines herbes', 'herb omelette'],
    ['kir', 'kir aperitif'],
    ['tarte Tatin', 'tarte Tatin'],
    ['déjeuner d\'affaires', 'business lunch'],
  ]);

  packs.cafe.byCategory["es"] = buildEntries([
    ['carta de bebidas', 'drinks menu'],
    ['menú', 'menu'],
    ['camarero', 'waiter'],
    ['recibo', 'receipt / bill'],
    ['brunch', 'brunch'],
    ['plato del día', 'dish of the day'],
    ['vegetariano', 'vegetarian'],
    ['reserva de mesa', 'table reservation'],
    ['agua con gas', 'sparkling water'],
    ['capuchino', 'cappuccino'],
    ['sin lactosa', 'lactose-free'],
    ['propina', 'tip'],
    ['entrantes', 'starters / appetizers'],
    ['para llevar', 'takeaway'],
    ['reserva', 'reservation'],
    ['picante', 'spicy'],
    ['cargo por servicio', 'service charge'],
    ['sin leche', 'without milk'],
    ['postre', 'dessert'],
    ['¿Qué recomienda?', 'What do you recommend?'],
  ]);

  packs.cafe.byCategory["it"] = buildEntries([
    ['caffè macchiato', 'macchiato'],
    ['conto per favore', 'the bill please'],
    ['terrazza', 'terrace seating'],
    ['piatto del giorno', 'dish of the day'],
    ['barista', 'barista'],
    ['carta dei vini', 'wine list'],
    ['cornetto', 'croissant'],
    ['menu pranzo', 'lunch menu'],
    ['acqua frizzante', 'sparkling water'],
    ['formula pranzo', 'lunch set menu'],
    ['aperitivo', 'aperitif'],
    ['cappuccino', 'cappuccino'],
    ['tiramisù', 'tiramisu'],
    ['spritz', 'spritz'],
    ['coperto', 'cover charge'],
    ['servizio incluso', 'service included'],
    ['banco del bar', 'bar counter'],
    ['prima colazione', 'breakfast'],
    ['panino', 'sandwich'],
    ['gelato artigianale', 'artisanal gelato'],
  ]);

  packs.cafe.byCategory["nl"] = buildEntries([
    ['koffie verkeerd', 'latte'],
    ['rekening alstublieft', 'the bill please'],
    ['terras', 'terrace'],
    ['dagschotel', 'dish of the day'],
    ['bediening', 'wait staff'],
    ['wijnkaart', 'wine list'],
    ['croissant', 'croissant'],
    ['lunchmenu', 'lunch menu'],
    ['mineraalwater', 'sparkling / mineral water'],
    ['dagmenu', 'set lunch'],
    ['borrel', 'aperitif drinks'],
    ['cappuccino', 'cappuccino'],
    ['appeltaart', 'apple pie'],
    ['bitterballen', 'bitterballen'],
    ['fooienpot', 'tip jar'],
    ['bar', 'bar counter'],
    ['ontbijtbuffet', 'breakfast buffet'],
    ['belegd broodje', 'filled sandwich'],
    ['ambachtelijk ijs', 'artisanal ice cream'],
    ['pilsje', 'glass of beer'],
  ]);

  packs.cafe.byCategory["pt"] = buildEntries([
    ['café', 'café'],
    ['cardápio', 'menu'],
    ['garçom', 'waiter'],
    ['conta', 'bill / check'],
    ['café da manhã', 'breakfast'],
    ['almoço', 'lunch'],
    ['vegetariano', 'vegetarian'],
    ['pedir', 'to order'],
    ['chá', 'tea'],
    ['cerveja', 'beer'],
    ['vinho', 'wine'],
    ['gorjeta', 'tip'],
    ['fechado', 'closed'],
    ['para viagem', 'takeaway'],
    ['reserva', 'reservation'],
    ['apimentado', 'spicy'],
    ['cheio', 'full (from food)'],
    ['sem leite', 'without milk'],
    ['sobremesa', 'dessert'],
    ['O que você recomenda?', 'What do you recommend?'],
  ]);

  packs.cafe.byCategory["pl"] = buildEntries([
    ['kawiarnia', 'café'],
    ['menu', 'menu'],
    ['kelner', 'waiter'],
    ['rachunek', 'bill / check'],
    ['śniadanie', 'breakfast'],
    ['obiad', 'lunch'],
    ['wegetariański', 'vegetarian'],
    ['zamawiać', 'to order'],
    ['herbata', 'tea'],
    ['piwo', 'beer'],
    ['wino', 'wine'],
    ['napiwek', 'tip'],
    ['zamknięte', 'closed'],
    ['na wynos', 'takeaway'],
    ['rezerwacja', 'reservation'],
    ['ostry', 'spicy'],
    ['najedzony', 'full (from food)'],
    ['bez mleka', 'without milk'],
    ['deser', 'dessert'],
    ['Co pan poleca?', 'What do you recommend?'],
  ]);

  packs.campus.byCategory["nb-bokmal"] = buildEntries([
    ['seminar', 'seminar'],
    ['lekser', 'homework'],
    ['klasserom', 'classroom'],
    ['lærer', 'teacher'],
    ['medstudent', 'classmate'],
    ['studentbevis', 'student ID'],
    ['studentbolig', 'student housing'],
    ['gruppearbeid', 'group work'],
    ['kontortid', 'office hours'],
    ['lab', 'lab'],
    ['masteroppgave', 'master\'s thesis'],
    ['å stryke', 'to fail (an exam)'],
    ['utvekslingsstudent', 'exchange student'],
    ['å notere', 'to take notes'],
    ['auditorium', 'lecture hall'],
    ['emne', 'course'],
    ['oppmelding', 'enrollment'],
    ['å bestå', 'to pass'],
    ['pensumliste', 'reading list'],
    ['Kan du gjenta det?', 'Could you repeat that?'],
  ]);

  packs.campus.byCategory["sv"] = buildEntries([
    ['seminarium', 'seminar'],
    ['läxor', 'homework'],
    ['klassrum', 'classroom'],
    ['lärare', 'teacher'],
    ['kurskamrat', 'classmate'],
    ['studentleg', 'student ID'],
    ['studentbostad', 'student housing'],
    ['grupparbete', 'group work'],
    ['mottagningstid', 'office hours'],
    ['labb', 'lab'],
    ['masteruppsats', 'master\'s thesis'],
    ['att kugga', 'to fail (an exam)'],
    ['utbytesstudent', 'exchange student'],
    ['att anteckna', 'to take notes'],
    ['hörsal', 'lecture hall'],
    ['kurs', 'course'],
    ['anmälan', 'enrollment'],
    ['att klara', 'to pass'],
    ['kurslitteratur', 'reading list'],
    ['Kan du upprepa det?', 'Could you repeat that?'],
  ]);

  packs.campus.byCategory["da"] = buildEntries([
    ['forelæsning', 'lecture'],
    ['lektier', 'homework'],
    ['klasselokale', 'classroom'],
    ['underviser', 'instructor'],
    ['medstuderende', 'classmate'],
    ['studieplads', 'study desk / place'],
    ['studiebolig', 'student housing'],
    ['studiegruppe', 'study group'],
    ['vejledning', 'academic advising'],
    ['lab', 'lab'],
    ['speciale', 'master\'s thesis'],
    ['at dumpe', 'to fail (an exam)'],
    ['udveksling', 'exchange program'],
    ['at notere', 'to take notes'],
    ['auditorium', 'lecture hall'],
    ['fag', 'course'],
    ['eksamenstilmelding', 'exam registration'],
    ['at bestå', 'to pass'],
    ['pensum', 'reading list'],
    ['Kan du gentage det?', 'Could you repeat that?'],
  ]);

  packs.campus.byCategory["de"] = buildEntries([
    ['Vorlesung', 'lecture'],
    ['Hausaufgaben', 'homework'],
    ['Klassenzimmer', 'classroom'],
    ['Dozent', 'lecturer / instructor'],
    ['Kommilitone', 'classmate'],
    ['Lernplatz', 'study desk / place'],
    ['Studentenwohnheim', 'student housing'],
    ['Lerngruppe', 'study group'],
    ['Studienberatung', 'academic advising'],
    ['Tutorium', 'tutorial session'],
    ['Masterarbeit', 'master\'s thesis'],
    ['durchfallen', 'to fail (an exam)'],
    ['Austauschprogramm', 'exchange program'],
    ['mitschreiben', 'to take notes'],
    ['Studentenwohnung', 'student flat'],
    ['Prüfungsanmeldung', 'exam registration'],
    ['Studienordnung', 'degree regulations'],
    ['bestehen', 'to pass'],
    ['Literaturliste', 'reading list'],
    ['Können Sie das wiederholen?', 'Could you repeat that?'],
  ]);

  packs.campus.byCategory["fr"] = buildEntries([
    ['bibliothèque universitaire', 'university library'],
    ['TD', 'tutorial class (TD)'],
    ['amphi', 'lecture hall'],
    ['carte étudiante', 'student card'],
    ['campus de Jussieu', 'Jussieu campus'],
    ['mémoire de master', 'master\'s thesis'],
    ['rentrée universitaire', 'start of term'],
    ['polycopié', 'course handout'],
    ['bureau des inscriptions', 'registrar\'s office'],
    ['Erasmus', 'Erasmus exchange'],
    ['tutorat', 'tutoring'],
    ['cité U', 'student residence'],
    ['partiel', 'midterm exam'],
    ['licence', 'bachelor\'s degree'],
    ['doctorat', 'PhD'],
    ['salle de travaux pratiques', 'lab room'],
    ['CROUS', 'student services (CROUS)'],
    ['bourse', 'scholarship'],
    ['syllabus', 'course outline'],
    ['orientation', 'academic advising'],
  ]);

  packs.campus.byCategory["es"] = buildEntries([
    ['seminario', 'seminar'],
    ['deberes', 'homework'],
    ['aula', 'classroom'],
    ['docente', 'instructor'],
    ['compañero de clase', 'classmate'],
    ['carnet de estudiante', 'student ID'],
    ['residencia de estudiantes', 'student housing'],
    ['trabajo en grupo', 'group work'],
    ['horario de tutoría', 'office hours'],
    ['tutorías', 'office hours / tutorials'],
    ['tesis de máster', 'master\'s thesis'],
    ['suspender', 'to fail (an exam)'],
    ['estudiante de intercambio', 'exchange student'],
    ['tomar apuntes', 'to take notes'],
    ['aula magna', 'lecture hall'],
    ['asignatura', 'course'],
    ['matrícula', 'enrollment'],
    ['aprobar', 'to pass'],
    ['lista de lecturas', 'reading list'],
    ['¿Puede repetir?', 'Could you repeat that?'],
  ]);

  packs.campus.byCategory["it"] = buildEntries([
    ['biblioteca universitaria', 'university library'],
    ['esercitazione', 'tutorial session'],
    ['aula magna', 'main lecture hall'],
    ['tessera studente', 'student card'],
    ['tesi di laurea', 'degree thesis'],
    ['inizio anno accademico', 'start of academic year'],
    ['dispense', 'course notes'],
    ['segreteria studenti', 'student registry'],
    ['Erasmus', 'Erasmus exchange'],
    ['tutorato', 'tutoring'],
    ['studentato', 'student residence'],
    ['esame parziale', 'mid-term exam'],
    ['laurea triennale', 'bachelor\'s degree'],
    ['dottorato', 'PhD'],
    ['aula informatica', 'computer lab'],
    ['diritto allo studio', 'right to study support'],
    ['borsa di studio', 'scholarship'],
    ['programma di studio', 'study plan'],
    ['orientamento', 'academic advising'],
    ['corso di laurea', 'degree course'],
  ]);

  packs.campus.byCategory["nl"] = buildEntries([
    ['universiteitsbibliotheek', 'university library'],
    ['werkgroep', 'tutorial group'],
    ['collegezaal', 'lecture hall'],
    ['studentenkaart', 'student card'],
    ['afstudeerscriptie', 'graduation thesis'],
    ['start academisch jaar', 'start of academic year'],
    ['dictaat', 'lecture notes'],
    ['studentenzaken', 'student affairs'],
    ['Erasmus', 'Erasmus exchange'],
    ['tutoraat', 'tutoring'],
    ['studentenhuis', 'student house'],
    ['deeltentamen', 'mid-term exam'],
    ['bachelor', 'bachelor\'s degree'],
    ['promotie', 'PhD defence'],
    ['practicum', 'lab practical'],
    ['studiebeurs', 'scholarship'],
    ['studieplan', 'study plan'],
    ['studieadviseur', 'academic advisor'],
    ['opleiding', 'degree programme'],
    ['campus', 'campus'],
  ]);

  packs.campus.byCategory["pt"] = buildEntries([
    ['seminário', 'seminar'],
    ['lição de casa', 'homework'],
    ['sala de aula', 'classroom'],
    ['professor', 'teacher'],
    ['colega de classe', 'classmate'],
    ['carteirinha de estudante', 'student ID'],
    ['república / moradia estudantil', 'student housing'],
    ['trabalho em grupo', 'group work'],
    ['horário de atendimento', 'office hours'],
    ['laboratório', 'lab'],
    ['dissertação de mestrado', 'master\'s thesis'],
    ['reprovar', 'to fail (an exam)'],
    ['estudante de intercâmbio', 'exchange student'],
    ['anotar', 'to take notes'],
    ['auditório', 'lecture hall'],
    ['disciplina', 'course'],
    ['matrícula', 'enrollment'],
    ['passar', 'to pass'],
    ['lista de leituras', 'reading list'],
    ['Pode repetir?', 'Could you repeat that?'],
  ]);

  packs.campus.byCategory["pl"] = buildEntries([
    ['seminarium', 'seminar'],
    ['praca domowa', 'homework'],
    ['klasa', 'classroom'],
    ['nauczyciel', 'teacher'],
    ['kolega z roku', 'classmate'],
    ['legitymacja studencka', 'student ID'],
    ['akademik', 'student housing'],
    ['praca grupowa', 'group work'],
    ['dyżur', 'office hours'],
    ['laboratorium', 'lab'],
    ['praca magisterska', 'master\'s thesis'],
    ['oblać', 'to fail (an exam)'],
    ['student wymiany', 'exchange student'],
    ['notować', 'to take notes'],
    ['aula', 'lecture hall'],
    ['przedmiot', 'course'],
    ['zapis', 'enrollment'],
    ['zdać', 'to pass'],
    ['lista lektur', 'reading list'],
    ['Czy może pan powtórzyć?', 'Could you repeat that?'],
  ]);

  packs.doctor.byCategory["nb-bokmal"] = buildEntries([
    ['resept', 'prescription'],
    ['medisin', 'medicine'],
    ['smerte', 'pain'],
    ['feber', 'fever'],
    ['hoste', 'cough'],
    ['forkjølelse', 'cold (illness)'],
    ['hodepine', 'headache'],
    ['magesmerter', 'stomachache'],
    ['allergi', 'allergy'],
    ['blodtrykk', 'blood pressure'],
    ['sykepleier', 'nurse'],
    ['ambulanse', 'ambulance'],
    ['vaksine', 'vaccine'],
    ['tannlege', 'dentist'],
    ['bandasje', 'bandage'],
    ['symptomer', 'symptoms'],
    ['akuttmottak', 'emergency room'],
    ['sykmelding', 'sick note'],
    ['legetime', 'doctor\'s appointment'],
    ['nødsituasjon', 'emergency'],
  ]);

  packs.doctor.byCategory["sv"] = buildEntries([
    ['recept', 'prescription'],
    ['medicin', 'medicine'],
    ['smärta', 'pain'],
    ['feber', 'fever'],
    ['hosta', 'cough'],
    ['förkylning', 'cold (illness)'],
    ['huvudvärk', 'headache'],
    ['magont', 'stomachache'],
    ['allergi', 'allergy'],
    ['blodtryck', 'blood pressure'],
    ['sjuksköterska', 'nurse'],
    ['ambulans', 'ambulance'],
    ['vaccin', 'vaccine'],
    ['tandläkare', 'dentist'],
    ['bandage', 'bandage'],
    ['symptom', 'symptoms'],
    ['akut', 'emergency room'],
    ['sjukintyg', 'sick note'],
    ['läkartid', 'doctor\'s appointment'],
    ['nödsituation', 'emergency'],
  ]);

  packs.doctor.byCategory["da"] = buildEntries([
    ['apoteker', 'pharmacist'],
    ['medicin', 'medicine'],
    ['smerte', 'pain'],
    ['termometer', 'thermometer'],
    ['halsbetændelse', 'sore throat'],
    ['forkølelse', 'cold (illness)'],
    ['migræne', 'migraine'],
    ['mavepine', 'stomachache'],
    ['allergisk', 'allergic'],
    ['hjertefrekvens', 'heart rate'],
    ['sygeplejerske', 'nurse'],
    ['akutlæge', 'emergency doctor'],
    ['vaccine', 'vaccine'],
    ['tandlæge', 'dentist'],
    ['forbinding', 'dressing / bandage'],
    ['symptomer', 'symptoms'],
    ['vagtlæge', 'on-call doctor'],
    ['sygeerklæring', 'sick note'],
    ['lægetid', 'doctor\'s appointment'],
    ['førstehjælp', 'first aid'],
  ]);

  packs.doctor.byCategory["de"] = buildEntries([
    ['Apotheker', 'pharmacist'],
    ['Medizin', 'medicine'],
    ['Schmerz', 'pain'],
    ['Fieberthermometer', 'thermometer'],
    ['Halsentzündung', 'sore throat'],
    ['Erkältung', 'cold (illness)'],
    ['Migräne', 'migraine'],
    ['Bauchschmerzen', 'stomachache'],
    ['allergisch', 'allergic'],
    ['Herzfrequenz', 'heart rate'],
    ['Krankenpfleger', 'nurse'],
    ['Notarzt', 'emergency doctor'],
    ['Impfpass', 'vaccination card'],
    ['Zahnarzt', 'dentist'],
    ['Wundverband', 'wound dressing'],
    ['Symptome', 'symptoms'],
    ['Bereitschaftsarzt', 'on-call doctor'],
    ['Arbeitsunfähigkeitsbescheinigung', 'sick note'],
    ['Arzttermin', 'doctor\'s appointment'],
    ['Erste Hilfe', 'first aid'],
  ]);

  packs.doctor.byCategory["fr"] = buildEntries([
    ['carte Vitale', 'health insurance card'],
    ['médecin traitant', 'family doctor'],
    ['pharmacie de garde', 'on-duty pharmacy'],
    ['rendez-vous', 'appointment'],
    ['ordonnance', 'prescription'],
    ['Sécurité Sociale', 'social security'],
    ['ticket modérateur', 'co-payment'],
    ['infirmier', 'nurse'],
    ['box de consultation', 'consultation booth'],
    ['spécialiste', 'specialist'],
    ['mutuelle', 'supplemental insurance'],
    ['vaccin', 'vaccine'],
    ['analyse de sang', 'blood test'],
    ['radiographie', 'X-ray'],
    ['cabinet médical', 'doctor\'s office'],
    ['service des urgences', 'emergency department'],
    ['dossier médical', 'medical file'],
    ['consultation', 'consultation'],
    ['antibiotique', 'antibiotic'],
    ['suivi médical', 'medical follow-up'],
  ]);

  packs.doctor.byCategory["es"] = buildEntries([
    ['receta', 'prescription'],
    ['farmacéutico', 'pharmacist'],
    ['analgésico', 'painkiller'],
    ['termómetro', 'thermometer'],
    ['tos', 'cough'],
    ['resfriado', 'cold (illness)'],
    ['dolor de cabeza', 'headache'],
    ['dolor de estómago', 'stomachache'],
    ['alergia', 'allergy'],
    ['presión arterial', 'blood pressure'],
    ['enfermero', 'nurse'],
    ['médico de urgencias', 'emergency doctor'],
    ['vacuna', 'vaccine'],
    ['dentista', 'dentist'],
    ['venda', 'bandage'],
    ['síntomas', 'symptoms'],
    ['urgencias', 'emergency room'],
    ['baja médica', 'sick note'],
    ['cita médica', 'doctor\'s appointment'],
    ['emergencia', 'emergency'],
  ]);

  packs.doctor.byCategory["it"] = buildEntries([
    ['tessera sanitaria', 'health insurance card'],
    ['medico di base', 'family doctor'],
    ['farmacia di turno', 'on-duty pharmacy'],
    ['appuntamento', 'appointment'],
    ['ricetta', 'prescription'],
    ['Servizio Sanitario Nazionale', 'national health service'],
    ['ticket', 'co-payment'],
    ['caposala', 'head nurse'],
    ['specialista', 'specialist'],
    ['mutua', 'health insurance'],
    ['vaccino', 'vaccine'],
    ['analisi del sangue', 'blood test'],
    ['radiografia', 'X-ray'],
    ['ambulatorio', 'clinic'],
    ['pronto soccorso', 'emergency room'],
    ['cartella clinica', 'medical record'],
    ['visita medica', 'medical examination'],
    ['antibiotico', 'antibiotic'],
    ['controllo periodico', 'check-up'],
    ['codice fiscale', 'tax code / fiscal code'],
  ]);

  packs.doctor.byCategory["nl"] = buildEntries([
    ['huisarts', 'family doctor'],
    ['apotheek van dienst', 'on-duty pharmacy'],
    ['spreekuur', 'surgery hours / consult'],
    ['medicijnvoorschrift', 'prescription'],
    ['basisverzekering', 'basic health insurance'],
    ['eigen risico', 'deductible'],
    ['zorgverlener', 'care provider'],
    ['specialist', 'specialist'],
    ['vaccinatie', 'vaccination'],
    ['bloedonderzoek', 'blood test'],
    ['röntgenfoto', 'X-ray'],
    ['spreekkamer', 'consultation room'],
    ['SEH', 'emergency department (SEH)'],
    ['medisch dossier', 'medical file'],
    ['controle', 'check-up'],
    ['antibioticum', 'antibiotic'],
    ['DigiD', 'DigiD digital ID'],
    ['zorgpas', 'health insurance card'],
    ['wachtkamer', 'waiting room'],
    ['verwijzing', 'referral'],
  ]);

  packs.doctor.byCategory["pt"] = buildEntries([
    ['receita', 'prescription'],
    ['remédio', 'medicine'],
    ['dor', 'pain'],
    ['febre', 'fever'],
    ['tosse', 'cough'],
    ['resfriado', 'cold (illness)'],
    ['dor de cabeça', 'headache'],
    ['dor de barriga', 'stomachache'],
    ['alergia', 'allergy'],
    ['pressão arterial', 'blood pressure'],
    ['enfermeiro', 'nurse'],
    ['ambulância', 'ambulance'],
    ['vacina', 'vaccine'],
    ['dentista', 'dentist'],
    ['atadura', 'bandage'],
    ['sintomas', 'symptoms'],
    ['pronto-socorro', 'emergency room'],
    ['atestado médico', 'sick note'],
    ['consulta médica', 'doctor\'s appointment'],
    ['emergência', 'emergency'],
  ]);

  packs.doctor.byCategory["pl"] = buildEntries([
    ['recepta', 'prescription'],
    ['lek', 'medicine'],
    ['ból', 'pain'],
    ['gorączka', 'fever'],
    ['kaszel', 'cough'],
    ['przeziębienie', 'cold (illness)'],
    ['ból głowy', 'headache'],
    ['ból brzucha', 'stomachache'],
    ['alergia', 'allergy'],
    ['ciśnienie', 'blood pressure'],
    ['pielęgniarka', 'nurse'],
    ['karetka', 'ambulance'],
    ['szczepionka', 'vaccine'],
    ['dentysta', 'dentist'],
    ['bandaż', 'bandage'],
    ['objawy', 'symptoms'],
    ['izba przyjęć', 'emergency room'],
    ['zwolnienie lekarskie', 'sick note'],
    ['wizyta u lekarza', 'doctor\'s appointment'],
    ['nagły wypadek', 'emergency'],
  ]);

  packs.housing.byCategory["nb-bokmal"] = buildEntries([
    ['leilighet', 'apartment'],
    ['husleie', 'rent'],
    ['utleier', 'landlord'],
    ['leietaker', 'tenant'],
    ['leiekontrakt', 'lease'],
    ['nøkler', 'keys'],
    ['møbler', 'furniture'],
    ['soverom', 'bedroom'],
    ['stue', 'living room'],
    ['balkong', 'balcony'],
    ['heis', 'elevator'],
    ['nabo', 'neighbor'],
    ['fellesutgifter', 'shared costs / utilities'],
    ['kollektiv', 'shared apartment'],
    ['vaskerom', 'laundry room'],
    ['postkasse', 'mailbox'],
    ['nabolag', 'neighborhood'],
    ['sikkerhetsdepositum', 'security deposit'],
    ['lekkasje', 'leak'],
    ['hotell', 'hotel'],
  ]);

  packs.housing.byCategory["sv"] = buildEntries([
    ['lägenhet', 'apartment'],
    ['hyra', 'rent'],
    ['hyresvärd', 'landlord'],
    ['hyresgäst', 'tenant'],
    ['hyreskontrakt', 'lease'],
    ['nycklar', 'keys'],
    ['möbler', 'furniture'],
    ['sovrum', 'bedroom'],
    ['vardagsrum', 'living room'],
    ['balkong', 'balcony'],
    ['hiss', 'elevator'],
    ['granne', 'neighbor'],
    ['avgifter', 'shared costs / utilities'],
    ['korridor', 'shared apartment'],
    ['tvättstuga', 'laundry room'],
    ['brevlåda', 'mailbox'],
    ['grannskap', 'neighborhood'],
    ['deposition', 'security deposit'],
    ['läcka', 'leak'],
    ['hotell', 'hotel'],
  ]);

  packs.housing.byCategory["da"] = buildEntries([
    ['etværelses', 'studio apartment'],
    ['a conto', 'utility advance payment'],
    ['boligselskab', 'housing association'],
    ['lejer', 'tenant'],
    ['lejekontrakt', 'lease'],
    ['nøgler', 'keys'],
    ['møbler', 'furniture'],
    ['soveværelse', 'bedroom'],
    ['stue', 'living room'],
    ['terrasse', 'terrace'],
    ['trappeopgang', 'stairwell'],
    ['nabo', 'neighbor'],
    ['fællesudgifter', 'shared costs / utilities'],
    ['bofællesskab', 'shared apartment'],
    ['vaskerum', 'laundry room'],
    ['dørtelefon', 'door intercom'],
    ['bydel', 'district'],
    ['huslejedepositum', 'rent deposit'],
    ['lækage', 'leak'],
    ['vandrerhjem', 'hostel'],
  ]);

  packs.housing.byCategory["de"] = buildEntries([
    ['Einzimmerwohnung', 'studio apartment'],
    ['Nebenkostenvorauszahlung', 'utility advance payment'],
    ['Wohnungsbaugesellschaft', 'housing association'],
    ['Mieter', 'tenant'],
    ['Mietvertrag', 'lease'],
    ['Gegensprechanlage', 'door intercom'],
    ['Möbel', 'furniture'],
    ['Schlafzimmer', 'bedroom'],
    ['Wohnzimmer', 'living room'],
    ['Dachterrasse', 'roof terrace'],
    ['Treppenhaus', 'stairwell'],
    ['Nachbar', 'neighbor'],
    ['Nebenkosten', 'shared costs / utilities'],
    ['WG', 'shared apartment'],
    ['Hausordnung', 'house rules'],
    ['Türklingel', 'doorbell'],
    ['Stadtteil', 'district'],
    ['Mietkaution', 'rent deposit'],
    ['Leck', 'leak'],
    ['Jugendherberge', 'youth hostel'],
  ]);

  packs.housing.byCategory["fr"] = buildEntries([
    ['loyer', 'rent'],
    ['bail', 'lease'],
    ['appartement meublé', 'furnished apartment'],
    ['syndic', 'building manager'],
    ['caution', 'security deposit'],
    ['diagnostic DPE', 'energy performance certificate'],
    ['colocation', 'shared apartment'],
    ['déménagement', 'moving house'],
    ['gardien', 'building concierge'],
    ['assurance habitation', 'home insurance'],
    ['compteur électrique', 'electricity meter'],
    ['studio', 'studio apartment'],
    ['quartier résidentiel', 'residential neighborhood'],
    ['pressing', 'dry cleaner'],
    ['poubelle', 'trash bin'],
    ['voisin', 'neighbor'],
    ['rez-de-chaussée', 'ground floor'],
    ['ascenseur', 'elevator'],
    ['bailleur', 'landlord'],
    ['quittance de loyer', 'rent receipt'],
  ]);

  packs.housing.byCategory["es"] = buildEntries([
    ['piso de un dormitorio', 'one-bedroom flat'],
    ['alquiler', 'rent'],
    ['casero', 'landlord'],
    ['inquilino', 'tenant'],
    ['contrato de alquiler', 'lease'],
    ['llaves', 'keys'],
    ['muebles', 'furniture'],
    ['dormitorio', 'bedroom'],
    ['salón', 'living room'],
    ['balcón', 'balcony'],
    ['ascensor', 'elevator'],
    ['vecino', 'neighbor'],
    ['gastos comunes', 'shared costs / utilities'],
    ['piso compartido', 'shared apartment'],
    ['lavadero', 'laundry room'],
    ['buzón', 'mailbox'],
    ['distrito', 'district'],
    ['fianza', 'security deposit'],
    ['fuga', 'leak'],
    ['albergue', 'hostel'],
  ]);

  packs.housing.byCategory["it"] = buildEntries([
    ['affitto', 'rent'],
    ['contratto di locazione', 'lease agreement'],
    ['appartamento arredato', 'furnished apartment'],
    ['amministratore di condominio', 'building administrator'],
    ['cauzione', 'security deposit'],
    ['certificato energetico', 'energy performance certificate'],
    ['condivisione', 'shared housing'],
    ['trasloco', 'moving house'],
    ['portiere', 'concierge'],
    ['assicurazione casa', 'home insurance'],
    ['contatore elettrico', 'electricity meter'],
    ['monolocale', 'studio apartment'],
    ['quartiere residenziale', 'residential neighbourhood'],
    ['lavanderia', 'laundry'],
    ['bidone', 'rubbish bin'],
    ['vicino di casa', 'neighbour'],
    ['piano terra', 'ground floor'],
    ['citofono', 'door intercom'],
    ['locatore', 'landlord'],
    ['ricevuta affitto', 'rent receipt'],
  ]);

  packs.housing.byCategory["nl"] = buildEntries([
    ['huurprijs', 'rent price'],
    ['huurcontract', 'rental contract'],
    ['gemeubileerd appartement', 'furnished apartment'],
    ['VvE', 'owners\' association'],
    ['borg', 'security deposit'],
    ['energielabel', 'energy label'],
    ['kamer delen', 'shared room'],
    ['verhuizen', 'moving house'],
    ['portier', 'doorman'],
    ['inboedelverzekering', 'contents insurance'],
    ['elektriciteitsmeter', 'electricity meter'],
    ['studio', 'studio apartment'],
    ['woonwijk', 'residential neighbourhood'],
    ['wasserette', 'launderette'],
    ['kliko', 'wheelie bin'],
    ['buur', 'neighbour'],
    ['begane grond', 'ground floor'],
    ['trappenhuis', 'stairwell'],
    ['verhuurder', 'landlord'],
    ['huurbewijs', 'rent receipt'],
  ]);

  packs.housing.byCategory["pt"] = buildEntries([
    ['apartamento', 'apartment'],
    ['aluguel', 'rent'],
    ['locador', 'landlord'],
    ['inquilino', 'tenant'],
    ['contrato de aluguel', 'lease'],
    ['chaves', 'keys'],
    ['móveis', 'furniture'],
    ['quarto', 'bedroom'],
    ['sala', 'living room'],
    ['varanda', 'balcony'],
    ['elevador', 'elevator'],
    ['vizinho', 'neighbor'],
    ['condomínio', 'shared costs / utilities'],
    ['república', 'shared apartment'],
    ['lavanderia', 'laundry room'],
    ['caixa de correio', 'mailbox'],
    ['bairro', 'neighborhood'],
    ['caução', 'security deposit'],
    ['vazamento', 'leak'],
    ['hotel', 'hotel'],
  ]);

  packs.housing.byCategory["pl"] = buildEntries([
    ['mieszkanie', 'apartment'],
    ['czynsz', 'rent'],
    ['wynajmujący', 'landlord'],
    ['najemca', 'tenant'],
    ['umowa najmu', 'lease'],
    ['klucze', 'keys'],
    ['meble', 'furniture'],
    ['sypialnia', 'bedroom'],
    ['salon', 'living room'],
    ['balkon', 'balcony'],
    ['winda', 'elevator'],
    ['sąsiad', 'neighbor'],
    ['opłaty', 'shared costs / utilities'],
    ['wspólne mieszkanie', 'shared apartment'],
    ['pralnia', 'laundry room'],
    ['skrzynka na listy', 'mailbox'],
    ['okolica', 'neighborhood'],
    ['kaucja', 'security deposit'],
    ['przeciek', 'leak'],
    ['hotel', 'hotel'],
  ]);

  packs.work.byCategory["nb-bokmal"] = buildEntries([
    ['kontor', 'office'],
    ['sjef', 'boss'],
    ['prosjekt', 'project'],
    ['fulltid', 'full-time'],
    ['deltid', 'part-time'],
    ['hjemmekontor', 'remote work'],
    ['jobbintervju', 'job interview'],
    ['lønn', 'salary'],
    ['overtid', 'overtime'],
    ['faktura', 'invoice'],
    ['kunde', 'customer / client'],
    ['passord', 'password'],
    ['forretningsreise', 'business trip'],
    ['agenda', 'agenda'],
    ['innleveringsfrist', 'deadline'],
    ['medarbeider', 'coworker'],
    ['møterom', 'meeting room'],
    ['ansettelse', 'employment'],
    ['oppsigelse', 'resignation / notice'],
    ['team', 'team'],
  ]);

  packs.work.byCategory["sv"] = buildEntries([
    ['kontor', 'office'],
    ['chef', 'boss'],
    ['projekt', 'project'],
    ['heltid', 'full-time'],
    ['deltid', 'part-time'],
    ['hemarbete', 'remote work'],
    ['jobbintervju', 'job interview'],
    ['lön', 'salary'],
    ['övertid', 'overtime'],
    ['faktura', 'invoice'],
    ['kund', 'customer / client'],
    ['lösenord', 'password'],
    ['affärsresa', 'business trip'],
    ['dagordning', 'agenda'],
    ['deadline', 'deadline'],
    ['medarbetare', 'coworker'],
    ['mötesrum', 'meeting room'],
    ['anställning', 'employment'],
    ['uppsägning', 'resignation / notice'],
    ['team', 'team'],
  ]);

  packs.work.byCategory["da"] = buildEntries([
    ['kontor', 'office'],
    ['leder', 'manager'],
    ['projekt', 'project'],
    ['fuldtid', 'full-time'],
    ['deltid', 'part-time'],
    ['hjemmearbejde', 'remote work'],
    ['jobansøgning', 'job application'],
    ['løn', 'salary'],
    ['overarbejde', 'overtime'],
    ['ordrebekræftelse', 'order confirmation'],
    ['kunde', 'customer / client'],
    ['brugernavn', 'username'],
    ['forretningsrejse', 'business trip'],
    ['dagsorden', 'agenda'],
    ['deadline', 'deadline'],
    ['medarbejder', 'coworker'],
    ['mødelokale', 'meeting room'],
    ['ansættelse', 'employment'],
    ['opsigelse', 'resignation / notice'],
    ['team', 'team'],
  ]);

  packs.work.byCategory["de"] = buildEntries([
    ['Büro', 'office'],
    ['Chef', 'boss'],
    ['Projekt', 'project'],
    ['Vollzeit', 'full-time'],
    ['Teilzeit', 'part-time'],
    ['Homeoffice', 'remote work'],
    ['Bewerbung', 'job application'],
    ['Gehalt', 'salary'],
    ['Überstunden', 'overtime'],
    ['Auftragsbestätigung', 'order confirmation'],
    ['Kunde', 'customer / client'],
    ['Benutzername', 'username'],
    ['Dienstreise', 'business trip'],
    ['Tagesordnung', 'agenda'],
    ['Frist', 'deadline'],
    ['Mitarbeiter', 'coworker'],
    ['Besprechungsraum', 'meeting room'],
    ['Anstellung', 'employment'],
    ['Kündigung', 'resignation / notice'],
    ['Team', 'team'],
  ]);

  packs.work.byCategory["fr"] = buildEntries([
    ['CDI', 'permanent contract'],
    ['CDD', 'fixed-term contract'],
    ['pause déjeuner', 'lunch break'],
    ['télétravail', 'remote work'],
    ['convention collective', 'collective agreement'],
    ['bulletin de salaire', 'payslip'],
    ['comité d\'entreprise', 'works council'],
    ['RTT', 'compensatory time off (RTT)'],
    ['chef de service', 'department head'],
    ['formation continue', 'continuing education'],
    ['SMIC', 'minimum wage'],
    ['35 heures', '35-hour workweek'],
    ['entretien annuel', 'annual review'],
    ['chômage', 'unemployment'],
    ['coéquipier', 'teammate'],
    ['cantine d\'entreprise', 'company cafeteria'],
    ['open space', 'open-plan office'],
    ['prime', 'bonus'],
    ['syndicat', 'trade union'],
    ['bilan de compétences', 'skills assessment'],
  ]);

  packs.work.byCategory["es"] = buildEntries([
    ['periodo de prueba', 'probation period'],
    ['superior', 'manager / superior'],
    ['confirmación de pedido', 'order confirmation'],
    ['jornada completa', 'full-time'],
    ['media jornada', 'part-time'],
    ['teletrabajo', 'remote work'],
    ['entrevista de trabajo', 'job interview'],
    ['sueldo', 'salary'],
    ['horas extra', 'overtime'],
    ['factura', 'invoice'],
    ['nombre de usuario', 'username'],
    ['contraseña', 'password'],
    ['viaje de negocios', 'business trip'],
    ['orden del día', 'agenda'],
    ['fecha límite', 'deadline'],
    ['compañero de trabajo', 'coworker'],
    ['sala de reuniones', 'meeting room'],
    ['solicitud de empleo', 'job application'],
    ['dimisión', 'resignation / notice'],
    ['entrevista laboral', 'job interview'],
  ]);

  packs.work.byCategory["it"] = buildEntries([
    ['contratto a tempo indeterminato', 'permanent contract'],
    ['contratto a termine', 'fixed-term contract'],
    ['pausa pranzo', 'lunch break'],
    ['smart working', 'remote work'],
    ['contratto collettivo', 'collective agreement'],
    ['busta paga', 'payslip'],
    ['rappresentanza sindacale', 'union representation'],
    ['ferie', 'paid leave'],
    ['capo ufficio', 'office manager'],
    ['formazione continua', 'continuing training'],
    ['salario minimo', 'minimum wage'],
    ['valutazione annuale', 'annual review'],
    ['disoccupazione', 'unemployment'],
    ['collaboratore', 'coworker / collaborator'],
    ['mensa aziendale', 'company canteen'],
    ['open space', 'open-plan office'],
    ['premio', 'bonus'],
    ['sindacato', 'trade union'],
    ['bilancio di competenze', 'skills assessment'],
    ['orario di lavoro', 'working hours'],
  ]);

  packs.work.byCategory["nl"] = buildEntries([
    ['vast contract', 'permanent contract'],
    ['tijdelijk contract', 'temporary contract'],
    ['lunchpauze', 'lunch break'],
    ['thuiswerken', 'working from home'],
    ['CAO', 'collective labour agreement'],
    ['loonstrook', 'payslip'],
    ['ondernemingsraad', 'works council'],
    ['vakantiedagen', 'holiday days'],
    ['afdelingshoofd', 'department head'],
    ['bijscholing', 'further training'],
    ['minimumloon', 'minimum wage'],
    ['functioneringsgesprek', 'performance review'],
    ['werkloosheid', 'unemployment'],
    ['teamgenoot', 'teammate'],
    ['bedrijfskantine', 'company canteen'],
    ['open kantoor', 'open-plan office'],
    ['bonus', 'bonus'],
    ['vakbond', 'trade union'],
    ['competentieprofiel', 'competency profile'],
    ['rooster', 'work roster'],
  ]);

  packs.work.byCategory["pt"] = buildEntries([
    ['escritório', 'office'],
    ['chefe', 'boss'],
    ['projeto', 'project'],
    ['tempo integral', 'full-time'],
    ['meio período', 'part-time'],
    ['home office', 'remote work'],
    ['entrevista de emprego', 'job interview'],
    ['salário', 'salary'],
    ['hora extra', 'overtime'],
    ['nota fiscal', 'invoice'],
    ['cliente', 'customer / client'],
    ['senha', 'password'],
    ['viagem de negócios', 'business trip'],
    ['pauta', 'agenda'],
    ['prazo', 'deadline'],
    ['colega de trabalho', 'coworker'],
    ['sala de reunião', 'meeting room'],
    ['contratação', 'employment'],
    ['demissão', 'resignation / notice'],
    ['equipe', 'team'],
  ]);

  packs.work.byCategory["pl"] = buildEntries([
    ['biuro', 'office'],
    ['szef', 'boss'],
    ['projekt', 'project'],
    ['pełny etat', 'full-time'],
    ['pół etatu', 'part-time'],
    ['praca zdalna', 'remote work'],
    ['rozmowa o pracę', 'job interview'],
    ['pensja', 'salary'],
    ['nadgodziny', 'overtime'],
    ['faktura', 'invoice'],
    ['klient', 'customer / client'],
    ['hasło', 'password'],
    ['podróż służbowa', 'business trip'],
    ['porządek obrad', 'agenda'],
    ['termin', 'deadline'],
    ['współpracownik', 'coworker'],
    ['sala konferencyjna', 'meeting room'],
    ['zatrudnienie', 'employment'],
    ['wypowiedzenie', 'resignation / notice'],
    ['zespół', 'team'],
  ]);

  packs.shopping.byCategory["nb-bokmal"] = buildEntries([
    ['matbutikk', 'supermarket'],
    ['billig', 'cheap'],
    ['salg', 'sale'],
    ['vekslepenger', 'change (money)'],
    ['handlepose', 'shopping bag'],
    ['handlevogn', 'shopping cart'],
    ['kasse', 'checkout / register'],
    ['størrelse', 'size'],
    ['grønnsaker', 'vegetables'],
    ['kylling', 'chicken'],
    ['prøverom', 'fitting room'],
    ['refusjon', 'refund'],
    ['gave', 'gift'],
    ['åpningstider', 'opening hours'],
    ['for stor', 'too big'],
    ['for liten', 'too small'],
    ['å betale', 'to pay'],
    ['farge', 'color'],
    ['tilbud', 'discount'],
    ['å bytte', 'to exchange / return'],
  ]);

  packs.shopping.byCategory["sv"] = buildEntries([
    ['matbutik', 'supermarket'],
    ['billig', 'cheap'],
    ['rea', 'sale'],
    ['växel', 'change (money)'],
    ['kasse', 'shopping bag'],
    ['kundvagn', 'shopping cart'],
    ['kassa', 'checkout / register'],
    ['storlek', 'size'],
    ['grönsaker', 'vegetables'],
    ['kyckling', 'chicken'],
    ['provrum', 'fitting room'],
    ['återbetalning', 'refund'],
    ['present', 'gift'],
    ['öppettider', 'opening hours'],
    ['för stor', 'too big'],
    ['för liten', 'too small'],
    ['att betala', 'to pay'],
    ['färg', 'color'],
    ['erbjudande', 'discount'],
    ['att byta', 'to exchange / return'],
  ]);

  packs.shopping.byCategory["da"] = buildEntries([
    ['discountbutik', 'discount store'],
    ['billig', 'cheap'],
    ['nedsat', 'reduced (on sale)'],
    ['mønter', 'coins'],
    ['pose', 'shopping bag'],
    ['indkøbsvogn', 'shopping cart'],
    ['kasseapparat', 'cash register'],
    ['størrelse', 'size'],
    ['grøntsager', 'vegetables'],
    ['kylling', 'chicken'],
    ['prøverum', 'fitting room'],
    ['reklamationsret', 'right to return / complain'],
    ['gavekort', 'gift card'],
    ['lukketid', 'closing time'],
    ['for stor', 'too big'],
    ['for lille', 'too small'],
    ['at betale', 'to pay'],
    ['farve', 'color'],
    ['prisnedsættelse', 'price reduction'],
    ['at bytte', 'to exchange / return'],
  ]);

  packs.shopping.byCategory["de"] = buildEntries([
    ['Discounter', 'discount supermarket'],
    ['billig', 'cheap'],
    ['reduziert', 'reduced (on sale)'],
    ['Münzen', 'coins'],
    ['Tragetasche', 'shopping bag'],
    ['Einkaufswagen', 'shopping cart'],
    ['Registrierkasse', 'cash register'],
    ['Größe', 'size'],
    ['Gemüse', 'vegetables'],
    ['Hähnchen', 'chicken'],
    ['Umkleidekabine', 'fitting room'],
    ['Reklamationsrecht', 'right to return / complain'],
    ['Geschenk', 'gift'],
    ['Schließungszeit', 'closing time'],
    ['zu groß', 'too big'],
    ['zu klein', 'too small'],
    ['Kartenzahlung', 'card payment'],
    ['Farbe', 'color'],
    ['Angebot', 'discount'],
    ['umtauschen', 'to exchange / return'],
  ]);

  packs.shopping.byCategory["fr"] = buildEntries([
    ['code-barres', 'barcode'],
    ['caisse', 'checkout'],
    ['soldes', 'sales'],
    ['panier', 'shopping basket'],
    ['chariot', 'shopping cart'],
    ['carte de fidélité', 'loyalty card'],
    ['rayon', 'aisle / section'],
    ['supermarché', 'supermarket'],
    ['courses', 'grocery shopping'],
    ['marché bio', 'organic market'],
    ['boulangerie', 'bakery'],
    ['ticket de caisse', 'receipt'],
    ['promotion', 'promotion'],
    ['self-service', 'self-service'],
    ['surgelés', 'frozen foods'],
    ['parapharmacie', 'drugstore section'],
    ['drive', 'click-and-collect'],
    ['étiquettes', 'price tags'],
    ['sac réutilisable', 'reusable bag'],
    ['grande surface', 'hypermarket'],
  ]);

  packs.shopping.byCategory["es"] = buildEntries([
    ['supermercado', 'supermarket'],
    ['barato', 'cheap'],
    ['rebajas', 'sale'],
    ['cambio', 'change (money)'],
    ['bolsa', 'shopping bag'],
    ['carrito', 'shopping cart'],
    ['caja', 'checkout / register'],
    ['talla', 'size'],
    ['verduras', 'vegetables'],
    ['tienda de descuento', 'discount store'],
    ['probador', 'fitting room'],
    ['reembolso', 'refund'],
    ['tarjeta regalo', 'gift card'],
    ['horario de apertura', 'opening hours'],
    ['demasiado grande', 'too big'],
    ['demasiado pequeño', 'too small'],
    ['pago con tarjeta', 'card payment'],
    ['hora de cierre', 'closing time'],
    ['bajada de precio', 'price reduction'],
    ['derecho de devolución', 'right of return'],
  ]);

  packs.shopping.byCategory["it"] = buildEntries([
    ['codice a barre', 'barcode'],
    ['cassa', 'checkout'],
    ['saldi', 'sales'],
    ['carrello', 'shopping trolley'],
    ['carta fedeltà', 'loyalty card'],
    ['reparto', 'department / aisle'],
    ['supermercato', 'supermarket'],
    ['spesa', 'grocery shopping'],
    ['mercato biologico', 'organic market'],
    ['panetteria', 'bakery'],
    ['scontrino fiscale', 'fiscal receipt'],
    ['promozione', 'promotion'],
    ['self service', 'self-service'],
    ['surgelati', 'frozen foods'],
    ['parafarmacia', 'drugstore section'],
    ['click and collect', 'click and collect'],
    ['etichette', 'price tags'],
    ['borsa riutilizzabile', 'reusable bag'],
    ['ipermercato', 'hypermarket'],
    ['sconto', 'discount'],
  ]);

  packs.shopping.byCategory["nl"] = buildEntries([
    ['streepjescode', 'barcode'],
    ['kassa', 'checkout'],
    ['uitverkoop', 'sale'],
    ['winkelwagen', 'shopping trolley'],
    ['klantenkaart', 'loyalty card'],
    ['afdeling', 'department'],
    ['supermarkt', 'supermarket'],
    ['boodschappen', 'groceries'],
    ['biologische markt', 'organic market'],
    ['bakkerij', 'bakery'],
    ['kassabon', 'receipt'],
    ['aanbieding', 'special offer'],
    ['zelfbediening', 'self-service'],
    ['diepvries', 'frozen foods'],
    ['drogisterij', 'drugstore'],
    ['click and collect', 'click and collect'],
    ['prijskaartje', 'price tag'],
    ['herbruikbare tas', 'reusable bag'],
    ['hypermarkt', 'hypermarket'],
    ['korting', 'discount'],
  ]);

  packs.shopping.byCategory["pt"] = buildEntries([
    ['supermercado', 'supermarket'],
    ['barato', 'cheap'],
    ['liquidação', 'sale'],
    ['troco', 'change (money)'],
    ['sacola', 'shopping bag'],
    ['carrinho', 'shopping cart'],
    ['caixa', 'checkout / register'],
    ['tamanho', 'size'],
    ['legumes', 'vegetables'],
    ['frango', 'chicken'],
    ['provador', 'fitting room'],
    ['reembolso', 'refund'],
    ['presente', 'gift'],
    ['horário de funcionamento', 'opening hours'],
    ['grande demais', 'too big'],
    ['pequeno demais', 'too small'],
    ['pagar', 'to pay'],
    ['cor', 'color'],
    ['oferta', 'discount'],
    ['trocar', 'to exchange / return'],
  ]);

  packs.shopping.byCategory["pl"] = buildEntries([
    ['supermarket', 'supermarket'],
    ['tani', 'cheap'],
    ['wyprzedaż', 'sale'],
    ['reszta', 'change (money)'],
    ['torba', 'shopping bag'],
    ['wózek', 'shopping cart'],
    ['kasa', 'checkout / register'],
    ['rozmiar', 'size'],
    ['warzywa', 'vegetables'],
    ['kurczak', 'chicken'],
    ['przymierzalnia', 'fitting room'],
    ['zwrot pieniędzy', 'refund'],
    ['prezent', 'gift'],
    ['godziny otwarcia', 'opening hours'],
    ['za duży', 'too big'],
    ['za mały', 'too small'],
    ['płacić', 'to pay'],
    ['kolor', 'color'],
    ['oferta', 'discount'],
    ['zwrócić / wymienić', 'to exchange / return'],
  ]);

  packs.social.byCategory["nb-bokmal"] = buildEntries([
    ['fest', 'party'],
    ['helg', 'weekend'],
    ['hobby', 'hobby'],
    ['å invitere', 'to invite'],
    ['å besøke', 'to visit'],
    ['Skål!', 'Cheers!'],
    ['Hyggelig å se deg', 'Good to see you'],
    ['Vi ses snart', 'See you soon'],
    ['Ta vare på deg', 'Take care'],
    ['Gratulerer med dagen!', 'Happy birthday!'],
    ['Jeg savner deg', 'I miss you'],
    ['Er du ledig?', 'Are you free?'],
    ['invitasjon', 'invitation'],
    ['bursdag', 'birthday'],
    ['å henge', 'to hang out'],
    ['planene', 'the plans'],
    ['kjempehyggelig', 'really nice'],
    ['å holde kontakten', 'to stay in touch'],
    ['kamerat', 'buddy / mate'],
    ['date', 'date (meetup)'],
  ]);

  packs.social.byCategory["sv"] = buildEntries([
    ['fest', 'party'],
    ['helg', 'weekend'],
    ['hobby', 'hobby'],
    ['att bjuda', 'to invite'],
    ['att besöka', 'to visit'],
    ['Skål!', 'Cheers!'],
    ['Kul att ses', 'Good to see you'],
    ['Vi ses snart', 'See you soon'],
    ['Ta hand om dig', 'Take care'],
    ['Grattis på födelsedagen!', 'Happy birthday!'],
    ['Jag saknar dig', 'I miss you'],
    ['Är du ledig?', 'Are you free?'],
    ['inbjudan', 'invitation'],
    ['födelsedag', 'birthday'],
    ['att hänga', 'to hang out'],
    ['planerna', 'the plans'],
    ['jättetrevligt', 'really nice'],
    ['att hålla kontakten', 'to stay in touch'],
    ['kompis', 'buddy / mate'],
    ['dejt', 'date (meetup)'],
  ]);

  packs.social.byCategory["da"] = buildEntries([
    ['fest', 'party'],
    ['weekend', 'weekend'],
    ['hobby', 'hobby'],
    ['at invitere', 'to invite'],
    ['at besøge', 'to visit'],
    ['Skål!', 'Cheers!'],
    ['Dejligt at se dig', 'Good to see you'],
    ['Vi ses snart', 'See you soon'],
    ['Pas på dig selv', 'Take care'],
    ['Tillykke med fødselsdagen!', 'Happy birthday!'],
    ['Jeg savner dig', 'I miss you'],
    ['Er du ledig?', 'Are you free?'],
    ['indbydelse', 'invitation'],
    ['jubilæum', 'anniversary / jubilee'],
    ['at hænge ud', 'to hang out'],
    ['planerne', 'the plans'],
    ['mega hyggeligt', 'really nice'],
    ['at holde kontakten', 'to stay in touch'],
    ['kammerat', 'buddy / mate'],
    ['date', 'date (meetup)'],
  ]);

  packs.social.byCategory["de"] = buildEntries([
    ['Party', 'party'],
    ['Wochenende', 'weekend'],
    ['Hobby', 'hobby'],
    ['einladen', 'to invite'],
    ['besuchen', 'to visit'],
    ['Prost!', 'Cheers!'],
    ['Schön dich zu sehen', 'Good to see you'],
    ['Wir sehen uns', 'See you (soon)'],
    ['Pass auf dich auf', 'Take care'],
    ['Alles Gute zum Geburtstag!', 'Happy birthday!'],
    ['Ich vermisse dich', 'I miss you'],
    ['Hast du Zeit?', 'Are you free?'],
    ['Einladung', 'invitation'],
    ['Geburtstag', 'birthday'],
    ['abhängen', 'to hang out'],
    ['die Pläne', 'the plans'],
    ['super nett', 'really nice'],
    ['in Kontakt bleiben', 'to stay in touch'],
    ['Kumpel', 'buddy / mate'],
    ['Date', 'date (meetup)'],
  ]);

  packs.social.byCategory["fr"] = buildEntries([
    ['copain', 'friend (casual)'],
    ['soirée', 'evening get-together'],
    ['bisou', 'cheek kiss'],
    ['repas de famille', 'family meal'],
    ['apéro', 'aperitif drinks'],
    ['voisinage', 'neighborhood community'],
    ['pot entre amis', 'drinks with friends'],
    ['pot de départ', 'farewell drink'],
    ['retrouvailles', 'reunion'],
    ['cercle d\'amis', 'circle of friends'],
    ['bavardage', 'chat / small talk'],
    ['parrain', 'godfather / mentor'],
    ['marraine', 'godmother'],
    ['mariage civil', 'civil wedding'],
    ['fête d\'anniversaire', 'birthday party'],
    ['café entre amis', 'coffee with friends'],
    ['discussion', 'discussion'],
    ['groupe WhatsApp', 'WhatsApp group'],
    ['poignée de main', 'handshake'],
    ['week-end en famille', 'family weekend'],
  ]);

  packs.social.byCategory["es"] = buildEntries([
    ['aniversario', 'anniversary'],
    ['fin de semana', 'weekend'],
    ['pasatiempo', 'hobby'],
    ['invitar', 'to invite'],
    ['visitar', 'to visit'],
    ['¡Salud!', 'Cheers!'],
    ['Encantado de verte', 'Good to see you'],
    ['Nos vemos pronto', 'See you soon'],
    ['Cuídate mucho', 'Take good care'],
    ['¡Feliz cumpleaños!', 'Happy birthday!'],
    ['Te echo de menos', 'I miss you'],
    ['¿Estás libre?', 'Are you free?'],
    ['invitación', 'invitation'],
    ['invitación formal', 'formal invitation'],
    ['pasar el rato', 'to hang out'],
    ['los planes', 'the plans'],
    ['muy agradable', 'really nice'],
    ['mantener el contacto', 'to stay in touch'],
    ['Estamos en contacto', 'We'll stay in touch'],
    ['cita', 'date (meetup)'],
  ]);

  packs.social.byCategory["it"] = buildEntries([
    ['serata', 'evening out'],
    ['bacio sulla guancia', 'kiss on the cheek'],
    ['pranzo di famiglia', 'family lunch'],
    ['apericena', 'aperitif + light meal'],
    ['vicinato', 'neighbourhood community'],
    ['festa privata', 'private party'],
    ['brindisi di addio', 'farewell toast'],
    ['ritrovo', 'get-together'],
    ['cerchia di amici', 'circle of friends'],
    ['conversazione', 'conversation'],
    ['padrino', 'godfather'],
    ['madrina', 'godmother'],
    ['matrimonio civile', 'civil wedding'],
    ['festa di compleanno', 'birthday party'],
    ['caffè con amici', 'coffee with friends'],
    ['discussione', 'discussion'],
    ['gruppo WhatsApp', 'WhatsApp group'],
    ['stretta di mano', 'handshake'],
    ['weekend in famiglia', 'family weekend'],
    ['amici di lunga data', 'long-time friends'],
  ]);

  packs.social.byCategory["nl"] = buildEntries([
    ['avondje uit', 'night out'],
    ['kus op de wang', 'kiss on the cheek'],
    ['familiediner', 'family dinner'],
    ['vrijmibo', 'Friday afternoon drinks'],
    ['buurt', 'neighbourhood community'],
    ['feest', 'party'],
    ['afscheidsborrel', 'farewell drinks'],
    ['reünie', 'reunion'],
    ['vriendengroep', 'group of friends'],
    ['gesprek', 'conversation'],
    ['peetoom', 'godfather'],
    ['peettante', 'godmother'],
    ['burgerlijk huwelijk', 'civil wedding'],
    ['verjaardag', 'birthday'],
    ['koffie met vrienden', 'coffee with friends'],
    ['discussie', 'discussion'],
    ['WhatsApp-groep', 'WhatsApp group'],
    ['handdruk', 'handshake'],
    ['weekend met familie', 'family weekend'],
    ['oude vrienden', 'old friends'],
  ]);

  packs.social.byCategory["pt"] = buildEntries([
    ['festa', 'party'],
    ['fim de semana', 'weekend'],
    ['hobby', 'hobby'],
    ['convidar', 'to invite'],
    ['visitar', 'to visit'],
    ['Saúde!', 'Cheers!'],
    ['Que bom te ver', 'Good to see you'],
    ['Até logo', 'See you soon'],
    ['Se cuida', 'Take care'],
    ['Feliz aniversário!', 'Happy birthday!'],
    ['Sinto sua falta', 'I miss you'],
    ['Você está livre?', 'Are you free?'],
    ['convite', 'invitation'],
    ['aniversário', 'birthday'],
    ['sair juntos', 'to hang out'],
    ['os planos', 'the plans'],
    ['muito legal', 'really nice'],
    ['manter contato', 'to stay in touch'],
    ['amigo', 'buddy / mate'],
    ['encontro', 'date (meetup)'],
  ]);

  packs.social.byCategory["pl"] = buildEntries([
    ['impreza', 'party'],
    ['weekend', 'weekend'],
    ['hobby', 'hobby'],
    ['zapraszać', 'to invite'],
    ['odwiedzać', 'to visit'],
    ['Na zdrowie!', 'Cheers!'],
    ['Miło cię widzieć', 'Good to see you'],
    ['Do zobaczenia wkrótce', 'See you soon'],
    ['Trzymaj się', 'Take care'],
    ['Wszystkiego najlepszego!', 'Happy birthday!'],
    ['Tęsknię za tobą', 'I miss you'],
    ['Jesteś wolny?', 'Are you free?'],
    ['zaproszenie', 'invitation'],
    ['urodziny', 'birthday'],
    ['spędzać czas', 'to hang out'],
    ['plany', 'the plans'],
    ['super miło', 'really nice'],
    ['utrzymywać kontakt', 'to stay in touch'],
    ['kumpel', 'buddy / mate'],
    ['randka', 'date (meetup)'],
  ]);

  packs.money.byCategory["nb-bokmal"] = buildEntries([
    ['minibank', 'ATM'],
    ['kredittkort', 'credit card'],
    ['debetkort', 'debit card'],
    ['beløp', 'amount'],
    ['å veksle', 'to exchange (money)'],
    ['gebyr', 'fee'],
    ['budsjett', 'budget'],
    ['lån', 'loan'],
    ['avdrag', 'installment'],
    ['å overføre', 'to transfer'],
    ['innskudd', 'deposit'],
    ['uttak', 'withdrawal'],
    ['kontantløs', 'cashless'],
    ['saldo', 'balance'],
    ['konto', 'account'],
    ['rente', 'interest'],
    ['valuta', 'currency'],
    ['vekslingskontor', 'currency exchange'],
    ['lønnsslipp', 'payslip'],
    ['å ta ut penger', 'to withdraw cash'],
  ]);

  packs.money.byCategory["sv"] = buildEntries([
    ['bankomat', 'ATM'],
    ['kreditkort', 'credit card'],
    ['betalkort', 'debit card'],
    ['belopp', 'amount'],
    ['att växla', 'to exchange (money)'],
    ['avgift', 'fee'],
    ['budget', 'budget'],
    ['lån', 'loan'],
    ['avbetalning', 'installment'],
    ['att överföra', 'to transfer'],
    ['insättning', 'deposit'],
    ['uttag', 'withdrawal'],
    ['kontantlös', 'cashless'],
    ['saldo', 'balance'],
    ['konto', 'account'],
    ['ränta', 'interest'],
    ['valuta', 'currency'],
    ['växlingskontor', 'currency exchange'],
    ['lönespecifikation', 'payslip'],
    ['att ta ut pengar', 'to withdraw cash'],
  ]);

  packs.money.byCategory["da"] = buildEntries([
    ['netbank', 'online banking'],
    ['dankort', 'Danish payment card'],
    ['MobilePay', 'MobilePay'],
    ['beløb', 'amount'],
    ['at veksle', 'to exchange (money)'],
    ['administrationsgebyr', 'admin fee'],
    ['budget', 'budget'],
    ['lån', 'loan'],
    ['afdrag', 'installment'],
    ['at overføre', 'to transfer'],
    ['indskud', 'deposit'],
    ['hævning', 'withdrawal'],
    ['kontantløs', 'cashless'],
    ['saldo', 'balance'],
    ['konto', 'account'],
    ['rente', 'interest'],
    ['valuta', 'currency'],
    ['vekselkontor', 'currency exchange'],
    ['lønseddel', 'payslip'],
    ['at hæve penge', 'to withdraw cash'],
  ]);

  packs.money.byCategory["de"] = buildEntries([
    ['Online-Banking', 'online banking'],
    ['Girokarte', 'debit / bank card'],
    ['Debitkarte', 'debit card'],
    ['Betrag', 'amount'],
    ['wechseln', 'to exchange (money)'],
    ['Verwaltungsgebühr', 'admin fee'],
    ['Budget', 'budget'],
    ['Kredit', 'loan'],
    ['Rate', 'installment'],
    ['überweisen', 'to transfer'],
    ['Einzahlung', 'deposit'],
    ['Abhebung', 'withdrawal'],
    ['bargeldlos', 'cashless'],
    ['Kontostand', 'balance'],
    ['Konto', 'account'],
    ['Zinsen', 'interest'],
    ['Währung', 'currency'],
    ['Wechselstube', 'currency exchange'],
    ['Gehaltsabrechnung', 'payslip'],
    ['Geld abheben', 'to withdraw cash'],
  ]);

  packs.money.byCategory["fr"] = buildEntries([
    ['RIB', 'bank account details (RIB)'],
    ['virement', 'bank transfer'],
    ['chéquier', 'checkbook'],
    ['découvert', 'overdraft'],
    ['code PIN', 'PIN code'],
    ['guichet automatique', 'ATM'],
    ['compte courant', 'checking account'],
    ['carte bleue', 'debit card'],
    ['prélèvement automatique', 'direct debit'],
    ['livret A', 'Livret A savings account'],
    ['frais bancaires', 'bank fees'],
    ['relevé de compte', 'bank statement'],
    ['IBAN', 'IBAN'],
    ['crédit immobilier', 'mortgage'],
    ['banque en ligne', 'online banking'],
    ['dépôt', 'deposit'],
    ['solde', 'balance'],
    ['conseiller financier', 'financial advisor'],
    ['retrait', 'withdrawal'],
    ['taux d\'intérêt', 'interest rate'],
  ]);

  packs.money.byCategory["es"] = buildEntries([
    ['cajero', 'ATM'],
    ['tarjeta de crédito', 'credit card'],
    ['tarjeta de débito', 'debit card'],
    ['importe', 'amount'],
    ['cambiar divisas', 'to exchange currency'],
    ['comisión', 'fee'],
    ['presupuesto', 'budget'],
    ['préstamo', 'loan'],
    ['cuota', 'installment'],
    ['transferir', 'to transfer'],
    ['ingreso', 'deposit'],
    ['retirada', 'withdrawal'],
    ['sin efectivo', 'cashless'],
    ['saldo', 'balance'],
    ['cuenta corriente', 'checking account'],
    ['interés', 'interest'],
    ['divisa', 'currency'],
    ['casa de cambio', 'currency exchange'],
    ['nómina', 'payslip'],
    ['sacar dinero', 'to withdraw cash'],
  ]);

  packs.money.byCategory["it"] = buildEntries([
    ['IBAN', 'IBAN'],
    ['bonifico', 'bank transfer'],
    ['libretto di assegni', 'chequebook'],
    ['scoperto', 'overdraft'],
    ['codice PIN', 'PIN code'],
    ['bancomat', 'ATM'],
    ['conto corrente', 'current account'],
    ['carta di debito', 'debit card'],
    ['addebito automatico', 'direct debit'],
    ['conto deposito', 'deposit account'],
    ['spese bancarie', 'bank fees'],
    ['estratto conto', 'bank statement'],
    ['mutuo', 'mortgage'],
    ['banca online', 'online banking'],
    ['deposito', 'deposit'],
    ['saldo', 'balance'],
    ['consulente finanziario', 'financial advisor'],
    ['prelievo', 'withdrawal'],
    ['tasso di interesse', 'interest rate'],
    ['carta di credito', 'credit card'],
  ]);

  packs.money.byCategory["nl"] = buildEntries([
    ['IBAN', 'IBAN'],
    ['overschrijving', 'bank transfer'],
    ['chequeboek', 'chequebook'],
    ['rood staan', 'overdraft'],
    ['pincode', 'PIN code'],
    ['pinautomaat', 'ATM'],
    ['betaalrekening', 'current account'],
    ['pinpas', 'debit card'],
    ['automatische incasso', 'direct debit'],
    ['spaarrekening', 'savings account'],
    ['bankkosten', 'bank fees'],
    ['rekeningafschrift', 'bank statement'],
    ['hypotheekrente', 'mortgage interest'],
    ['internetbankieren', 'online banking'],
    ['storting', 'deposit'],
    ['saldo', 'balance'],
    ['financieel adviseur', 'financial advisor'],
    ['opname', 'withdrawal'],
    ['rente', 'interest rate'],
    ['creditcard', 'credit card'],
  ]);

  packs.money.byCategory["pt"] = buildEntries([
    ['caixa eletrônico', 'ATM'],
    ['cartão de crédito', 'credit card'],
    ['cartão de débito', 'debit card'],
    ['valor', 'amount'],
    ['cambiar', 'to exchange (money)'],
    ['taxa', 'fee'],
    ['orçamento', 'budget'],
    ['empréstimo', 'loan'],
    ['parcela', 'installment'],
    ['transferir', 'to transfer'],
    ['depósito', 'deposit'],
    ['saque', 'withdrawal'],
    ['sem dinheiro', 'cashless'],
    ['saldo', 'balance'],
    ['conta', 'account'],
    ['juros', 'interest'],
    ['moeda', 'currency'],
    ['casa de câmbio', 'currency exchange'],
    ['holerite', 'payslip'],
    ['sacar dinheiro', 'to withdraw cash'],
  ]);

  packs.money.byCategory["pl"] = buildEntries([
    ['bankomat', 'ATM'],
    ['karta kredytowa', 'credit card'],
    ['karta debetowa', 'debit card'],
    ['kwota', 'amount'],
    ['wymieniać', 'to exchange (money)'],
    ['opłata', 'fee'],
    ['budżet', 'budget'],
    ['pożyczka', 'loan'],
    ['rata', 'installment'],
    ['przelewać', 'to transfer'],
    ['wpłata', 'deposit'],
    ['wypłata', 'withdrawal'],
    ['bezgotówkowy', 'cashless'],
    ['saldo', 'balance'],
    ['konto', 'account'],
    ['odsetki', 'interest'],
    ['waluta', 'currency'],
    ['kantor', 'currency exchange'],
    ['pasek wypłaty', 'payslip'],
    ['wypłacać pieniądze', 'to withdraw cash'],
  ]);

  root.THEMATIC_PACKS = packs;
  root.THEMATIC_PACK_LIST = Object.values(packs);
})(typeof window !== "undefined" ? window : globalThis);
