/**
 * Thematic mini-packs — opt-in extras, not part of the frequency starter.
 * Enable from Library → Themes. Cards merge by unique foreign form.
 * Ranks start at 1001 so day-one hook mix stays on the core deck;
 * enabled packs get a small daily intro bias after the early phase.
 */
(function (root) {
  const packs = {
    airport: {
      id: "airport",
      title: "Airport & travel",
      blurb: "Gates, bags, delays, and asking for help.",
      byCategory: {},
    },
    cafe: {
      id: "cafe",
      title: "Café & dining",
      blurb: "Ordering food, the bill, and allergies.",
      byCategory: {},
    },
    campus: {
      id: "campus",
      title: "Campus & studies",
      blurb: "Classes, exams, library, and student life.",
      byCategory: {},
    },
    doctor: {
      id: "doctor",
      title: "Doctor & health",
      blurb: "Symptoms, pharmacy, and asking for care.",
      byCategory: {},
    },
    housing: {
      id: "housing",
      title: "Housing",
      blurb: "Rent, viewings, neighbors, and repairs.",
      byCategory: {},
    },
  };

  function buildEntries(forms) {
    return forms.map(([foreign, native]) => {
      const f = String(foreign || "").trim();
      const isPhrase = /\s|[?!…]/.test(f);
      return {
        foreign: f,
        native: String(native || "").trim(),
        category: isPhrase ? "phrase" : (String(native).startsWith("to ") ? "verb" : "noun"),
        band: isPhrase ? "phrase" : "C",
      };
    });
  }

  packs.airport.byCategory["nb-bokmal"] = buildEntries([
    ['flyplass', 'airport'],
    ['fly', 'flight'],
    ['boardingkort', 'boarding pass'],
    ['pass', 'passport'],
    ['koffert', 'suitcase'],
    ['bagasje', 'luggage'],
    ['gate', 'gate'],
    ['avgang', 'departure'],
    ['ankomst', 'arrival'],
    ['innsjekking', 'check-in'],
    ['sikkerhetskontroll', 'security'],
    ['toll', 'customs'],
    ['bagasjebånd', 'baggage claim'],
    ['forsinket', 'delayed'],
    ['kansellert', 'cancelled'],
    ['i rute', 'on time'],
    ['billett', 'ticket'],
    ['sete', 'seat'],
    ['vindusplass', 'window seat'],
    ['midtgangsplass', 'aisle seat'],
    ['ombordstigning', 'boarding'],
    ['å ta av', 'to take off'],
    ['å lande', 'to land'],
    ['Hvor er gaten?', 'Where is the gate?'],
    ['Jeg har en reservasjon', 'I have a reservation'],
    ['enveisbillett', 'one-way ticket'],
    ['tur-retur', 'return ticket'],
    ['Kofferten min er borte', 'My suitcase is missing'],
    ['Hvor mye koster det?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['kabinansatt', 'flight attendant'],
    ['hattehylle', 'overhead bin'],
    ['håndbagasje', 'hand luggage'],
    ['taxi', 'taxi'],
    ['buss', 'bus'],
    ['tog', 'train'],
    ['hotell', 'hotel'],
    ['Jeg trenger hjelp', 'I need help'],
    ['Finnes det wifi?', 'Is there Wi-Fi?'],
    ['utgang', 'exit'],
    ['inngang', 'entrance'],
    ['Snakker du engelsk?', 'Do you speak English?'],
    ['Jeg forstår ikke', 'I don\'t understand'],
    ['Snakk saktere, er du snill', 'Please speak more slowly'],
    ['Hvor er toalettet?', 'Where is the bathroom?'],
    ['hittegods', 'lost and found'],
    ['bytte', 'transfer'],
    ['korrespondanse', 'connection'],
    ['ombordstigningstid', 'boarding time'],
    ['passkontroll', 'passport control'],
  ]);

  packs.airport.byCategory["sv"] = buildEntries([
    ['flygplats', 'airport'],
    ['flyg', 'flight'],
    ['boardingkort', 'boarding pass'],
    ['pass', 'passport'],
    ['resväska', 'suitcase'],
    ['bagage', 'luggage'],
    ['gate', 'gate'],
    ['avgång', 'departure'],
    ['ankomst', 'arrival'],
    ['incheckning', 'check-in'],
    ['säkerhetskontroll', 'security'],
    ['tull', 'customs'],
    ['bagageband', 'baggage claim'],
    ['försenad', 'delayed'],
    ['inställd', 'cancelled'],
    ['i tid', 'on time'],
    ['biljett', 'ticket'],
    ['säte', 'seat'],
    ['fönsterplats', 'window seat'],
    ['gångplats', 'aisle seat'],
    ['ombordstigning', 'boarding'],
    ['att lyfta', 'to take off'],
    ['att landa', 'to land'],
    ['Var är gaten?', 'Where is the gate?'],
    ['Jag har en reservation', 'I have a reservation'],
    ['enkel biljett', 'one-way ticket'],
    ['tur och retur', 'return ticket'],
    ['Min resväska är borta', 'My suitcase is missing'],
    ['Hur mycket kostar det?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['kabinpersonal', 'flight attendant'],
    ['hatthylla', 'overhead bin'],
    ['handbagage', 'hand luggage'],
    ['taxi', 'taxi'],
    ['buss', 'bus'],
    ['tåg', 'train'],
    ['hotell', 'hotel'],
    ['Jag behöver hjälp', 'I need help'],
    ['Finns det wifi?', 'Is there Wi-Fi?'],
    ['utgång', 'exit'],
    ['ingång', 'entrance'],
    ['Talar du engelska?', 'Do you speak English?'],
    ['Jag förstår inte', 'I don\'t understand'],
    ['Kan du tala långsammare?', 'Please speak more slowly'],
    ['Var är toaletten?', 'Where is the bathroom?'],
    ['hittegods', 'lost and found'],
    ['byte', 'transfer'],
    ['anslutning', 'connection'],
    ['ombordstigningstid', 'boarding time'],
    ['passkontroll', 'passport control'],
  ]);

  packs.airport.byCategory["da"] = buildEntries([
    ['lufthavn', 'airport'],
    ['fly', 'flight'],
    ['boardingkort', 'boarding pass'],
    ['pas', 'passport'],
    ['kuffert', 'suitcase'],
    ['bagage', 'luggage'],
    ['gate', 'gate'],
    ['afgang', 'departure'],
    ['ankomst', 'arrival'],
    ['check-in', 'check-in'],
    ['sikkerhedskontrol', 'security'],
    ['told', 'customs'],
    ['bagagebånd', 'baggage claim'],
    ['forsinket', 'delayed'],
    ['aflyst', 'cancelled'],
    ['til tiden', 'on time'],
    ['billet', 'ticket'],
    ['sæde', 'seat'],
    ['vinduesplads', 'window seat'],
    ['midtergangsplads', 'aisle seat'],
    ['boarding', 'boarding'],
    ['at lette', 'to take off'],
    ['at lande', 'to land'],
    ['Hvor er gaten?', 'Where is the gate?'],
    ['Jeg har en reservation', 'I have a reservation'],
    ['enkeltbillet', 'one-way ticket'],
    ['tur-retur', 'return ticket'],
    ['Min kuffert er væk', 'My suitcase is missing'],
    ['Hvor meget koster det?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['kabinepersonale', 'flight attendant'],
    ['hattehylde', 'overhead bin'],
    ['håndbagage', 'hand luggage'],
    ['taxa', 'taxi'],
    ['bus', 'bus'],
    ['tog', 'train'],
    ['hotel', 'hotel'],
    ['Jeg har brug for hjælp', 'I need help'],
    ['Er der wifi?', 'Is there Wi-Fi?'],
    ['udgang', 'exit'],
    ['indgang', 'entrance'],
    ['Taler du engelsk?', 'Do you speak English?'],
    ['Jeg forstår ikke', 'I don\'t understand'],
    ['Tal langsommere, tak', 'Please speak more slowly'],
    ['Hvor er toilettet?', 'Where is the bathroom?'],
    ['hittegods', 'lost and found'],
    ['skift', 'transfer'],
    ['forbindelse', 'connection'],
    ['boardingtid', 'boarding time'],
    ['paskontrol', 'passport control'],
  ]);

  packs.airport.byCategory["de"] = buildEntries([
    ['Flughafen', 'airport'],
    ['Flug', 'flight'],
    ['Bordkarte', 'boarding pass'],
    ['Reisepass', 'passport'],
    ['Koffer', 'suitcase'],
    ['Gepäck', 'luggage'],
    ['Gate', 'gate'],
    ['Abflug', 'departure'],
    ['Ankunft', 'arrival'],
    ['Check-in', 'check-in'],
    ['Sicherheitskontrolle', 'security'],
    ['Zoll', 'customs'],
    ['Gepäckausgabe', 'baggage claim'],
    ['verspätet', 'delayed'],
    ['gestrichen', 'cancelled'],
    ['pünktlich', 'on time'],
    ['Ticket', 'ticket'],
    ['Sitzplatz', 'seat'],
    ['Fensterplatz', 'window seat'],
    ['Gangplatz', 'aisle seat'],
    ['Boarding', 'boarding'],
    ['abheben', 'to take off'],
    ['landen', 'to land'],
    ['Wo ist das Gate?', 'Where is the gate?'],
    ['Ich habe eine Reservierung', 'I have a reservation'],
    ['einfache Fahrkarte', 'one-way ticket'],
    ['Hin- und Rückfahrt', 'return ticket'],
    ['Mein Koffer ist weg', 'My suitcase is missing'],
    ['Was kostet das?', 'How much does it cost?'],
    ['Terminal', 'terminal'],
    ['Flugbegleiter', 'flight attendant'],
    ['Gepäckfach', 'overhead bin'],
    ['Handgepäck', 'hand luggage'],
    ['Taxi', 'taxi'],
    ['Bus', 'bus'],
    ['Zug', 'train'],
    ['Hotel', 'hotel'],
    ['Ich brauche Hilfe', 'I need help'],
    ['Gibt es WLAN?', 'Is there Wi-Fi?'],
    ['Ausgang', 'exit'],
    ['Eingang', 'entrance'],
    ['Sprechen Sie Englisch?', 'Do you speak English?'],
    ['Ich verstehe nicht', 'I don\'t understand'],
    ['Sprechen Sie bitte langsamer', 'Please speak more slowly'],
    ['Wo ist die Toilette?', 'Where is the bathroom?'],
    ['Fundbüro', 'lost and found'],
    ['Umstieg', 'transfer'],
    ['Anschluss', 'connection'],
    ['Boardingzeit', 'boarding time'],
    ['Passkontrolle', 'passport control'],
  ]);

  packs.airport.byCategory["fr"] = buildEntries([
    ['aéroport', 'airport'],
    ['vol', 'flight'],
    ['carte d\'embarquement', 'boarding pass'],
    ['passeport', 'passport'],
    ['valise', 'suitcase'],
    ['bagages', 'luggage'],
    ['porte d\'embarquement', 'gate'],
    ['départ', 'departure'],
    ['arrivée', 'arrival'],
    ['enregistrement', 'check-in'],
    ['contrôle de sécurité', 'security'],
    ['douane', 'customs'],
    ['livraison des bagages', 'baggage claim'],
    ['retardé', 'delayed'],
    ['annulé', 'cancelled'],
    ['à l\'heure', 'on time'],
    ['billet', 'ticket'],
    ['siège', 'seat'],
    ['place côté fenêtre', 'window seat'],
    ['place côté couloir', 'aisle seat'],
    ['embarquement', 'boarding'],
    ['décoller', 'to take off'],
    ['atterrir', 'to land'],
    ['Où est la porte d\'embarquement ?', 'Where is the gate?'],
    ['J\'ai une réservation', 'I have a reservation'],
    ['aller simple', 'one-way ticket'],
    ['aller-retour', 'return ticket'],
    ['Ma valise a disparu', 'My suitcase is missing'],
    ['Combien ça coûte ?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['agent de bord', 'flight attendant'],
    ['coffre à bagages', 'overhead bin'],
    ['bagage à main', 'hand luggage'],
    ['taxi', 'taxi'],
    ['bus', 'bus'],
    ['train', 'train'],
    ['hôtel', 'hotel'],
    ['J\'ai besoin d\'aide', 'I need help'],
    ['Y a-t-il du Wi-Fi ?', 'Is there Wi-Fi?'],
    ['sortie', 'exit'],
    ['entrée', 'entrance'],
    ['Parlez-vous anglais ?', 'Do you speak English?'],
    ['Je ne comprends pas', 'I don\'t understand'],
    ['Parlez plus lentement, s\'il vous plaît', 'Please speak more slowly'],
    ['Où sont les toilettes ?', 'Where is the bathroom?'],
    ['objets trouvés', 'lost and found'],
    ['correspondance', 'transfer'],
    ['connexion', 'connection'],
    ['heure d\'embarquement', 'boarding time'],
    ['contrôle des passeports', 'passport control'],
  ]);

  packs.airport.byCategory["es"] = buildEntries([
    ['aeropuerto', 'airport'],
    ['vuelo', 'flight'],
    ['tarjeta de embarque', 'boarding pass'],
    ['pasaporte', 'passport'],
    ['maleta', 'suitcase'],
    ['equipaje', 'luggage'],
    ['puerta de embarque', 'gate'],
    ['salida', 'departure'],
    ['llegada', 'arrival'],
    ['facturación', 'check-in'],
    ['control de seguridad', 'security'],
    ['aduana', 'customs'],
    ['recogida de equipajes', 'baggage claim'],
    ['retrasado', 'delayed'],
    ['cancelado', 'cancelled'],
    ['a tiempo', 'on time'],
    ['billete', 'ticket'],
    ['asiento', 'seat'],
    ['asiento de ventanilla', 'window seat'],
    ['asiento de pasillo', 'aisle seat'],
    ['embarque', 'boarding'],
    ['despegar', 'to take off'],
    ['aterrizar', 'to land'],
    ['¿Dónde está la puerta?', 'Where is the gate?'],
    ['Tengo una reserva', 'I have a reservation'],
    ['billete de ida', 'one-way ticket'],
    ['ida y vuelta', 'return ticket'],
    ['Falta mi maleta', 'My suitcase is missing'],
    ['¿Cuánto cuesta?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['auxiliar de vuelo', 'flight attendant'],
    ['compartimento superior', 'overhead bin'],
    ['equipaje de mano', 'hand luggage'],
    ['taxi', 'taxi'],
    ['autobús', 'bus'],
    ['tren', 'train'],
    ['hotel', 'hotel'],
    ['Necesito ayuda', 'I need help'],
    ['¿Hay wifi?', 'Is there Wi-Fi?'],
    ['salida del edificio', 'exit'],
    ['entrada', 'entrance'],
    ['¿Habla inglés?', 'Do you speak English?'],
    ['No entiendo', 'I don\'t understand'],
    ['Hable más despacio, por favor', 'Please speak more slowly'],
    ['¿Dónde está el baño?', 'Where is the bathroom?'],
    ['objetos perdidos', 'lost and found'],
    ['transbordo', 'transfer'],
    ['conexión', 'connection'],
    ['hora de embarque', 'boarding time'],
    ['control de pasaportes', 'passport control'],
  ]);

  packs.airport.byCategory["it"] = buildEntries([
    ['aeroporto', 'airport'],
    ['volo', 'flight'],
    ['carta d\'imbarco', 'boarding pass'],
    ['passaporto', 'passport'],
    ['valigia', 'suitcase'],
    ['bagaglio', 'luggage'],
    ['gate', 'gate'],
    ['partenza', 'departure'],
    ['arrivo', 'arrival'],
    ['check-in', 'check-in'],
    ['controlli di sicurezza', 'security'],
    ['dogana', 'customs'],
    ['ritiro bagagli', 'baggage claim'],
    ['in ritardo', 'delayed'],
    ['cancellato', 'cancelled'],
    ['in orario', 'on time'],
    ['biglietto', 'ticket'],
    ['posto', 'seat'],
    ['posto finestrino', 'window seat'],
    ['posto corridoio', 'aisle seat'],
    ['imbarco', 'boarding'],
    ['decollare', 'to take off'],
    ['atterrare', 'to land'],
    ['Dov\'è il gate?', 'Where is the gate?'],
    ['Ho una prenotazione', 'I have a reservation'],
    ['andata', 'one-way ticket'],
    ['andata e ritorno', 'return ticket'],
    ['Manca la mia valigia', 'My suitcase is missing'],
    ['Quanto costa?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['assistente di volo', 'flight attendant'],
    ['vano bagagli', 'overhead bin'],
    ['bagaglio a mano', 'hand luggage'],
    ['taxi', 'taxi'],
    ['autobus', 'bus'],
    ['treno', 'train'],
    ['hotel', 'hotel'],
    ['Ho bisogno di aiuto', 'I need help'],
    ['C\'è il Wi-Fi?', 'Is there Wi-Fi?'],
    ['uscita', 'exit'],
    ['entrata', 'entrance'],
    ['Parla inglese?', 'Do you speak English?'],
    ['Non capisco', 'I don\'t understand'],
    ['Parli più lentamente, per favore', 'Please speak more slowly'],
    ['Dov\'è il bagno?', 'Where is the bathroom?'],
    ['oggetti smarriti', 'lost and found'],
    ['coincidenza', 'transfer'],
    ['collegamento', 'connection'],
    ['ora d\'imbarco', 'boarding time'],
    ['controllo passaporti', 'passport control'],
  ]);

  packs.airport.byCategory["nl"] = buildEntries([
    ['luchthaven', 'airport'],
    ['vlucht', 'flight'],
    ['boardingpass', 'boarding pass'],
    ['paspoort', 'passport'],
    ['koffer', 'suitcase'],
    ['bagage', 'luggage'],
    ['gate', 'gate'],
    ['vertrek', 'departure'],
    ['aankomst', 'arrival'],
    ['inchecken', 'check-in'],
    ['veiligheidscontrole', 'security'],
    ['douane', 'customs'],
    ['bagageband', 'baggage claim'],
    ['vertraagd', 'delayed'],
    ['geannuleerd', 'cancelled'],
    ['op tijd', 'on time'],
    ['kaartje', 'ticket'],
    ['stoel', 'seat'],
    ['raamstoel', 'window seat'],
    ['gangpadstoel', 'aisle seat'],
    ['boarding', 'boarding'],
    ['opstijgen', 'to take off'],
    ['landen', 'to land'],
    ['Waar is de gate?', 'Where is the gate?'],
    ['Ik heb een reservering', 'I have a reservation'],
    ['enkele reis', 'one-way ticket'],
    ['retourtje', 'return ticket'],
    ['Mijn koffer is zoek', 'My suitcase is missing'],
    ['Hoeveel kost het?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['stewardess', 'flight attendant'],
    ['bagagevak', 'overhead bin'],
    ['handbagage', 'hand luggage'],
    ['taxi', 'taxi'],
    ['bus', 'bus'],
    ['trein', 'train'],
    ['hotel', 'hotel'],
    ['Ik heb hulp nodig', 'I need help'],
    ['Is er wifi?', 'Is there Wi-Fi?'],
    ['uitgang', 'exit'],
    ['ingang', 'entrance'],
    ['Spreekt u Engels?', 'Do you speak English?'],
    ['Ik begrijp het niet', 'I don\'t understand'],
    ['Kunt u langzamer praten?', 'Please speak more slowly'],
    ['Waar is het toilet?', 'Where is the bathroom?'],
    ['gevonden voorwerpen', 'lost and found'],
    ['overstap', 'transfer'],
    ['aansluiting', 'connection'],
    ['boardingtijd', 'boarding time'],
    ['paspoortcontrole', 'passport control'],
  ]);

  packs.airport.byCategory["pt"] = buildEntries([
    ['aeroporto', 'airport'],
    ['voo', 'flight'],
    ['cartão de embarque', 'boarding pass'],
    ['passaporte', 'passport'],
    ['mala', 'suitcase'],
    ['bagagem', 'luggage'],
    ['portão', 'gate'],
    ['partida', 'departure'],
    ['chegada', 'arrival'],
    ['check-in', 'check-in'],
    ['segurança', 'security'],
    ['alfândega', 'customs'],
    ['esteira de bagagem', 'baggage claim'],
    ['atrasado', 'delayed'],
    ['cancelado', 'cancelled'],
    ['no horário', 'on time'],
    ['passagem', 'ticket'],
    ['assento', 'seat'],
    ['janela', 'window seat'],
    ['corredor', 'aisle seat'],
    ['embarque', 'boarding'],
    ['decolar', 'to take off'],
    ['pousar', 'to land'],
    ['Onde fica o portão?', 'Where is the gate?'],
    ['Tenho uma reserva', 'I have a reservation'],
    ['só ida', 'one-way ticket'],
    ['ida e volta', 'return ticket'],
    ['Minha mala sumiu', 'My suitcase is missing'],
    ['Quanto custa?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['comissário de bordo', 'flight attendant'],
    ['compartimento superior', 'overhead bin'],
    ['bagagem de mão', 'hand luggage'],
    ['táxi', 'taxi'],
    ['ônibus', 'bus'],
    ['trem', 'train'],
    ['hotel', 'hotel'],
    ['Preciso de ajuda', 'I need help'],
    ['Tem wi-fi?', 'Is there Wi-Fi?'],
    ['saída', 'exit'],
    ['entrada', 'entrance'],
    ['Você fala inglês?', 'Do you speak English?'],
    ['Não entendo', 'I don\'t understand'],
    ['Fale mais devagar, por favor', 'Please speak more slowly'],
    ['Onde fica o banheiro?', 'Where is the bathroom?'],
    ['achados e perdidos', 'lost and found'],
    ['conexão', 'transfer'],
    ['ligação', 'connection'],
    ['horário de embarque', 'boarding time'],
    ['controle de passaporte', 'passport control'],
  ]);

  packs.airport.byCategory["pl"] = buildEntries([
    ['lotnisko', 'airport'],
    ['lot', 'flight'],
    ['karta pokładowa', 'boarding pass'],
    ['paszport', 'passport'],
    ['walizka', 'suitcase'],
    ['bagaż', 'luggage'],
    ['bramka', 'gate'],
    ['odlot', 'departure'],
    ['przylot', 'arrival'],
    ['odprawa', 'check-in'],
    ['kontrola bezpieczeństwa', 'security'],
    ['cło', 'customs'],
    ['odbiór bagażu', 'baggage claim'],
    ['opóźniony', 'delayed'],
    ['odwołany', 'cancelled'],
    ['na czas', 'on time'],
    ['bilet', 'ticket'],
    ['miejsce', 'seat'],
    ['miejsce przy oknie', 'window seat'],
    ['miejsce przy przejściu', 'aisle seat'],
    ['boarding', 'boarding'],
    ['startować', 'to take off'],
    ['lądować', 'to land'],
    ['Gdzie jest bramka?', 'Where is the gate?'],
    ['Mam rezerwację', 'I have a reservation'],
    ['bilet w jedną stronę', 'one-way ticket'],
    ['bilet w obie strony', 'return ticket'],
    ['Zginęła moja walizka', 'My suitcase is missing'],
    ['Ile to kosztuje?', 'How much does it cost?'],
    ['terminal', 'terminal'],
    ['stewardesa', 'flight attendant'],
    ['półka na bagaż', 'overhead bin'],
    ['bagaż podręczny', 'hand luggage'],
    ['taksi', 'taxi'],
    ['autobus', 'bus'],
    ['pociąg', 'train'],
    ['hotel', 'hotel'],
    ['Potrzebuję pomocy', 'I need help'],
    ['Czy jest wi-fi?', 'Is there Wi-Fi?'],
    ['wyjście', 'exit'],
    ['wejście', 'entrance'],
    ['Czy mówi pan po angielsku?', 'Do you speak English?'],
    ['Nie rozumiem', 'I don\'t understand'],
    ['Proszę mówić wolniej', 'Please speak more slowly'],
    ['Gdzie jest toaleta?', 'Where is the bathroom?'],
    ['biuro rzeczy znalezionych', 'lost and found'],
    ['przesiadka', 'transfer'],
    ['połączenie', 'connection'],
    ['godzina boardingu', 'boarding time'],
    ['kontrola paszportowa', 'passport control'],
  ]);

  packs.cafe.byCategory["nb-bokmal"] = buildEntries([
    ['kafe', 'café'],
    ['restaurant', 'restaurant'],
    ['meny', 'menu'],
    ['kelner', 'waiter'],
    ['regning', 'bill / check'],
    ['tips', 'tip'],
    ['bord', 'table'],
    ['vann', 'water'],
    ['kaffe', 'coffee'],
    ['te', 'tea'],
    ['øl', 'beer'],
    ['vin', 'wine'],
    ['brød', 'bread'],
    ['ost', 'cheese'],
    ['kjøtt', 'meat'],
    ['fisk', 'fish'],
    ['vegetarisk', 'vegetarian'],
    ['Jeg er allergisk mot…', 'I am allergic to…'],
    ['Et bord til to, takk', 'A table for two, please'],
    ['Menyen, takk', 'The menu, please'],
    ['Jeg vil gjerne ha…', 'I would like…'],
    ['Hva anbefaler du?', 'What do you recommend?'],
    ['Er dette sterkt?', 'Is this spicy?'],
    ['Uten melk', 'Without milk'],
    ['Med sukker', 'With sugar'],
    ['Regningen, takk', 'The bill, please'],
    ['Kan jeg betale med kort?', 'Can I pay by card?'],
    ['kontanter', 'cash'],
    ['kvittering', 'receipt'],
    ['frokost', 'breakfast'],
    ['lunsj', 'lunch'],
    ['middag', 'dinner'],
    ['veldig godt', 'delicious'],
    ['Jeg er mett', 'I am full'],
    ['En kaffe til, takk', 'Another coffee, please'],
    ['takeaway', 'takeaway'],
    ['å bestille', 'to order'],
    ['reservasjon', 'reservation'],
    ['åpen', 'open'],
    ['stengt', 'closed'],
  ]);

  packs.cafe.byCategory["sv"] = buildEntries([
    ['kafé', 'café'],
    ['restaurang', 'restaurant'],
    ['meny', 'menu'],
    ['kypare', 'waiter'],
    ['nota', 'bill / check'],
    ['dricks', 'tip'],
    ['bord', 'table'],
    ['vatten', 'water'],
    ['kaffe', 'coffee'],
    ['te', 'tea'],
    ['öl', 'beer'],
    ['vin', 'wine'],
    ['bröd', 'bread'],
    ['ost', 'cheese'],
    ['kött', 'meat'],
    ['fisk', 'fish'],
    ['vegetarisk', 'vegetarian'],
    ['Jag är allergisk mot…', 'I am allergic to…'],
    ['Ett bord för två, tack', 'A table for two, please'],
    ['Menyn, tack', 'The menu, please'],
    ['Jag skulle vilja ha…', 'I would like…'],
    ['Vad rekommenderar du?', 'What do you recommend?'],
    ['Är det starkt?', 'Is this spicy?'],
    ['Utan mjölk', 'Without milk'],
    ['Med socker', 'With sugar'],
    ['Notan, tack', 'The bill, please'],
    ['Kan jag betala med kort?', 'Can I pay by card?'],
    ['kontanter', 'cash'],
    ['kvitto', 'receipt'],
    ['frukost', 'breakfast'],
    ['lunch', 'lunch'],
    ['middag', 'dinner'],
    ['jättegott', 'delicious'],
    ['Jag är mätt', 'I am full'],
    ['En kaffe till, tack', 'Another coffee, please'],
    ['takeaway', 'takeaway'],
    ['att beställa', 'to order'],
    ['bokning', 'reservation'],
    ['öppen', 'open'],
    ['stängd', 'closed'],
  ]);

  packs.cafe.byCategory["da"] = buildEntries([
    ['café', 'café'],
    ['restaurant', 'restaurant'],
    ['menu', 'menu'],
    ['tjener', 'waiter'],
    ['regning', 'bill / check'],
    ['drikkepenge', 'tip'],
    ['bord', 'table'],
    ['vand', 'water'],
    ['kaffe', 'coffee'],
    ['te', 'tea'],
    ['øl', 'beer'],
    ['vin', 'wine'],
    ['brød', 'bread'],
    ['ost', 'cheese'],
    ['kød', 'meat'],
    ['fisk', 'fish'],
    ['vegetarisk', 'vegetarian'],
    ['Jeg er allergisk over for…', 'I am allergic to…'],
    ['Et bord til to, tak', 'A table for two, please'],
    ['Menuet, tak', 'The menu, please'],
    ['Jeg vil gerne have…', 'I would like…'],
    ['Hvad anbefaler du?', 'What do you recommend?'],
    ['Er det stærkt?', 'Is this spicy?'],
    ['Uden mælk', 'Without milk'],
    ['Med sukker', 'With sugar'],
    ['Regningen, tak', 'The bill, please'],
    ['Kan jeg betale med kort?', 'Can I pay by card?'],
    ['kontanter', 'cash'],
    ['kvittering', 'receipt'],
    ['morgenmad', 'breakfast'],
    ['frokost', 'lunch'],
    ['aftensmad', 'dinner'],
    ['meget lækkert', 'delicious'],
    ['Jeg er mæt', 'I am full'],
    ['En kaffe mere, tak', 'Another coffee, please'],
    ['takeaway', 'takeaway'],
    ['at bestille', 'to order'],
    ['reservation', 'reservation'],
    ['åben', 'open'],
    ['lukket', 'closed'],
  ]);

  packs.cafe.byCategory["de"] = buildEntries([
    ['Café', 'café'],
    ['Restaurant', 'restaurant'],
    ['Speisekarte', 'menu'],
    ['Kellner', 'waiter'],
    ['Rechnung', 'bill / check'],
    ['Trinkgeld', 'tip'],
    ['Tisch', 'table'],
    ['Wasser', 'water'],
    ['Kaffee', 'coffee'],
    ['Tee', 'tea'],
    ['Bier', 'beer'],
    ['Wein', 'wine'],
    ['Brot', 'bread'],
    ['Käse', 'cheese'],
    ['Fleisch', 'meat'],
    ['Fisch', 'fish'],
    ['vegetarisch', 'vegetarian'],
    ['Ich bin allergisch gegen…', 'I am allergic to…'],
    ['Einen Tisch für zwei, bitte', 'A table for two, please'],
    ['Die Speisekarte, bitte', 'The menu, please'],
    ['Ich hätte gerne…', 'I would like…'],
    ['Was empfehlen Sie?', 'What do you recommend?'],
    ['Ist das scharf?', 'Is this spicy?'],
    ['Ohne Milch', 'Without milk'],
    ['Mit Zucker', 'With sugar'],
    ['Die Rechnung, bitte', 'The bill, please'],
    ['Kann ich mit Karte zahlen?', 'Can I pay by card?'],
    ['Bargeld', 'cash'],
    ['Beleg', 'receipt'],
    ['Frühstück', 'breakfast'],
    ['Mittagessen', 'lunch'],
    ['Abendessen', 'dinner'],
    ['lecker', 'delicious'],
    ['Ich bin satt', 'I am full'],
    ['Noch einen Kaffee, bitte', 'Another coffee, please'],
    ['zum Mitnehmen', 'takeaway'],
    ['bestellen', 'to order'],
    ['Reservierung', 'reservation'],
    ['geöffnet', 'open'],
    ['geschlossen', 'closed'],
  ]);

  packs.cafe.byCategory["fr"] = buildEntries([
    ['bistrot', 'café'],
    ['restaurant', 'restaurant'],
    ['menu', 'menu'],
    ['serveur', 'waiter'],
    ['addition', 'bill / check'],
    ['pourboire', 'tip'],
    ['table', 'table'],
    ['eau', 'water'],
    ['café', 'coffee'],
    ['thé', 'tea'],
    ['bière', 'beer'],
    ['vin', 'wine'],
    ['pain', 'bread'],
    ['fromage', 'cheese'],
    ['viande', 'meat'],
    ['poisson', 'fish'],
    ['végétarien', 'vegetarian'],
    ['Je suis allergique à…', 'I am allergic to…'],
    ['Une table pour deux, s\'il vous plaît', 'A table for two, please'],
    ['Le menu, s\'il vous plaît', 'The menu, please'],
    ['Je voudrais…', 'I would like…'],
    ['Que recommandez-vous ?', 'What do you recommend?'],
    ['C\'est épicé ?', 'Is this spicy?'],
    ['Sans lait', 'Without milk'],
    ['Avec du sucre', 'With sugar'],
    ['L\'addition, s\'il vous plaît', 'The bill, please'],
    ['Puis-je payer par carte ?', 'Can I pay by card?'],
    ['espèces', 'cash'],
    ['reçu', 'receipt'],
    ['petit-déjeuner', 'breakfast'],
    ['déjeuner', 'lunch'],
    ['dîner', 'dinner'],
    ['délicieux', 'delicious'],
    ['Je suis rassasié', 'I am full'],
    ['Un autre café, s\'il vous plaît', 'Another coffee, please'],
    ['à emporter', 'takeaway'],
    ['commander', 'to order'],
    ['réservation', 'reservation'],
    ['ouvert', 'open'],
    ['fermé', 'closed'],
  ]);

  packs.cafe.byCategory["es"] = buildEntries([
    ['cafetería', 'café'],
    ['restaurante', 'restaurant'],
    ['carta', 'menu'],
    ['camarero', 'waiter'],
    ['cuenta', 'bill / check'],
    ['propina', 'tip'],
    ['mesa', 'table'],
    ['agua', 'water'],
    ['café', 'coffee'],
    ['té', 'tea'],
    ['cerveza', 'beer'],
    ['vino', 'wine'],
    ['pan', 'bread'],
    ['queso', 'cheese'],
    ['carne', 'meat'],
    ['pescado', 'fish'],
    ['vegetariano', 'vegetarian'],
    ['Soy alérgico a…', 'I am allergic to…'],
    ['Una mesa para dos, por favor', 'A table for two, please'],
    ['La carta, por favor', 'The menu, please'],
    ['Quisiera…', 'I would like…'],
    ['¿Qué recomienda?', 'What do you recommend?'],
    ['¿Está picante?', 'Is this spicy?'],
    ['Sin leche', 'Without milk'],
    ['Con azúcar', 'With sugar'],
    ['La cuenta, por favor', 'The bill, please'],
    ['¿Puedo pagar con tarjeta?', 'Can I pay by card?'],
    ['efectivo', 'cash'],
    ['recibo', 'receipt'],
    ['desayuno', 'breakfast'],
    ['almuerzo', 'lunch'],
    ['cena', 'dinner'],
    ['delicioso', 'delicious'],
    ['Estoy lleno', 'I am full'],
    ['Otro café, por favor', 'Another coffee, please'],
    ['para llevar', 'takeaway'],
    ['pedir', 'to order'],
    ['reserva', 'reservation'],
    ['abierto', 'open'],
    ['cerrado', 'closed'],
  ]);

  packs.cafe.byCategory["it"] = buildEntries([
    ['bar', 'café'],
    ['ristorante', 'restaurant'],
    ['menu', 'menu'],
    ['cameriere', 'waiter'],
    ['conto', 'bill / check'],
    ['mancia', 'tip'],
    ['tavolo', 'table'],
    ['acqua', 'water'],
    ['caffè', 'coffee'],
    ['tè', 'tea'],
    ['birra', 'beer'],
    ['vino', 'wine'],
    ['pane', 'bread'],
    ['formaggio', 'cheese'],
    ['carne', 'meat'],
    ['pesce', 'fish'],
    ['vegetariano', 'vegetarian'],
    ['Sono allergico a…', 'I am allergic to…'],
    ['Un tavolo per due, per favore', 'A table for two, please'],
    ['Il menu, per favore', 'The menu, please'],
    ['Vorrei…', 'I would like…'],
    ['Cosa mi consiglia?', 'What do you recommend?'],
    ['È piccante?', 'Is this spicy?'],
    ['Senza latte', 'Without milk'],
    ['Con zucchero', 'With sugar'],
    ['Il conto, per favore', 'The bill, please'],
    ['Posso pagare con la carta?', 'Can I pay by card?'],
    ['contanti', 'cash'],
    ['scontrino', 'receipt'],
    ['colazione', 'breakfast'],
    ['pranzo', 'lunch'],
    ['cena', 'dinner'],
    ['delizioso', 'delicious'],
    ['Sono sazio', 'I am full'],
    ['Un altro caffè, per favore', 'Another coffee, please'],
    ['da asporto', 'takeaway'],
    ['ordinare', 'to order'],
    ['prenotazione', 'reservation'],
    ['aperto', 'open'],
    ['chiuso', 'closed'],
  ]);

  packs.cafe.byCategory["nl"] = buildEntries([
    ['café', 'café'],
    ['restaurant', 'restaurant'],
    ['menu', 'menu'],
    ['ober', 'waiter'],
    ['rekening', 'bill / check'],
    ['fooi', 'tip'],
    ['tafel', 'table'],
    ['water', 'water'],
    ['koffie', 'coffee'],
    ['thee', 'tea'],
    ['bier', 'beer'],
    ['wijn', 'wine'],
    ['brood', 'bread'],
    ['kaas', 'cheese'],
    ['vlees', 'meat'],
    ['vis', 'fish'],
    ['vegetarisch', 'vegetarian'],
    ['Ik ben allergisch voor…', 'I am allergic to…'],
    ['Een tafel voor twee, alstublieft', 'A table for two, please'],
    ['De menukaart, alstublieft', 'The menu, please'],
    ['Ik wil graag…', 'I would like…'],
    ['Wat raadt u aan?', 'What do you recommend?'],
    ['Is dit pittig?', 'Is this spicy?'],
    ['Zonder melk', 'Without milk'],
    ['Met suiker', 'With sugar'],
    ['De rekening, alstublieft', 'The bill, please'],
    ['Kan ik met pin betalen?', 'Can I pay by card?'],
    ['contant', 'cash'],
    ['bonnetje', 'receipt'],
    ['ontbijt', 'breakfast'],
    ['lunch', 'lunch'],
    ['diner', 'dinner'],
    ['lekker', 'delicious'],
    ['Ik zit vol', 'I am full'],
    ['Nog een koffie, alstublieft', 'Another coffee, please'],
    ['afhalen', 'takeaway'],
    ['bestellen', 'to order'],
    ['reservering', 'reservation'],
    ['open', 'open'],
    ['gesloten', 'closed'],
  ]);

  packs.cafe.byCategory["pt"] = buildEntries([
    ['cafeteria', 'café'],
    ['restaurante', 'restaurant'],
    ['cardápio', 'menu'],
    ['garçom', 'waiter'],
    ['conta', 'bill / check'],
    ['gorjeta', 'tip'],
    ['mesa', 'table'],
    ['água', 'water'],
    ['café', 'coffee'],
    ['chá', 'tea'],
    ['cerveja', 'beer'],
    ['vinho', 'wine'],
    ['pão', 'bread'],
    ['queijo', 'cheese'],
    ['carne', 'meat'],
    ['peixe', 'fish'],
    ['vegetariano', 'vegetarian'],
    ['Sou alérgico a…', 'I am allergic to…'],
    ['Uma mesa para dois, por favor', 'A table for two, please'],
    ['O cardápio, por favor', 'The menu, please'],
    ['Eu gostaria de…', 'I would like…'],
    ['O que você recomenda?', 'What do you recommend?'],
    ['Isso é apimentado?', 'Is this spicy?'],
    ['Sem leite', 'Without milk'],
    ['Com açúcar', 'With sugar'],
    ['A conta, por favor', 'The bill, please'],
    ['Posso pagar com cartão?', 'Can I pay by card?'],
    ['dinheiro', 'cash'],
    ['recibo', 'receipt'],
    ['café da manhã', 'breakfast'],
    ['almoço', 'lunch'],
    ['jantar', 'dinner'],
    ['delicioso', 'delicious'],
    ['Estou cheio', 'I am full'],
    ['Mais um café, por favor', 'Another coffee, please'],
    ['para viagem', 'takeaway'],
    ['pedir', 'to order'],
    ['reserva', 'reservation'],
    ['aberto', 'open'],
    ['fechado', 'closed'],
  ]);

  packs.cafe.byCategory["pl"] = buildEntries([
    ['kawiarnia', 'café'],
    ['restauracja', 'restaurant'],
    ['menu', 'menu'],
    ['kelner', 'waiter'],
    ['rachunek', 'bill / check'],
    ['napiwek', 'tip'],
    ['stół', 'table'],
    ['woda', 'water'],
    ['kawa', 'coffee'],
    ['herbata', 'tea'],
    ['piwo', 'beer'],
    ['wino', 'wine'],
    ['chleb', 'bread'],
    ['ser', 'cheese'],
    ['mięso', 'meat'],
    ['ryba', 'fish'],
    ['wegetariański', 'vegetarian'],
    ['Mam uczulenie na…', 'I am allergic to…'],
    ['Stolik dla dwóch osób, proszę', 'A table for two, please'],
    ['Menu, proszę', 'The menu, please'],
    ['Poproszę…', 'I would like…'],
    ['Co pan poleca?', 'What do you recommend?'],
    ['Czy to jest ostre?', 'Is this spicy?'],
    ['Bez mleka', 'Without milk'],
    ['Z cukrem', 'With sugar'],
    ['Rachunek, proszę', 'The bill, please'],
    ['Czy mogę zapłacić kartą?', 'Can I pay by card?'],
    ['gotówka', 'cash'],
    ['paragon', 'receipt'],
    ['śniadanie', 'breakfast'],
    ['obiad', 'lunch'],
    ['kolacja', 'dinner'],
    ['pyszne', 'delicious'],
    ['Jestem najedzony', 'I am full'],
    ['Jeszcze jedną kawę, proszę', 'Another coffee, please'],
    ['na wynos', 'takeaway'],
    ['zamawiać', 'to order'],
    ['rezerwacja', 'reservation'],
    ['otwarte', 'open'],
    ['zamknięte', 'closed'],
  ]);

  packs.campus.byCategory["nb-bokmal"] = buildEntries([
    ['universitet', 'university'],
    ['student', 'student'],
    ['campus', 'campus'],
    ['forelesning', 'lecture'],
    ['seminar', 'seminar'],
    ['eksamen', 'exam'],
    ['lekser', 'homework'],
    ['bibliotek', 'library'],
    ['klasserom', 'classroom'],
    ['professor', 'professor'],
    ['lærer', 'teacher'],
    ['medstudent', 'classmate'],
    ['timeplan', 'timetable'],
    ['frist', 'deadline'],
    ['oppgave', 'assignment'],
    ['å studere', 'to study'],
    ['å lære', 'to learn'],
    ['å bestå eksamen', 'to pass an exam'],
    ['å stryke', 'to fail an exam'],
    ['Hvor er biblioteket?', 'Where is the library?'],
    ['Jeg har time klokken ni', 'I have a class at nine'],
    ['Kan du hjelpe meg?', 'Can you help me?'],
    ['Jeg er utvekslingsstudent', 'I am an exchange student'],
    ['studentbevis', 'student ID'],
    ['stipend', 'scholarship'],
    ['studentbolig', 'dorm / student housing'],
    ['kantine', 'canteen / cafeteria'],
    ['notater', 'notes'],
    ['å notere', 'to take notes'],
    ['gruppearbeid', 'group work'],
    ['presentasjon', 'presentation'],
    ['karakter', 'grade'],
    ['semester', 'semester'],
    ['pause', 'break'],
    ['Jeg forstår ikke dette', 'I don\'t understand this'],
    ['Kan du gjenta det?', 'Could you repeat that?'],
    ['kontortid', 'office hours'],
    ['lab', 'lab'],
    ['forskning', 'research'],
    ['masteroppgave', 'thesis'],
  ]);

  packs.campus.byCategory["sv"] = buildEntries([
    ['universitet', 'university'],
    ['student', 'student'],
    ['campus', 'campus'],
    ['föreläsning', 'lecture'],
    ['seminarium', 'seminar'],
    ['tenta', 'exam'],
    ['läxor', 'homework'],
    ['bibliotek', 'library'],
    ['klassrum', 'classroom'],
    ['professor', 'professor'],
    ['lärare', 'teacher'],
    ['kurskamrat', 'classmate'],
    ['schema', 'timetable'],
    ['deadline', 'deadline'],
    ['uppgift', 'assignment'],
    ['att studera', 'to study'],
    ['att lära sig', 'to learn'],
    ['att klara tentan', 'to pass an exam'],
    ['att kugga', 'to fail an exam'],
    ['Var är biblioteket?', 'Where is the library?'],
    ['Jag har lektion klockan nio', 'I have a class at nine'],
    ['Kan du hjälpa mig?', 'Can you help me?'],
    ['Jag är utbytesstudent', 'I am an exchange student'],
    ['studentkort', 'student ID'],
    ['stipendium', 'scholarship'],
    ['studentbostad', 'dorm / student housing'],
    ['matsal', 'canteen / cafeteria'],
    ['anteckningar', 'notes'],
    ['att anteckna', 'to take notes'],
    ['grupparbete', 'group work'],
    ['presentation', 'presentation'],
    ['betyg', 'grade'],
    ['termin', 'semester'],
    ['rast', 'break'],
    ['Jag förstår inte det här', 'I don\'t understand this'],
    ['Kan du upprepa det?', 'Could you repeat that?'],
    ['mottagningstid', 'office hours'],
    ['labb', 'lab'],
    ['forskning', 'research'],
    ['uppsats', 'thesis'],
  ]);

  packs.campus.byCategory["da"] = buildEntries([
    ['universitet', 'university'],
    ['studerende', 'student'],
    ['campus', 'campus'],
    ['forelæsning', 'lecture'],
    ['seminar', 'seminar'],
    ['eksamen', 'exam'],
    ['lektier', 'homework'],
    ['bibliotek', 'library'],
    ['klasselokale', 'classroom'],
    ['professor', 'professor'],
    ['lærer', 'teacher'],
    ['medstuderende', 'classmate'],
    ['skema', 'timetable'],
    ['frist', 'deadline'],
    ['opgave', 'assignment'],
    ['at studere', 'to study'],
    ['at lære', 'to learn'],
    ['at bestå eksamen', 'to pass an exam'],
    ['at dumpe', 'to fail an exam'],
    ['Hvor er biblioteket?', 'Where is the library?'],
    ['Jeg har time klokken ni', 'I have a class at nine'],
    ['Kan du hjælpe mig?', 'Can you help me?'],
    ['Jeg er udvekslingsstuderende', 'I am an exchange student'],
    ['studiekort', 'student ID'],
    ['stipendium', 'scholarship'],
    ['kollegium', 'dorm / student housing'],
    ['kantine', 'canteen / cafeteria'],
    ['noter', 'notes'],
    ['at tage noter', 'to take notes'],
    ['gruppearbejde', 'group work'],
    ['præsentation', 'presentation'],
    ['karakter', 'grade'],
    ['semester', 'semester'],
    ['pause', 'break'],
    ['Jeg forstår ikke det her', 'I don\'t understand this'],
    ['Kan du gentage det?', 'Could you repeat that?'],
    ['træffetid', 'office hours'],
    ['lab', 'lab'],
    ['forskning', 'research'],
    ['speciale', 'thesis'],
  ]);

  packs.campus.byCategory["de"] = buildEntries([
    ['Universität', 'university'],
    ['Student', 'student'],
    ['Campus', 'campus'],
    ['Vorlesung', 'lecture'],
    ['Seminar', 'seminar'],
    ['Prüfung', 'exam'],
    ['Hausaufgaben', 'homework'],
    ['Bibliothek', 'library'],
    ['Klassenzimmer', 'classroom'],
    ['Professor', 'professor'],
    ['Lehrer', 'teacher'],
    ['Kommilitone', 'classmate'],
    ['Stundenplan', 'timetable'],
    ['Frist', 'deadline'],
    ['Aufgabe', 'assignment'],
    ['studieren', 'to study'],
    ['lernen', 'to learn'],
    ['eine Prüfung bestehen', 'to pass an exam'],
    ['durchfallen', 'to fail an exam'],
    ['Wo ist die Bibliothek?', 'Where is the library?'],
    ['Ich habe um neun Unterricht', 'I have a class at nine'],
    ['Können Sie mir helfen?', 'Can you help me?'],
    ['Ich bin Austauschstudent', 'I am an exchange student'],
    ['Studentenausweis', 'student ID'],
    ['Stipendium', 'scholarship'],
    ['Wohnheim', 'dorm / student housing'],
    ['Mensa', 'canteen / cafeteria'],
    ['Notizen', 'notes'],
    ['mitschreiben', 'to take notes'],
    ['Gruppenarbeit', 'group work'],
    ['Präsentation', 'presentation'],
    ['Note', 'grade'],
    ['Semester', 'semester'],
    ['Pause', 'break'],
    ['Ich verstehe das nicht', 'I don\'t understand this'],
    ['Können Sie das wiederholen?', 'Could you repeat that?'],
    ['Sprechstunde', 'office hours'],
    ['Labor', 'lab'],
    ['Forschung', 'research'],
    ['Abschlussarbeit', 'thesis'],
  ]);

  packs.campus.byCategory["fr"] = buildEntries([
    ['université', 'university'],
    ['étudiant', 'student'],
    ['campus', 'campus'],
    ['cours magistral', 'lecture'],
    ['séminaire', 'seminar'],
    ['examen', 'exam'],
    ['devoirs', 'homework'],
    ['bibliothèque', 'library'],
    ['salle de classe', 'classroom'],
    ['professeur', 'professor'],
    ['enseignant', 'teacher'],
    ['camarade de classe', 'classmate'],
    ['emploi du temps', 'timetable'],
    ['date limite', 'deadline'],
    ['devoir', 'assignment'],
    ['étudier', 'to study'],
    ['apprendre', 'to learn'],
    ['réussir un examen', 'to pass an exam'],
    ['échouer à un examen', 'to fail an exam'],
    ['Où est la bibliothèque ?', 'Where is the library?'],
    ['J\'ai cours à neuf heures', 'I have a class at nine'],
    ['Pouvez-vous m\'aider ?', 'Can you help me?'],
    ['Je suis étudiant en échange', 'I am an exchange student'],
    ['carte d\'étudiant', 'student ID'],
    ['bourse', 'scholarship'],
    ['résidence universitaire', 'dorm / student housing'],
    ['cafétéria', 'canteen / cafeteria'],
    ['notes', 'notes'],
    ['prendre des notes', 'to take notes'],
    ['travail de groupe', 'group work'],
    ['présentation', 'presentation'],
    ['note', 'grade'],
    ['semestre', 'semester'],
    ['pause', 'break'],
    ['Je ne comprends pas ça', 'I don\'t understand this'],
    ['Pouvez-vous répéter ?', 'Could you repeat that?'],
    ['heures de permanence', 'office hours'],
    ['laboratoire', 'lab'],
    ['recherche', 'research'],
    ['mémoire', 'thesis'],
  ]);

  packs.campus.byCategory["es"] = buildEntries([
    ['universidad', 'university'],
    ['estudiante', 'student'],
    ['campus', 'campus'],
    ['clase magistral', 'lecture'],
    ['seminario', 'seminar'],
    ['examen', 'exam'],
    ['deberes', 'homework'],
    ['biblioteca', 'library'],
    ['aula', 'classroom'],
    ['profesor', 'professor'],
    ['maestro', 'teacher'],
    ['compañero de clase', 'classmate'],
    ['horario', 'timetable'],
    ['fecha límite', 'deadline'],
    ['trabajo', 'assignment'],
    ['estudiar', 'to study'],
    ['aprender', 'to learn'],
    ['aprobar un examen', 'to pass an exam'],
    ['suspender un examen', 'to fail an exam'],
    ['¿Dónde está la biblioteca?', 'Where is the library?'],
    ['Tengo clase a las nueve', 'I have a class at nine'],
    ['¿Me puede ayudar?', 'Can you help me?'],
    ['Soy estudiante de intercambio', 'I am an exchange student'],
    ['carnet de estudiante', 'student ID'],
    ['beca', 'scholarship'],
    ['residencia de estudiantes', 'dorm / student housing'],
    ['cafetería', 'canteen / cafeteria'],
    ['apuntes', 'notes'],
    ['tomar apuntes', 'to take notes'],
    ['trabajo en grupo', 'group work'],
    ['presentación', 'presentation'],
    ['nota', 'grade'],
    ['semestre', 'semester'],
    ['recreo', 'break'],
    ['No entiendo esto', 'I don\'t understand this'],
    ['¿Puede repetir?', 'Could you repeat that?'],
    ['horas de tutoría', 'office hours'],
    ['laboratorio', 'lab'],
    ['investigación', 'research'],
    ['tesis', 'thesis'],
  ]);

  packs.campus.byCategory["it"] = buildEntries([
    ['università', 'university'],
    ['studente', 'student'],
    ['campus', 'campus'],
    ['lezione', 'lecture'],
    ['seminario', 'seminar'],
    ['esame', 'exam'],
    ['compiti', 'homework'],
    ['biblioteca', 'library'],
    ['aula', 'classroom'],
    ['professore', 'professor'],
    ['insegnante', 'teacher'],
    ['compagno di corso', 'classmate'],
    ['orario', 'timetable'],
    ['scadenza', 'deadline'],
    ['compito', 'assignment'],
    ['studiare', 'to study'],
    ['imparare', 'to learn'],
    ['superare un esame', 'to pass an exam'],
    ['bocciare un esame', 'to fail an exam'],
    ['Dov\'è la biblioteca?', 'Where is the library?'],
    ['Ho lezione alle nove', 'I have a class at nine'],
    ['Mi può aiutare?', 'Can you help me?'],
    ['Sono uno studente in scambio', 'I am an exchange student'],
    ['tesserino universitario', 'student ID'],
    ['borsa di studio', 'scholarship'],
    ['casa dello studente', 'dorm / student housing'],
    ['mensa', 'canteen / cafeteria'],
    ['appunti', 'notes'],
    ['prendere appunti', 'to take notes'],
    ['lavoro di gruppo', 'group work'],
    ['presentazione', 'presentation'],
    ['voto', 'grade'],
    ['semestre', 'semester'],
    ['pausa', 'break'],
    ['Non capisco questo', 'I don\'t understand this'],
    ['Può ripetere?', 'Could you repeat that?'],
    ['ricevimento', 'office hours'],
    ['laboratorio', 'lab'],
    ['ricerca', 'research'],
    ['tesi', 'thesis'],
  ]);

  packs.campus.byCategory["nl"] = buildEntries([
    ['universiteit', 'university'],
    ['student', 'student'],
    ['campus', 'campus'],
    ['hoorcollege', 'lecture'],
    ['werkcollege', 'seminar'],
    ['tentamen', 'exam'],
    ['huiswerk', 'homework'],
    ['bibliotheek', 'library'],
    ['klaslokaal', 'classroom'],
    ['hoogleraar', 'professor'],
    ['leraar', 'teacher'],
    ['klasgenoot', 'classmate'],
    ['rooster', 'timetable'],
    ['deadline', 'deadline'],
    ['opdracht', 'assignment'],
    ['studeren', 'to study'],
    ['leren', 'to learn'],
    ['slagen voor een tentamen', 'to pass an exam'],
    ['zakken voor een tentamen', 'to fail an exam'],
    ['Waar is de bibliotheek?', 'Where is the library?'],
    ['Ik heb om negen les', 'I have a class at nine'],
    ['Kunt u me helpen?', 'Can you help me?'],
    ['Ik ben uitwisselingsstudent', 'I am an exchange student'],
    ['studentenkaart', 'student ID'],
    ['beurs', 'scholarship'],
    ['studentenhuis', 'dorm / student housing'],
    ['kantine', 'canteen / cafeteria'],
    ['aantekeningen', 'notes'],
    ['aantekeningen maken', 'to take notes'],
    ['groepsopdracht', 'group work'],
    ['presentatie', 'presentation'],
    ['cijfer', 'grade'],
    ['semester', 'semester'],
    ['pauze', 'break'],
    ['Ik begrijp dit niet', 'I don\'t understand this'],
    ['Kunt u dat herhalen?', 'Could you repeat that?'],
    ['spreekuur', 'office hours'],
    ['lab', 'lab'],
    ['onderzoek', 'research'],
    ['scriptie', 'thesis'],
  ]);

  packs.campus.byCategory["pt"] = buildEntries([
    ['universidade', 'university'],
    ['estudante', 'student'],
    ['campus', 'campus'],
    ['aula', 'lecture'],
    ['seminário', 'seminar'],
    ['prova', 'exam'],
    ['lição de casa', 'homework'],
    ['biblioteca', 'library'],
    ['sala de aula', 'classroom'],
    ['professor', 'professor'],
    ['professor da escola', 'teacher'],
    ['colega de turma', 'classmate'],
    ['horário', 'timetable'],
    ['prazo', 'deadline'],
    ['trabalho', 'assignment'],
    ['estudar', 'to study'],
    ['aprender', 'to learn'],
    ['passar na prova', 'to pass an exam'],
    ['reprovar na prova', 'to fail an exam'],
    ['Onde fica a biblioteca?', 'Where is the library?'],
    ['Tenho aula às nove', 'I have a class at nine'],
    ['Pode me ajudar?', 'Can you help me?'],
    ['Sou estudante de intercâmbio', 'I am an exchange student'],
    ['carteirinha de estudante', 'student ID'],
    ['bolsa de estudos', 'scholarship'],
    ['república estudantil', 'dorm / student housing'],
    ['bandejão', 'canteen / cafeteria'],
    ['anotações', 'notes'],
    ['fazer anotações', 'to take notes'],
    ['trabalho em grupo', 'group work'],
    ['apresentação', 'presentation'],
    ['nota', 'grade'],
    ['semestre', 'semester'],
    ['intervalo', 'break'],
    ['Não entendo isto', 'I don\'t understand this'],
    ['Pode repetir?', 'Could you repeat that?'],
    ['horário de atendimento', 'office hours'],
    ['laboratório', 'lab'],
    ['pesquisa', 'research'],
    ['tcc', 'thesis'],
  ]);

  packs.campus.byCategory["pl"] = buildEntries([
    ['uniwersytet', 'university'],
    ['student', 'student'],
    ['kampus', 'campus'],
    ['wykład', 'lecture'],
    ['seminarium', 'seminar'],
    ['egzamin', 'exam'],
    ['zadanie domowe', 'homework'],
    ['biblioteka', 'library'],
    ['sala lekcyjna', 'classroom'],
    ['profesor', 'professor'],
    ['nauczyciel', 'teacher'],
    ['kolega z roku', 'classmate'],
    ['plan zajęć', 'timetable'],
    ['termin', 'deadline'],
    ['zadanie', 'assignment'],
    ['studiować', 'to study'],
    ['uczyć się', 'to learn'],
    ['zdać egzamin', 'to pass an exam'],
    ['oblać egzamin', 'to fail an exam'],
    ['Gdzie jest biblioteka?', 'Where is the library?'],
    ['Mam zajęcia o dziewiątej', 'I have a class at nine'],
    ['Czy może mi pan pomóc?', 'Can you help me?'],
    ['Jestem studentem wymiany', 'I am an exchange student'],
    ['legitymacja studencka', 'student ID'],
    ['stypendium', 'scholarship'],
    ['akademik', 'dorm / student housing'],
    ['stołówka', 'canteen / cafeteria'],
    ['notatki', 'notes'],
    ['robić notatki', 'to take notes'],
    ['praca grupowa', 'group work'],
    ['prezentacja', 'presentation'],
    ['ocena', 'grade'],
    ['semestr', 'semester'],
    ['przerwa', 'break'],
    ['Nie rozumiem tego', 'I don\'t understand this'],
    ['Czy może pan powtórzyć?', 'Could you repeat that?'],
    ['dyżur', 'office hours'],
    ['laboratorium', 'lab'],
    ['badania', 'research'],
    ['praca dyplomowa', 'thesis'],
  ]);

  packs.doctor.byCategory["nb-bokmal"] = buildEntries([
    ['lege', 'doctor'],
    ['sykehus', 'hospital'],
    ['apotek', 'pharmacy'],
    ['akuttmottak', 'emergency room'],
    ['time', 'appointment'],
    ['resept', 'prescription'],
    ['medisin', 'medicine'],
    ['smerte', 'pain'],
    ['feber', 'fever'],
    ['hoste', 'cough'],
    ['forkjølelse', 'cold (illness)'],
    ['hodepine', 'headache'],
    ['magesmerter', 'stomach ache'],
    ['allergi', 'allergy'],
    ['blodtrykk', 'blood pressure'],
    ['sykepleier', 'nurse'],
    ['ambulanse', 'ambulance'],
    ['helsekort', 'insurance card'],
    ['Jeg er syk', 'I feel sick'],
    ['Jeg trenger en lege', 'I need a doctor'],
    ['Det gjør vondt her', 'It hurts here'],
    ['Jeg har feber', 'I have a fever'],
    ['Hvor lenge har du hatt dette?', 'How long have you had this?'],
    ['Jeg er gravid', 'I am pregnant'],
    ['Jeg tar denne medisinen', 'I take this medicine'],
    ['Er du allergisk mot noe?', 'Are you allergic to anything?'],
    ['Jeg trenger en sykmelding', 'I need a sick note'],
    ['Hvor er apoteket?', 'Where is the pharmacy?'],
    ['Er det alvorlig?', 'Is it serious?'],
    ['hvile', 'rest'],
    ['bandasje', 'bandage'],
    ['vaksine', 'vaccine'],
    ['tannlege', 'dentist'],
    ['øyelege', 'eye doctor'],
    ['Jeg trenger en tolk', 'I need an interpreter'],
    ['Kan jeg få kvittering?', 'Can I get a receipt?'],
    ['nødsituasjon', 'emergency'],
    ['Ring ambulanse', 'Call an ambulance'],
    ['Jeg har forsikring', 'I have insurance'],
    ['symptomer', 'symptoms'],
  ]);

  packs.doctor.byCategory["sv"] = buildEntries([
    ['läkare', 'doctor'],
    ['sjukhus', 'hospital'],
    ['apotek', 'pharmacy'],
    ['akut', 'emergency room'],
    ['tid', 'appointment'],
    ['recept', 'prescription'],
    ['medicin', 'medicine'],
    ['smärta', 'pain'],
    ['feber', 'fever'],
    ['hosta', 'cough'],
    ['förkylning', 'cold (illness)'],
    ['huvudvärk', 'headache'],
    ['magont', 'stomach ache'],
    ['allergi', 'allergy'],
    ['blodtryck', 'blood pressure'],
    ['sjuksköterska', 'nurse'],
    ['ambulans', 'ambulance'],
    ['försäkringskort', 'insurance card'],
    ['Jag mår dåligt', 'I feel sick'],
    ['Jag behöver en läkare', 'I need a doctor'],
    ['Det gör ont här', 'It hurts here'],
    ['Jag har feber', 'I have a fever'],
    ['Hur länge har du haft det här?', 'How long have you had this?'],
    ['Jag är gravid', 'I am pregnant'],
    ['Jag tar den här medicinen', 'I take this medicine'],
    ['Är du allergisk mot något?', 'Are you allergic to anything?'],
    ['Jag behöver ett sjukintyg', 'I need a sick note'],
    ['Var är apoteket?', 'Where is the pharmacy?'],
    ['Är det allvarligt?', 'Is it serious?'],
    ['vila', 'rest'],
    ['bandage', 'bandage'],
    ['vaccin', 'vaccine'],
    ['tandläkare', 'dentist'],
    ['ögonläkare', 'eye doctor'],
    ['Jag behöver en tolk', 'I need an interpreter'],
    ['Kan jag få kvitto?', 'Can I get a receipt?'],
    ['nödsituation', 'emergency'],
    ['Ring en ambulans', 'Call an ambulance'],
    ['Jag har försäkring', 'I have insurance'],
    ['symptom', 'symptoms'],
  ]);

  packs.doctor.byCategory["da"] = buildEntries([
    ['læge', 'doctor'],
    ['hospital', 'hospital'],
    ['apotek', 'pharmacy'],
    ['skadestue', 'emergency room'],
    ['tid', 'appointment'],
    ['recept', 'prescription'],
    ['medicin', 'medicine'],
    ['smerte', 'pain'],
    ['feber', 'fever'],
    ['hoste', 'cough'],
    ['forkølelse', 'cold (illness)'],
    ['hovedpine', 'headache'],
    ['mavepine', 'stomach ache'],
    ['allergi', 'allergy'],
    ['blodtryk', 'blood pressure'],
    ['sygeplejerske', 'nurse'],
    ['ambulance', 'ambulance'],
    ['sygesikringskort', 'insurance card'],
    ['Jeg er syg', 'I feel sick'],
    ['Jeg har brug for en læge', 'I need a doctor'],
    ['Det gør ondt her', 'It hurts here'],
    ['Jeg har feber', 'I have a fever'],
    ['Hvor længe har du haft det?', 'How long have you had this?'],
    ['Jeg er gravid', 'I am pregnant'],
    ['Jeg tager denne medicin', 'I take this medicine'],
    ['Er du allergisk over for noget?', 'Are you allergic to anything?'],
    ['Jeg har brug for en sygemelding', 'I need a sick note'],
    ['Hvor er apoteket?', 'Where is the pharmacy?'],
    ['Er det alvorligt?', 'Is it serious?'],
    ['hvile', 'rest'],
    ['bandage', 'bandage'],
    ['vaccine', 'vaccine'],
    ['tandlæge', 'dentist'],
    ['øjenlæge', 'eye doctor'],
    ['Jeg har brug for en tolk', 'I need an interpreter'],
    ['Kan jeg få en kvittering?', 'Can I get a receipt?'],
    ['nødsituation', 'emergency'],
    ['Ring efter en ambulance', 'Call an ambulance'],
    ['Jeg har forsikring', 'I have insurance'],
    ['symptomer', 'symptoms'],
  ]);

  packs.doctor.byCategory["de"] = buildEntries([
    ['Arzt', 'doctor'],
    ['Krankenhaus', 'hospital'],
    ['Apotheke', 'pharmacy'],
    ['Notaufnahme', 'emergency room'],
    ['Termin', 'appointment'],
    ['Rezept', 'prescription'],
    ['Medizin', 'medicine'],
    ['Schmerz', 'pain'],
    ['Fieber', 'fever'],
    ['Husten', 'cough'],
    ['Erkältung', 'cold (illness)'],
    ['Kopfschmerzen', 'headache'],
    ['Bauchschmerzen', 'stomach ache'],
    ['Allergie', 'allergy'],
    ['Blutdruck', 'blood pressure'],
    ['Krankenschwester', 'nurse'],
    ['Krankenwagen', 'ambulance'],
    ['Versicherungskarte', 'insurance card'],
    ['Mir ist übel', 'I feel sick'],
    ['Ich brauche einen Arzt', 'I need a doctor'],
    ['Hier tut es weh', 'It hurts here'],
    ['Ich habe Fieber', 'I have a fever'],
    ['Wie lange haben Sie das schon?', 'How long have you had this?'],
    ['Ich bin schwanger', 'I am pregnant'],
    ['Ich nehme dieses Medikament', 'I take this medicine'],
    ['Sind Sie gegen etwas allergisch?', 'Are you allergic to anything?'],
    ['Ich brauche eine Krankschreibung', 'I need a sick note'],
    ['Wo ist die Apotheke?', 'Where is the pharmacy?'],
    ['Ist es ernst?', 'Is it serious?'],
    ['Ruhe', 'rest'],
    ['Verband', 'bandage'],
    ['Impfstoff', 'vaccine'],
    ['Zahnarzt', 'dentist'],
    ['Augenarzt', 'eye doctor'],
    ['Ich brauche einen Dolmetscher', 'I need an interpreter'],
    ['Kann ich eine Quittung bekommen?', 'Can I get a receipt?'],
    ['Notfall', 'emergency'],
    ['Rufen Sie einen Krankenwagen', 'Call an ambulance'],
    ['Ich bin versichert', 'I have insurance'],
    ['Symptome', 'symptoms'],
  ]);

  packs.doctor.byCategory["fr"] = buildEntries([
    ['médecin', 'doctor'],
    ['hôpital', 'hospital'],
    ['pharmacie', 'pharmacy'],
    ['urgences', 'emergency room'],
    ['rendez-vous', 'appointment'],
    ['ordonnance', 'prescription'],
    ['médicament', 'medicine'],
    ['douleur', 'pain'],
    ['fièvre', 'fever'],
    ['toux', 'cough'],
    ['rhume', 'cold (illness)'],
    ['mal de tête', 'headache'],
    ['mal au ventre', 'stomach ache'],
    ['allergie', 'allergy'],
    ['tension artérielle', 'blood pressure'],
    ['infirmier', 'nurse'],
    ['ambulance', 'ambulance'],
    ['carte d\'assurance', 'insurance card'],
    ['Je me sens mal', 'I feel sick'],
    ['J\'ai besoin d\'un médecin', 'I need a doctor'],
    ['Ça fait mal ici', 'It hurts here'],
    ['J\'ai de la fièvre', 'I have a fever'],
    ['Depuis combien de temps avez-vous ça ?', 'How long have you had this?'],
    ['Je suis enceinte', 'I am pregnant'],
    ['Je prends ce médicament', 'I take this medicine'],
    ['Êtes-vous allergique à quelque chose ?', 'Are you allergic to anything?'],
    ['J\'ai besoin d\'un arrêt de travail', 'I need a sick note'],
    ['Où est la pharmacie ?', 'Where is the pharmacy?'],
    ['Est-ce grave ?', 'Is it serious?'],
    ['repos', 'rest'],
    ['pansement', 'bandage'],
    ['vaccin', 'vaccine'],
    ['dentiste', 'dentist'],
    ['ophtalmologue', 'eye doctor'],
    ['J\'ai besoin d\'un interprète', 'I need an interpreter'],
    ['Puis-je avoir un reçu ?', 'Can I get a receipt?'],
    ['urgence', 'emergency'],
    ['Appelez une ambulance', 'Call an ambulance'],
    ['J\'ai une assurance', 'I have insurance'],
    ['symptômes', 'symptoms'],
  ]);

  packs.doctor.byCategory["es"] = buildEntries([
    ['médico', 'doctor'],
    ['hospital', 'hospital'],
    ['farmacia', 'pharmacy'],
    ['urgencias', 'emergency room'],
    ['cita', 'appointment'],
    ['receta', 'prescription'],
    ['medicamento', 'medicine'],
    ['dolor', 'pain'],
    ['fiebre', 'fever'],
    ['tos', 'cough'],
    ['resfriado', 'cold (illness)'],
    ['dolor de cabeza', 'headache'],
    ['dolor de estómago', 'stomach ache'],
    ['alergia', 'allergy'],
    ['presión arterial', 'blood pressure'],
    ['enfermero', 'nurse'],
    ['ambulancia', 'ambulance'],
    ['tarjeta sanitaria', 'insurance card'],
    ['Me siento mal', 'I feel sick'],
    ['Necesito un médico', 'I need a doctor'],
    ['Me duele aquí', 'It hurts here'],
    ['Tengo fiebre', 'I have a fever'],
    ['¿Desde cuándo le pasa esto?', 'How long have you had this?'],
    ['Estoy embarazada', 'I am pregnant'],
    ['Tomo este medicamento', 'I take this medicine'],
    ['¿Es alérgico a algo?', 'Are you allergic to anything?'],
    ['Necesito una baja médica', 'I need a sick note'],
    ['¿Dónde está la farmacia?', 'Where is the pharmacy?'],
    ['¿Es grave?', 'Is it serious?'],
    ['reposo', 'rest'],
    ['venda', 'bandage'],
    ['vacuna', 'vaccine'],
    ['dentista', 'dentist'],
    ['oculista', 'eye doctor'],
    ['Necesito un intérprete', 'I need an interpreter'],
    ['¿Puedo tener un recibo?', 'Can I get a receipt?'],
    ['emergencia', 'emergency'],
    ['Llame a una ambulancia', 'Call an ambulance'],
    ['Tengo seguro', 'I have insurance'],
    ['síntomas', 'symptoms'],
  ]);

  packs.doctor.byCategory["it"] = buildEntries([
    ['medico', 'doctor'],
    ['ospedale', 'hospital'],
    ['farmacia', 'pharmacy'],
    ['pronto soccorso', 'emergency room'],
    ['appuntamento', 'appointment'],
    ['ricetta', 'prescription'],
    ['medicina', 'medicine'],
    ['dolore', 'pain'],
    ['febbre', 'fever'],
    ['tosse', 'cough'],
    ['raffreddore', 'cold (illness)'],
    ['mal di testa', 'headache'],
    ['mal di pancia', 'stomach ache'],
    ['allergia', 'allergy'],
    ['pressione sanguigna', 'blood pressure'],
    ['infermiere', 'nurse'],
    ['ambulanza', 'ambulance'],
    ['tessera sanitaria', 'insurance card'],
    ['Mi sento male', 'I feel sick'],
    ['Ho bisogno di un medico', 'I need a doctor'],
    ['Mi fa male qui', 'It hurts here'],
    ['Ho la febbre', 'I have a fever'],
    ['Da quanto tempo ha questo?', 'How long have you had this?'],
    ['Sono incinta', 'I am pregnant'],
    ['Prendo questa medicina', 'I take this medicine'],
    ['È allergico a qualcosa?', 'Are you allergic to anything?'],
    ['Mi serve un certificato medico', 'I need a sick note'],
    ['Dov\'è la farmacia?', 'Where is the pharmacy?'],
    ['È grave?', 'Is it serious?'],
    ['riposo', 'rest'],
    ['benda', 'bandage'],
    ['vaccino', 'vaccine'],
    ['dentista', 'dentist'],
    ['oculista', 'eye doctor'],
    ['Ho bisogno di un interprete', 'I need an interpreter'],
    ['Posso avere lo scontrino?', 'Can I get a receipt?'],
    ['emergenza', 'emergency'],
    ['Chiami un\'ambulanza', 'Call an ambulance'],
    ['Ho un\'assicurazione', 'I have insurance'],
    ['sintomi', 'symptoms'],
  ]);

  packs.doctor.byCategory["nl"] = buildEntries([
    ['arts', 'doctor'],
    ['ziekenhuis', 'hospital'],
    ['apotheek', 'pharmacy'],
    ['spoedeisende hulp', 'emergency room'],
    ['afspraak', 'appointment'],
    ['recept', 'prescription'],
    ['medicijn', 'medicine'],
    ['pijn', 'pain'],
    ['koorts', 'fever'],
    ['hoest', 'cough'],
    ['verkoudheid', 'cold (illness)'],
    ['hoofdpijn', 'headache'],
    ['buikpijn', 'stomach ache'],
    ['allergie', 'allergy'],
    ['bloeddruk', 'blood pressure'],
    ['verpleegkundige', 'nurse'],
    ['ambulance', 'ambulance'],
    ['zorgpas', 'insurance card'],
    ['Ik voel me ziek', 'I feel sick'],
    ['Ik heb een arts nodig', 'I need a doctor'],
    ['Het doet pijn hier', 'It hurts here'],
    ['Ik heb koorts', 'I have a fever'],
    ['Hoe lang heeft u dit al?', 'How long have you had this?'],
    ['Ik ben zwanger', 'I am pregnant'],
    ['Ik gebruik dit medicijn', 'I take this medicine'],
    ['Bent u ergens allergisch voor?', 'Are you allergic to anything?'],
    ['Ik heb een ziekmelding nodig', 'I need a sick note'],
    ['Waar is de apotheek?', 'Where is the pharmacy?'],
    ['Is het ernstig?', 'Is it serious?'],
    ['rust', 'rest'],
    ['verband', 'bandage'],
    ['vaccin', 'vaccine'],
    ['tandarts', 'dentist'],
    ['oogarts', 'eye doctor'],
    ['Ik heb een tolk nodig', 'I need an interpreter'],
    ['Kan ik een bonnetje krijgen?', 'Can I get a receipt?'],
    ['noodgeval', 'emergency'],
    ['Bel een ambulance', 'Call an ambulance'],
    ['Ik ben verzekerd', 'I have insurance'],
    ['symptomen', 'symptoms'],
  ]);

  packs.doctor.byCategory["pt"] = buildEntries([
    ['médico', 'doctor'],
    ['hospital', 'hospital'],
    ['farmácia', 'pharmacy'],
    ['pronto-socorro', 'emergency room'],
    ['consulta', 'appointment'],
    ['receita', 'prescription'],
    ['remédio', 'medicine'],
    ['dor', 'pain'],
    ['febre', 'fever'],
    ['tosse', 'cough'],
    ['resfriado', 'cold (illness)'],
    ['dor de cabeça', 'headache'],
    ['dor de barriga', 'stomach ache'],
    ['alergia', 'allergy'],
    ['pressão arterial', 'blood pressure'],
    ['enfermeiro', 'nurse'],
    ['ambulância', 'ambulance'],
    ['carteirinha do plano', 'insurance card'],
    ['Estou me sentindo mal', 'I feel sick'],
    ['Preciso de um médico', 'I need a doctor'],
    ['Dói aqui', 'It hurts here'],
    ['Estou com febre', 'I have a fever'],
    ['Há quanto tempo você tem isso?', 'How long have you had this?'],
    ['Estou grávida', 'I am pregnant'],
    ['Tomo este remédio', 'I take this medicine'],
    ['Você é alérgico a alguma coisa?', 'Are you allergic to anything?'],
    ['Preciso de um atestado', 'I need a sick note'],
    ['Onde fica a farmácia?', 'Where is the pharmacy?'],
    ['É grave?', 'Is it serious?'],
    ['repouso', 'rest'],
    ['curativo', 'bandage'],
    ['vacina', 'vaccine'],
    ['dentista', 'dentist'],
    ['oftalmo', 'eye doctor'],
    ['Preciso de um intérprete', 'I need an interpreter'],
    ['Posso ter um recibo?', 'Can I get a receipt?'],
    ['emergência', 'emergency'],
    ['Chame uma ambulância', 'Call an ambulance'],
    ['Tenho convênio', 'I have insurance'],
    ['sintomas', 'symptoms'],
  ]);

  packs.doctor.byCategory["pl"] = buildEntries([
    ['lekarz', 'doctor'],
    ['szpital', 'hospital'],
    ['apteka', 'pharmacy'],
    ['izba przyjęć', 'emergency room'],
    ['wizyta', 'appointment'],
    ['recepta', 'prescription'],
    ['lek', 'medicine'],
    ['ból', 'pain'],
    ['gorączka', 'fever'],
    ['kaszel', 'cough'],
    ['przeziębienie', 'cold (illness)'],
    ['ból głowy', 'headache'],
    ['ból brzucha', 'stomach ache'],
    ['alergia', 'allergy'],
    ['ciśnienie krwi', 'blood pressure'],
    ['pielęgniarka', 'nurse'],
    ['karetka', 'ambulance'],
    ['karta ubezpieczenia', 'insurance card'],
    ['Źle się czuję', 'I feel sick'],
    ['Potrzebuję lekarza', 'I need a doctor'],
    ['Boli mnie tutaj', 'It hurts here'],
    ['Mam gorączkę', 'I have a fever'],
    ['Od jak dawna pan to ma?', 'How long have you had this?'],
    ['Jestem w ciąży', 'I am pregnant'],
    ['Biorę ten lek', 'I take this medicine'],
    ['Czy ma pan na coś uczulenie?', 'Are you allergic to anything?'],
    ['Potrzebuję zwolnienia lekarskiego', 'I need a sick note'],
    ['Gdzie jest apteka?', 'Where is the pharmacy?'],
    ['Czy to poważne?', 'Is it serious?'],
    ['odpoczynek', 'rest'],
    ['bandaż', 'bandage'],
    ['szczepionka', 'vaccine'],
    ['dentysta', 'dentist'],
    ['okulista', 'eye doctor'],
    ['Potrzebuję tłumacza', 'I need an interpreter'],
    ['Czy mogę dostać paragon?', 'Can I get a receipt?'],
    ['nagły wypadek', 'emergency'],
    ['Wezwij karetkę', 'Call an ambulance'],
    ['Mam ubezpieczenie', 'I have insurance'],
    ['objawy', 'symptoms'],
  ]);

  packs.housing.byCategory["nb-bokmal"] = buildEntries([
    ['leilighet', 'apartment'],
    ['hus', 'house'],
    ['rom', 'room'],
    ['husleie', 'rent'],
    ['utleier', 'landlord'],
    ['leietaker', 'tenant'],
    ['depositum', 'deposit'],
    ['leiekontrakt', 'lease / contract'],
    ['nøkler', 'keys'],
    ['møbler', 'furniture'],
    ['møblert', 'furnished'],
    ['kjøkken', 'kitchen'],
    ['bad', 'bathroom'],
    ['soverom', 'bedroom'],
    ['stue', 'living room'],
    ['balkong', 'balcony'],
    ['heis', 'elevator'],
    ['varme', 'heating'],
    ['strøm', 'electricity'],
    ['internett', 'internet'],
    ['nabo', 'neighbor'],
    ['stille', 'quiet'],
    ['støyende', 'noisy'],
    ['ledig fra…', 'available from…'],
    ['Hvor høy er husleien?', 'How much is the rent?'],
    ['Er varme inkludert?', 'Is heating included?'],
    ['Jeg vil gjerne se leiligheten', 'I would like to view the apartment'],
    ['Når kan jeg flytte inn?', 'When can I move in?'],
    ['Vasken lekker', 'The sink is leaking'],
    ['Det er ikke varmt vann', 'There is no hot water'],
    ['Varmen fungerer ikke', 'The heating does not work'],
    ['Kan du fikse det?', 'Can you fix it?'],
    ['postkasse', 'mailbox'],
    ['parkeringsplass', 'parking space'],
    ['vaskerom', 'laundry room'],
    ['kollektiv', 'shared apartment'],
    ['fellesutgifter', 'utilities'],
    ['Jeg flytter ut', 'I am moving out'],
    ['adresse', 'address'],
    ['nabolag', 'neighborhood'],
  ]);

  packs.housing.byCategory["sv"] = buildEntries([
    ['lägenhet', 'apartment'],
    ['hus', 'house'],
    ['rum', 'room'],
    ['hyra', 'rent'],
    ['hyresvärd', 'landlord'],
    ['hyresgäst', 'tenant'],
    ['deposition', 'deposit'],
    ['hyreskontrakt', 'lease / contract'],
    ['nycklar', 'keys'],
    ['möbler', 'furniture'],
    ['möblerad', 'furnished'],
    ['kök', 'kitchen'],
    ['badrum', 'bathroom'],
    ['sovrum', 'bedroom'],
    ['vardagsrum', 'living room'],
    ['balkong', 'balcony'],
    ['hiss', 'elevator'],
    ['värme', 'heating'],
    ['el', 'electricity'],
    ['internet', 'internet'],
    ['granne', 'neighbor'],
    ['tyst', 'quiet'],
    ['högljudd', 'noisy'],
    ['ledig från…', 'available from…'],
    ['Hur mycket är hyran?', 'How much is the rent?'],
    ['Ingår värme?', 'Is heating included?'],
    ['Jag skulle vilja se lägenheten', 'I would like to view the apartment'],
    ['När kan jag flytta in?', 'When can I move in?'],
    ['Diskbänken läcker', 'The sink is leaking'],
    ['Det finns inget varmvatten', 'There is no hot water'],
    ['Värmen fungerar inte', 'The heating does not work'],
    ['Kan du laga det?', 'Can you fix it?'],
    ['brevlåda', 'mailbox'],
    ['parkeringsplats', 'parking space'],
    ['tvättstuga', 'laundry room'],
    ['korridor / delad lägenhet', 'shared apartment'],
    ['avgifter', 'utilities'],
    ['Jag flyttar ut', 'I am moving out'],
    ['adress', 'address'],
    ['område', 'neighborhood'],
  ]);

  packs.housing.byCategory["da"] = buildEntries([
    ['lejlighed', 'apartment'],
    ['hus', 'house'],
    ['værelse', 'room'],
    ['husleje', 'rent'],
    ['udlejer', 'landlord'],
    ['lejer', 'tenant'],
    ['depositum', 'deposit'],
    ['lejekontrakt', 'lease / contract'],
    ['nøgler', 'keys'],
    ['møbler', 'furniture'],
    ['møbleret', 'furnished'],
    ['køkken', 'kitchen'],
    ['badeværelse', 'bathroom'],
    ['soveværelse', 'bedroom'],
    ['stue', 'living room'],
    ['altan', 'balcony'],
    ['elevator', 'elevator'],
    ['varme', 'heating'],
    ['el', 'electricity'],
    ['internet', 'internet'],
    ['nabo', 'neighbor'],
    ['stille', 'quiet'],
    ['støjende', 'noisy'],
    ['ledig fra…', 'available from…'],
    ['Hvor høj er huslejen?', 'How much is the rent?'],
    ['Er varme inkluderet?', 'Is heating included?'],
    ['Jeg vil gerne se lejligheden', 'I would like to view the apartment'],
    ['Hvornår kan jeg flytte ind?', 'When can I move in?'],
    ['Vasken drypper', 'The sink is leaking'],
    ['Der er ikke varmt vand', 'There is no hot water'],
    ['Varmen virker ikke', 'The heating does not work'],
    ['Kan du ordne det?', 'Can you fix it?'],
    ['postkasse', 'mailbox'],
    ['parkeringsplads', 'parking space'],
    ['vaskerum', 'laundry room'],
    ['bofællesskab', 'shared apartment'],
    ['forbrug', 'utilities'],
    ['Jeg flytter ud', 'I am moving out'],
    ['adresse', 'address'],
    ['kvarter', 'neighborhood'],
  ]);

  packs.housing.byCategory["de"] = buildEntries([
    ['Wohnung', 'apartment'],
    ['Haus', 'house'],
    ['Zimmer', 'room'],
    ['Miete', 'rent'],
    ['Vermieter', 'landlord'],
    ['Mieter', 'tenant'],
    ['Kaution', 'deposit'],
    ['Mietvertrag', 'lease / contract'],
    ['Schlüssel', 'keys'],
    ['Möbel', 'furniture'],
    ['möbliert', 'furnished'],
    ['Küche', 'kitchen'],
    ['Badezimmer', 'bathroom'],
    ['Schlafzimmer', 'bedroom'],
    ['Wohnzimmer', 'living room'],
    ['Balkon', 'balcony'],
    ['Aufzug', 'elevator'],
    ['Heizung', 'heating'],
    ['Strom', 'electricity'],
    ['Internet', 'internet'],
    ['Nachbar', 'neighbor'],
    ['ruhig', 'quiet'],
    ['laut', 'noisy'],
    ['verfügbar ab…', 'available from…'],
    ['Wie hoch ist die Miete?', 'How much is the rent?'],
    ['Ist Heizung inklusive?', 'Is heating included?'],
    ['Ich möchte die Wohnung besichtigen', 'I would like to view the apartment'],
    ['Wann kann ich einziehen?', 'When can I move in?'],
    ['Das Spülbecken tropft', 'The sink is leaking'],
    ['Es gibt kein Warmwasser', 'There is no hot water'],
    ['Die Heizung funktioniert nicht', 'The heating does not work'],
    ['Können Sie das reparieren?', 'Can you fix it?'],
    ['Briefkasten', 'mailbox'],
    ['Parkplatz', 'parking space'],
    ['Waschküche', 'laundry room'],
    ['Wohngemeinschaft', 'shared apartment'],
    ['Nebenkosten', 'utilities'],
    ['Ich ziehe aus', 'I am moving out'],
    ['Adresse', 'address'],
    ['Viertel', 'neighborhood'],
  ]);

  packs.housing.byCategory["fr"] = buildEntries([
    ['appartement', 'apartment'],
    ['maison', 'house'],
    ['chambre', 'room'],
    ['loyer', 'rent'],
    ['propriétaire', 'landlord'],
    ['locataire', 'tenant'],
    ['caution', 'deposit'],
    ['bail', 'lease / contract'],
    ['clés', 'keys'],
    ['meubles', 'furniture'],
    ['meublé', 'furnished'],
    ['cuisine', 'kitchen'],
    ['salle de bain', 'bathroom'],
    ['chambre à coucher', 'bedroom'],
    ['salon', 'living room'],
    ['balcon', 'balcony'],
    ['ascenseur', 'elevator'],
    ['chauffage', 'heating'],
    ['électricité', 'electricity'],
    ['internet', 'internet'],
    ['voisin', 'neighbor'],
    ['calme', 'quiet'],
    ['bruyant', 'noisy'],
    ['disponible à partir de…', 'available from…'],
    ['Combien est le loyer ?', 'How much is the rent?'],
    ['Le chauffage est-il inclus ?', 'Is heating included?'],
    ['Je voudrais visiter l\'appartement', 'I would like to view the apartment'],
    ['Quand puis-je emménager ?', 'When can I move in?'],
    ['L\'évier fuit', 'The sink is leaking'],
    ['Il n\'y a pas d\'eau chaude', 'There is no hot water'],
    ['Le chauffage ne marche pas', 'The heating does not work'],
    ['Pouvez-vous le réparer ?', 'Can you fix it?'],
    ['boîte aux lettres', 'mailbox'],
    ['place de parking', 'parking space'],
    ['buanderie', 'laundry room'],
    ['colocation', 'shared apartment'],
    ['charges', 'utilities'],
    ['Je déménage', 'I am moving out'],
    ['adresse', 'address'],
    ['quartier', 'neighborhood'],
  ]);

  packs.housing.byCategory["es"] = buildEntries([
    ['piso', 'apartment'],
    ['casa', 'house'],
    ['habitación', 'room'],
    ['alquiler', 'rent'],
    ['casero', 'landlord'],
    ['inquilino', 'tenant'],
    ['fianza', 'deposit'],
    ['contrato de alquiler', 'lease / contract'],
    ['llaves', 'keys'],
    ['muebles', 'furniture'],
    ['amueblado', 'furnished'],
    ['cocina', 'kitchen'],
    ['baño', 'bathroom'],
    ['dormitorio', 'bedroom'],
    ['salón', 'living room'],
    ['balcón', 'balcony'],
    ['ascensor', 'elevator'],
    ['calefacción', 'heating'],
    ['electricidad', 'electricity'],
    ['internet', 'internet'],
    ['vecino', 'neighbor'],
    ['tranquilo', 'quiet'],
    ['ruidoso', 'noisy'],
    ['disponible desde…', 'available from…'],
    ['¿Cuánto es el alquiler?', 'How much is the rent?'],
    ['¿Está incluida la calefacción?', 'Is heating included?'],
    ['Me gustaría ver el piso', 'I would like to view the apartment'],
    ['¿Cuándo puedo mudarme?', 'When can I move in?'],
    ['El fregadero gotea', 'The sink is leaking'],
    ['No hay agua caliente', 'There is no hot water'],
    ['La calefacción no funciona', 'The heating does not work'],
    ['¿Puede arreglarlo?', 'Can you fix it?'],
    ['buzón', 'mailbox'],
    ['plaza de aparcamiento', 'parking space'],
    ['lavadero', 'laundry room'],
    ['piso compartido', 'shared apartment'],
    ['gastos de comunidad', 'utilities'],
    ['Me mudo', 'I am moving out'],
    ['dirección', 'address'],
    ['barrio', 'neighborhood'],
  ]);

  packs.housing.byCategory["it"] = buildEntries([
    ['appartamento', 'apartment'],
    ['casa', 'house'],
    ['stanza', 'room'],
    ['affitto', 'rent'],
    ['padrone di casa', 'landlord'],
    ['inquilino', 'tenant'],
    ['deposito', 'deposit'],
    ['contratto d\'affitto', 'lease / contract'],
    ['chiavi', 'keys'],
    ['mobili', 'furniture'],
    ['arredato', 'furnished'],
    ['cucina', 'kitchen'],
    ['bagno', 'bathroom'],
    ['camera da letto', 'bedroom'],
    ['soggiorno', 'living room'],
    ['balcone', 'balcony'],
    ['ascensore', 'elevator'],
    ['riscaldamento', 'heating'],
    ['elettricità', 'electricity'],
    ['internet', 'internet'],
    ['vicino', 'neighbor'],
    ['tranquillo', 'quiet'],
    ['rumoroso', 'noisy'],
    ['disponibile da…', 'available from…'],
    ['Quanto è l\'affitto?', 'How much is the rent?'],
    ['Il riscaldamento è incluso?', 'Is heating included?'],
    ['Vorrei vedere l\'appartamento', 'I would like to view the apartment'],
    ['Quando posso trasferirmi?', 'When can I move in?'],
    ['Il lavandino perde', 'The sink is leaking'],
    ['Non c\'è acqua calda', 'There is no hot water'],
    ['Il riscaldamento non funziona', 'The heating does not work'],
    ['Può ripararlo?', 'Can you fix it?'],
    ['cassetta della posta', 'mailbox'],
    ['posto auto', 'parking space'],
    ['lavanderia', 'laundry room'],
    ['appartamento condiviso', 'shared apartment'],
    ['spese', 'utilities'],
    ['Sto andando via', 'I am moving out'],
    ['indirizzo', 'address'],
    ['quartiere', 'neighborhood'],
  ]);

  packs.housing.byCategory["nl"] = buildEntries([
    ['appartement', 'apartment'],
    ['huis', 'house'],
    ['kamer', 'room'],
    ['huur', 'rent'],
    ['huisbaas', 'landlord'],
    ['huurder', 'tenant'],
    ['borg', 'deposit'],
    ['huurcontract', 'lease / contract'],
    ['sleutels', 'keys'],
    ['meubels', 'furniture'],
    ['gemeubileerd', 'furnished'],
    ['keuken', 'kitchen'],
    ['badkamer', 'bathroom'],
    ['slaapkamer', 'bedroom'],
    ['woonkamer', 'living room'],
    ['balkon', 'balcony'],
    ['lift', 'elevator'],
    ['verwarming', 'heating'],
    ['elektra', 'electricity'],
    ['internet', 'internet'],
    ['buur', 'neighbor'],
    ['rustig', 'quiet'],
    ['lawaaiig', 'noisy'],
    ['beschikbaar vanaf…', 'available from…'],
    ['Hoeveel is de huur?', 'How much is the rent?'],
    ['Is verwarming inbegrepen?', 'Is heating included?'],
    ['Ik wil de woning graag bekijken', 'I would like to view the apartment'],
    ['Wanneer kan ik intrekken?', 'When can I move in?'],
    ['De gootsteen lekt', 'The sink is leaking'],
    ['Er is geen warm water', 'There is no hot water'],
    ['De verwarming doet het niet', 'The heating does not work'],
    ['Kunt u het maken?', 'Can you fix it?'],
    ['brievenbus', 'mailbox'],
    ['parkeerplaats', 'parking space'],
    ['wasruimte', 'laundry room'],
    ['studentenhuis / gedeeld', 'shared apartment'],
    ['servicekosten', 'utilities'],
    ['Ik ga verhuizen', 'I am moving out'],
    ['adres', 'address'],
    ['buurt', 'neighborhood'],
  ]);

  packs.housing.byCategory["pt"] = buildEntries([
    ['apartamento', 'apartment'],
    ['casa', 'house'],
    ['quarto', 'room'],
    ['aluguel', 'rent'],
    ['senhorio', 'landlord'],
    ['inquilino', 'tenant'],
    ['caução', 'deposit'],
    ['contrato de aluguel', 'lease / contract'],
    ['chaves', 'keys'],
    ['móveis', 'furniture'],
    ['mobiliado', 'furnished'],
    ['cozinha', 'kitchen'],
    ['banheiro', 'bathroom'],
    ['quarto de dormir', 'bedroom'],
    ['sala', 'living room'],
    ['varanda', 'balcony'],
    ['elevador', 'elevator'],
    ['aquecimento', 'heating'],
    ['eletricidade', 'electricity'],
    ['internet', 'internet'],
    ['vizinho', 'neighbor'],
    ['tranquilo', 'quiet'],
    ['barulhento', 'noisy'],
    ['disponível a partir de…', 'available from…'],
    ['Quanto é o aluguel?', 'How much is the rent?'],
    ['O aquecimento está incluso?', 'Is heating included?'],
    ['Gostaria de ver o apartamento', 'I would like to view the apartment'],
    ['Quando posso me mudar?', 'When can I move in?'],
    ['A pia está vazando', 'The sink is leaking'],
    ['Não tem água quente', 'There is no hot water'],
    ['O aquecimento não funciona', 'The heating does not work'],
    ['Pode consertar?', 'Can you fix it?'],
    ['caixa de correio', 'mailbox'],
    ['vaga de estacionamento', 'parking space'],
    ['lavanderia', 'laundry room'],
    ['república', 'shared apartment'],
    ['condomínio', 'utilities'],
    ['Estou me mudando', 'I am moving out'],
    ['endereço', 'address'],
    ['bairro', 'neighborhood'],
  ]);

  packs.housing.byCategory["pl"] = buildEntries([
    ['mieszkanie', 'apartment'],
    ['dom', 'house'],
    ['pokój', 'room'],
    ['czynsz', 'rent'],
    ['wynajmujący', 'landlord'],
    ['najemca', 'tenant'],
    ['kaucja', 'deposit'],
    ['umowa najmu', 'lease / contract'],
    ['klucze', 'keys'],
    ['meble', 'furniture'],
    ['umeblowane', 'furnished'],
    ['kuchnia', 'kitchen'],
    ['łazienka', 'bathroom'],
    ['sypialnia', 'bedroom'],
    ['salon', 'living room'],
    ['balkon', 'balcony'],
    ['winda', 'elevator'],
    ['ogrzewanie', 'heating'],
    ['prąd', 'electricity'],
    ['internet', 'internet'],
    ['sąsiad', 'neighbor'],
    ['cichy', 'quiet'],
    ['głośny', 'noisy'],
    ['wolne od…', 'available from…'],
    ['Ile wynosi czynsz?', 'How much is the rent?'],
    ['Czy ogrzewanie jest wliczone?', 'Is heating included?'],
    ['Chciałbym obejrzeć mieszkanie', 'I would like to view the apartment'],
    ['Kiedy mogę się wprowadzić?', 'When can I move in?'],
    ['Zlew cieknie', 'The sink is leaking'],
    ['Nie ma ciepłej wody', 'There is no hot water'],
    ['Ogrzewanie nie działa', 'The heating does not work'],
    ['Czy może pan to naprawić?', 'Can you fix it?'],
    ['skrzynka na listy', 'mailbox'],
    ['miejsce parkingowe', 'parking space'],
    ['pralnia', 'laundry room'],
    ['mieszkanie współdzielone', 'shared apartment'],
    ['opłaty', 'utilities'],
    ['Wyprowadzam się', 'I am moving out'],
    ['adres', 'address'],
    ['okolica', 'neighborhood'],
  ]);

  root.THEMATIC_PACKS = packs;
  root.THEMATIC_PACK_LIST = Object.values(packs);
})(typeof window !== "undefined" ? window : globalThis);
