/**
 * Parallel reading texts for the Read tab.
 * Trail marks follow ski-run difficulty (green → double black).
 * Subtitles: short English labels only - no meta, no attribution fluff.
 *
 * ---------------------------------------------------------------------------
 * Read difficulty ladder (product law — desirable difficulty, not native lit)
 * ---------------------------------------------------------------------------
 * Stories are for L2 learning with tap-gloss, not pleasure reading alone.
 * Slightly challenging is good; beginner must never feel Expert is unreachable.
 *
 *   green-circle   Beginner      ~A1   Short turns (mostly 3–8 words). Present.
 *                                    Greetings, yes/no, simple where/what/want.
 *                                    High-frequency core only — almost no theme packs.
 *   blue-square    Intermediate  ~A2   Everyday scenes. Light connectors (men, hvis).
 *                                    Core ranks a bit deeper; light café/shop/social.
 *   black-diamond  Advanced      ~B1   Full situations (work, health, home). Past OK.
 *                                    Multi-clause lightly; theme words welcome.
 *   double-black   Expert        ~B1+  Opinion, plans, denser natural dialogue.
 *                                    Theme weave OK; still sounds like people.
 *
 * Norwegian is the template. Keep dialogue human — never a vocab dump.
 */
const READ_TRAIL_ORDER = [
  "green-circle",
  "blue-square",
  "black-diamond",
  "double-black-diamond",
];

const READ_TRAIL_LEVELS = {
  "green-circle": {
    id: "green-circle",
    label: "Beginner",
  },
  "blue-square": {
    id: "blue-square",
    label: "Intermediate",
  },
  "black-diamond": {
    id: "black-diamond",
    label: "Advanced",
  },
  "double-black-diamond": {
    id: "double-black-diamond",
    label: "Expert",
  },
};

function getReadTrailLevel(id) {
  if (id === "Starter") return READ_TRAIL_LEVELS["green-circle"];
  if (id === "blue-circle") return READ_TRAIL_LEVELS["blue-square"];
  return READ_TRAIL_LEVELS[id] || READ_TRAIL_LEVELS["green-circle"];
}

function sortStoriesByTrail(stories) {
  return [...stories].sort(
    (a, b) => READ_TRAIL_ORDER.indexOf(a.trail) - READ_TRAIL_ORDER.indexOf(b.trail)
  );
}

const READ_STORIES = [
  // ── Beginner (green): short, warm, high-frequency only ─────────────────
  {
    id: "nb-morgen",
    categoryId: "nb-bokmal",
    title: "God morgen",
    subtitle: "Good morning",
    trail: "green-circle",
    sentences: [
      { nb: "God morgen!", en: "Good morning!" },
      { nb: "Hei! Hvordan har du det?", en: "Hi! How are you?" },
      { nb: "Bra, takk. Og du?", en: "Good, thanks. And you?" },
      { nb: "Også bra. Det er fint vær i dag.", en: "Also good. The weather is nice today." },
      { nb: "Ja. Sol og ikke for kaldt.", en: "Yes. Sun and not too cold." },
      { nb: "Skal du til byen?", en: "Are you going into town?" },
      { nb: "Ja. Jeg skal kjøpe brød.", en: "Yes. I'm going to buy bread." },
      { nb: "Ha det bra!", en: "Bye! / Take care!" },
      { nb: "Ha det! Vi ses.", en: "Bye! See you." },
    ],
    glosses: {
      Han: "he",
      bor: "live / lives",
      også: "also / too",
      "God morgen": "Good morning",
      "Hvordan har du det": "How are you",
      Bra: "good / fine",
      vær: "weather",
      Sol: "sun",
      kaldt: "cold",
      byen: "the town / city",
      kjøpe: "to buy",
      brød: "bread",
      "Ha det bra": "goodbye / take care",
      "Vi ses": "see you",
      Hvordan: "how",
      morgen: "morning",
      Også: "also / too",
      takk: "thanks / thank you",
      dag: "day",
      "ha det": "goodbye",
      "i dag": "today",
      God: "good"
    },
  },
  {
    id: "nb-kaffe",
    categoryId: "nb-bokmal",
    title: "En kaffe, takk",
    subtitle: "A coffee, please",
    trail: "green-circle",
    sentences: [
      { nb: "Hei! Hva vil du ha?", en: "Hi! What would you like?" },
      { nb: "En kaffe, takk.", en: "A coffee, please." },
      { nb: "Med melk?", en: "With milk?" },
      { nb: "Nei, svart. Og vann, takk.", en: "No, black. And water, please." },
      { nb: "Vil du ha noe å spise?", en: "Would you like something to eat?" },
      { nb: "Bare kaffe i dag.", en: "Just coffee today." },
      { nb: "Det blir førti kroner.", en: "That's forty kroner." },
      { nb: "Hvor mye koster det?", en: "How much does it cost?" },
      { nb: "Jeg forstår ikke. Snakk saktere.", en: "I don't understand. Speak more slowly." },
      { nb: "Her er pengene. Takk!", en: "Here's the money. Thanks!" },
      { nb: "Takk skal du ha. Ha en fin dag!", en: "Thank you. Have a nice day!" },
    ],
    glosses: {
      koster: "costs",
      forstår: "understand",
      saktere: "more slowly",
      vil: "want / would like",
      kaffe: "coffee",
      melk: "milk",
      svart: "black",
      vann: "water",
      spise: "to eat",
      Bare: "just / only",
      førti: "forty",
      kroner: "kroner",
      pengene: "the money",
      "fin dag": "nice day",
      blir: "become / is (passive)",
      takk: "thanks / thank you",
      dag: "day",
      fin: "fine / nice",
      Hei: "hello / hi",
      "hvor mye koster det": "how much does it cost",
      "ha en fin dag": "have a nice day",
      "i dag": "today"
    },
  },
  {
    id: "nb-tog",
    categoryId: "nb-bokmal",
    title: "Hvor er toget?",
    subtitle: "Where is the train?",
    trail: "green-circle",
    sentences: [
      { nb: "Unnskyld. Hvor er toget?", en: "Excuse me. Where is the train?" },
      { nb: "Der borte. Spor to.", en: "Over there. Platform two." },
      { nb: "Takk. Går det snart?", en: "Thanks. Does it leave soon?" },
      { nb: "Ja, om ti minutter.", en: "Yes, in ten minutes." },
      { nb: "Trenger jeg billett nå?", en: "Do I need a ticket now?" },
      { nb: "Ja. Du kan kjøpe her.", en: "Yes. You can buy here." },
      { nb: "En billett til sentrum, takk.", en: "One ticket to the center, please." },
      { nb: "Kan du hjelpe meg?", en: "Can you help me?" },
      { nb: "En gang til, takk.", en: "Once more, please." },
      { nb: "Vær så god. Ha en fin tur!", en: "Here you are. Have a nice trip!" },
      { nb: "Tusen takk!", en: "Thank you so much!" },
    ],
    glosses: {
      hjelpe: "to help",
      "En gang til": "once more",
      Unnskyld: "excuse me",
      toget: "the train",
      "Der borte": "over there",
      Spor: "track / platform",
      snart: "soon",
      minutter: "minutes",
      Trenger: "need",
      billett: "ticket",
      kjøpe: "to buy",
      sentrum: "the center",
      "Vær så god": "here you are / you're welcome",
      tur: "trip",
      "Tusen takk": "thank you so much",
      borte: "away / gone",
      Hvor: "where",
      Takk: "thanks / thank you",
      "kan du hjelpe meg": "can you help me",
      "hvor er": "where is",
      gang: "time / occasion",
      fin: "fine / nice"
    },
  },

  // ── Intermediate (blue): everyday life, light connectors ───────────────
  {
    id: "nb-bibliotek",
    categoryId: "nb-bokmal",
    title: "På biblioteket",
    subtitle: "At the library",
    trail: "blue-square",
    sentences: [
      { nb: "Hei. Har dere bøker på engelsk?", en: "Hi. Do you have books in English?" },
      { nb: "Ja. De står der. Vil du låne noen?", en: "Yes. They're over there. Would you like to borrow some?" },
      { nb: "Ja, gjerne. Trenger jeg studentbevis?", en: "Yes, please. Do I need a student ID?" },
      { nb: "Ja. Du kan få det i dag hvis du har ID.", en: "Yes. You can get it today if you have ID." },
      { nb: "Fint. Hvor lenge kan jeg ha bøkene?", en: "Great. How long can I keep the books?" },
      { nb: "Tre uker. Du kan forlenge på nettet.", en: "Three weeks. You can renew online." },
      { nb: "Er det stille her om kvelden?", en: "Is it quiet here in the evening?" },
      { nb: "Ja, etter seks. Da er det fint å lese pensum.", en: "Yes, after six. Then it's nice to read the syllabus." },
      { nb: "Unnskyld, hvor er toalettet?", en: "Excuse me, where is the toilet?" },
      { nb: "Har dere åpent i morgen?", en: "Are you open tomorrow?" },
      { nb: "Takk for hjelpen!", en: "Thanks for the help!" },
      { nb: "Bare hyggelig. Lykke til med emnet!", en: "You're welcome. Good luck with the course!" },
    ],
    glosses: {
      toalettet: "the toilet",
      åpent: "open",
      Unnskyld: "excuse me",
      "i morgen": "tomorrow",
      bøker: "books",
      engelsk: "English",
      låne: "to borrow",
      gjerne: "gladly / please",
      studentbevis: "student ID",
      ID: "ID",
      lenge: "long",
      uker: "weeks",
      forlenge: "to renew / extend",
      nettet: "the internet / online",
      stille: "quiet",
      kvelden: "the evening",
      lese: "to read",
      pensum: "syllabus / reading list",
      hjelpen: "the help",
      "Bare hyggelig": "you're welcome",
      emnet: "the course / subject",
      "hvor er toalettet": "where is the toilet",
      "takk for hjelpen": "thanks for the help",
      "lykke til": "good luck",
      "hvor er": "where is",
      "i dag": "today"
    },
  },
  {
    id: "nb-marked",
    categoryId: "nb-bokmal",
    title: "I butikken",
    subtitle: "At the shop",
    trail: "blue-square",
    sentences: [
      { nb: "Hei. Hvor er brødet?", en: "Hi. Where is the bread?" },
      { nb: "Rett fram, til venstre.", en: "Straight ahead, to the left." },
      { nb: "Takk. Hva koster eplene?", en: "Thanks. How much are the apples?" },
      { nb: "Tjue kroner kiloen. De er på tilbud i dag.", en: "Twenty kroner a kilo. They're on sale today." },
      { nb: "Jeg tar fire epler og et brød.", en: "I'll take four apples and a loaf of bread." },
      { nb: "Vil du ha handlepose?", en: "Would you like a shopping bag?" },
      { nb: "Ja, takk. Kan jeg betale med kort?", en: "Yes, please. Can I pay by card?" },
      { nb: "Selvfølgelig. Det blir sekstifem kroner i kassen.", en: "Of course. That's sixty-five kroner at the checkout." },
      { nb: "Kan jeg få kvittering?", en: "Can I get a receipt?" },
      { nb: "Har dere noe billigere?", en: "Do you have something cheaper?" },
      { nb: "Her er kortet. Ha en fin dag!", en: "Here's the card. Have a nice day!" },
      { nb: "I like måte. Velkommen igjen!", en: "Same to you. Welcome back anytime!" },
    ],
    glosses: {
      kvittering: "receipt",
      billigere: "cheaper",
      brødet: "the bread",
      "Rett fram": "straight ahead",
      "til venstre": "to the left",
      koster: "costs",
      eplene: "the apples",
      Tjue: "twenty",
      kiloen: "per kilo",
      tilbud: "sale / special offer",
      tar: "take / will take",
      handlepose: "shopping bag",
      betale: "to pay",
      kort: "card",
      Selvfølgelig: "of course",
      sekstifem: "sixty-five",
      kassen: "the checkout",
      "I like måte": "same to you",
      "Velkommen igjen": "welcome again",
      "ha en fin dag": "have a nice day",
      "hvor er": "where is",
      "i dag": "today"
    },
  },
  {
    id: "nb-venner",
    categoryId: "nb-bokmal",
    title: "Nye venner",
    subtitle: "New friends",
    trail: "blue-square",
    sentences: [
      { nb: "Hei, jeg heter Sam.", en: "Hi, my name is Sam." },
      { nb: "Hyggelig å se deg! Jeg er Noor.", en: "Nice to see you! I'm Noor." },
      { nb: "Hvor kommer du fra?", en: "Where are you from?" },
      { nb: "Fra Canada, men jeg bor her nå.", en: "From Canada, but I live here now." },
      { nb: "Hva studerer du?", en: "What do you study?" },
      { nb: "Biologi. Og du?", en: "Biology. And you?" },
      { nb: "Jeg jobber på kafé. Har du planer i helgen?", en: "I work at a café. Do you have plans this weekend?" },
      { nb: "Ikke ennå. Er du ledig på lørdag?", en: "Not yet. Are you free on Saturday?" },
      { nb: "Hva er nummeret ditt?", en: "What's your number?" },
      { nb: "Vi ses i morgen!", en: "See you tomorrow!" },
      { nb: "Gjerne kaffe! Vi kan møtes her klokka to.", en: "Coffee sounds good! We can meet here at two o'clock." },
      { nb: "Supert. Vi ses snart!", en: "Great. See you soon!" },
    ],
    glosses: {
      nummeret: "the number",
      ditt: "your",
      "i morgen": "tomorrow",
      heter: "am called / my name is",
      "Hyggelig å se deg": "nice to see you",
      kommer: "come",
      bor: "live",
      studerer: "study",
      jobber: "work",
      kafé: "café",
      planer: "plans",
      helgen: "the weekend",
      "Ikke ennå": "not yet",
      "Er du ledig": "are you free",
      lørdag: "Saturday",
      møtes: "meet (each other)",
      klokka: "o'clock / the clock",
      "Vi ses snart": "see you soon",
      Biologi: "biology",
      "jeg bor her": "I live here",
      "jeg heter": "my name is / I am called",
      morgen: "morning"
    },
  },

  // ── Advanced (black): full situations, past OK, theme welcome ──────────
  {
    id: "nb-jobb",
    categoryId: "nb-bokmal",
    title: "Første dag på jobb",
    subtitle: "First day at work",
    trail: "black-diamond",
    sentences: [
      { nb: "Velkommen til teamet, Sam.", en: "Welcome to the team, Sam." },
      { nb: "Takk. Jeg er litt nervøs.", en: "Thanks. I'm a bit nervous." },
      { nb: "Det er vanlig. Her er pulten din ved vinduet.", en: "That's normal. Here's your desk by the window." },
      { nb: "Flott. Hvem er sjefen min?", en: "Great. Who is my boss?" },
      { nb: "Det er jeg i dag. Passordet får du av en medarbeider.", en: "That's me today. You'll get the password from a coworker." },
      { nb: "Når er lunsj, og er det fulltid?", en: "When is lunch, and is it full-time?" },
      { nb: "Lunsj klokka tolv. Agendaen ligger i møterommet.", en: "Lunch at twelve. The agenda is in the meeting room." },
      { nb: "Kan jeg ha hjemmekontor noen dager senere?", en: "Can I work from home some days later?" },
      { nb: "Etter prøvetiden, hvis det går bra.", en: "After the trial period, if things go well." },
      { nb: "Hva er wifi-passordet?", en: "What's the Wi‑Fi password?" },
      { nb: "Hvem kan jeg spørre hvis jeg trenger hjelp?", en: "Who can I ask if I need help?" },
      { nb: "Forstått. Takk for hjelpen!", en: "Understood. Thanks for the help!" },
      { nb: "Bare spør. Lykke til med prosjektet!", en: "Just ask. Good luck with the project!" },
    ],
    glosses: {
      "wifi-passordet": "the Wi‑Fi password",
      Hvem: "who",
      spørre: "to ask",
      trenger: "need",
      teamet: "the team",
      nervøs: "nervous",
      vanlig: "normal / common",
      pulten: "the desk",
      sjefen: "the boss",
      Passordet: "the password",
      medarbeider: "coworker / colleague",
      lunsj: "lunch",
      fulltid: "full-time",
      Agendaen: "the agenda",
      møterommet: "the meeting room",
      hjemmekontor: "home office / remote work",
      prøvetiden: "the trial period",
      Forstått: "understood",
      prosjektet: "the project",
      Velkommen: "welcome",
      "takk for hjelpen": "thanks for the help",
      "lykke til": "good luck",
      "i dag": "today"
    },
  },
  {
    id: "nb-lege",
    categoryId: "nb-bokmal",
    title: "Hos legen",
    subtitle: "At the doctor's",
    trail: "black-diamond",
    sentences: [
      { nb: "God dag. Hva er det som er galt?", en: "Good day. What's the matter?" },
      { nb: "Jeg har hatt vondt i halsen i to dager.", en: "I've had a sore throat for two days." },
      { nb: "Har du feber eller hoste også?", en: "Do you have a fever or a cough as well?" },
      { nb: "Litt feber i morges, og litt hoste.", en: "A little fever this morning, and a bit of a cough." },
      { nb: "Si aaa. Det ser ut som en mild forkjølelse.", en: "Say ah. It looks like a mild cold." },
      { nb: "Trenger jeg resept på medisin?", en: "Do I need a prescription for medicine?" },
      { nb: "Ikke ennå. Hvile, vann og paracetamol.", en: "Not yet. Rest, water, and paracetamol." },
      { nb: "Kan jeg få sykmelding hvis det blir verre?", en: "Can I get a sick note if it gets worse?" },
      { nb: "Ja. Book ny legetime da, eller ring.", en: "Yes. Book a new appointment then, or call." },
      { nb: "Jeg er allergisk mot penicillin.", en: "I'm allergic to penicillin." },
      { nb: "Hvor ofte skal jeg ta det?", en: "How often should I take it?" },
      { nb: "Tusen takk for hjelpen.", en: "Thank you so much for the help." },
      { nb: "Bare hyggelig. Bli frisk snart!", en: "You're welcome. Get well soon!" },
    ],
    glosses: {
      allergisk: "allergic",
      penicillin: "penicillin",
      ofte: "often",
      galt: "wrong / the matter",
      "vondt i halsen": "sore throat",
      dager: "days",
      feber: "fever",
      hoste: "cough",
      morges: "this morning",
      mild: "mild",
      forkjølelse: "cold (illness)",
      resept: "prescription",
      medisin: "medicine",
      Hvile: "rest",
      paracetamol: "paracetamol / acetaminophen",
      sykmelding: "sick note",
      verre: "worse",
      legetime: "doctor's appointment",
      frisk: "well / healthy",
      "takk for hjelpen": "thanks for the help",
      Trenger: "need",
      halsen: "the throat"
    },
  },
  {
    id: "nb-bolig",
    categoryId: "nb-bokmal",
    title: "Leter etter et rom",
    subtitle: "Looking for a room",
    trail: "black-diamond",
    sentences: [
      { nb: "Hei, jeg ringer om rommet på nettet.", en: "Hi, I'm calling about the room online." },
      { nb: "Ja, det er fortsatt ledig. Når vil du se det?", en: "Yes, it's still free. When would you like to see it?" },
      { nb: "I ettermiddag, rundt tre, hvis det går.", en: "This afternoon, around three, if that works." },
      { nb: "Fint. Det er tredje etasje, ingen heis.", en: "Fine. It's the third floor, no elevator." },
      { nb: "Er det et kollektiv, og hva er husleien?", en: "Is it a shared flat, and what's the rent?" },
      { nb: "Ja. Husleien inkluderer internett. Depositum er en måned.", en: "Yes. Rent includes internet. Deposit is one month." },
      { nb: "Når får jeg nøkler hvis jeg tar det?", en: "When do I get keys if I take it?" },
      { nb: "Utleier møter deg med leiekontrakten ved postkassen.", en: "The landlord will meet you with the lease at the mailbox." },
      { nb: "Når kan jeg flytte inn?", en: "When can I move in?" },
      { nb: "Er strøm inkludert i leien?", en: "Is electricity included in the rent?" },
      { nb: "Høres bra ut. Jeg kommer klokka tre.", en: "Sounds good. I'll come at three o'clock." },
      { nb: "Supert. Ring hvis naboen klager over støy!", en: "Great. Call if the neighbor complains about noise!" },
    ],
    glosses: {
      flytte: "to move",
      inn: "in",
      strøm: "electricity",
      inkludert: "included",
      ringer: "am calling",
      rommet: "the room",
      ledig: "available / free",
      ettermiddag: "afternoon",
      etasje: "floor",
      heis: "elevator",
      kollektiv: "shared flat",
      husleien: "the rent",
      inkluderer: "includes",
      Depositum: "deposit",
      nøkler: "keys",
      Utleier: "landlord",
      leiekontrakten: "the lease",
      postkassen: "the mailbox",
      naboen: "the neighbor",
      støy: "noise",
      internett: "internet",
      kommer: "comes / is coming"
    },
  },

  // ── Expert (double black): denser, opinion, plans, theme weave ─────────
  {
    id: "nb-ferge",
    categoryId: "nb-bokmal",
    title: "Fergen går ikke",
    subtitle: "The ferry is cancelled",
    trail: "double-black-diamond",
    sentences: [
      { nb: "Har du sjekket rutetabellen i dag?", en: "Have you checked the timetable today?" },
      { nb: "Ja. Fergen til øya er innstilt på grunn av storm.", en: "Yes. The ferry to the island is cancelled because of the storm." },
      { nb: "Så vi sitter fast her til i morgen?", en: "So we're stuck here until tomorrow?" },
      { nb: "Ikke nødvendigvis. Det går en buss langs kysten klokka fire.", en: "Not necessarily. There's a bus along the coast at four." },
      { nb: "Tar den oss helt til kaien?", en: "Does it take us all the way to the quay?" },
      { nb: "Nesten. Så går det en liten båt hvis bølgene roer seg.", en: "Almost. Then a small boat runs if the waves calm down." },
      { nb: "Skal vi booke billetter nå, eller vente?", en: "Should we book tickets now, or wait?" },
      { nb: "Nå. Køen blir lang hvis flere hører det samme.", en: "Now. The queue will be long if more people hear the same thing." },
      { nb: "Hvor er bussholdeplassen fra hotellet?", en: "Where is the bus stop from the hotel?" },
      { nb: "Ti minutter til fots, rett forbi butikken.", en: "Ten minutes on foot, straight past the shop." },
      { nb: "Greit. Jeg tar sekkene, du sjekker appen.", en: "Alright. I'll take the bags, you check the app." },
      { nb: "Vi snakkes når bussen er bekreftet.", en: "We'll talk when the bus is confirmed." },
    ],
    glosses: {
      rutetabellen: "the timetable",
      Fergen: "the ferry",
      innstilt: "cancelled",
      storm: "storm",
      øya: "the island",
      kysten: "the coast",
      kaien: "the quay",
      bølgene: "the waves",
      booke: "to book",
      Køen: "the queue",
      bussholdeplassen: "the bus stop",
      bekreftet: "confirmed",
      sekkene: "the bags",
      "i morgen": "tomorrow",
      "hvor er": "where is",
      "i dag": "today",
      minutter: "minutes",
      snakkes: "talk (to each other)",
      morgen: "morning",
      eller: "or",
      forbi: "past / by",
      Greit: "okay / fine / alright"
    },
  },
  {
    id: "nb-hytte",
    categoryId: "nb-bokmal",
    title: "Hytta før vinteren",
    subtitle: "The cabin before winter",
    trail: "double-black-diamond",
    sentences: [
      { nb: "Vi må stenge hytta før frosten kommer.", en: "We have to close the cabin before the frost comes." },
      { nb: "Jeg kan tømme vannet i rørene på lørdag.", en: "I can drain the water in the pipes on Saturday." },
      { nb: "Flott. Hvem tar ut søpla og låser vedskjulet?", en: "Great. Who takes out the trash and locks the woodshed?" },
      { nb: "Det kan jeg gjøre, hvis du sjekker taket for løv.", en: "I can do that, if you check the roof for leaves." },
      { nb: "Taket ser greit ut. Men nøkkelen til boden mangler.", en: "The roof looks fine. But the key to the shed is missing." },
      { nb: "Den ligger i skuffen under stearinlysene.", en: "It's in the drawer under the candles." },
      { nb: "Skal vi invitere naboene til en siste kaffe?", en: "Should we invite the neighbors for a last coffee?" },
      { nb: "Gjerne. De passet på hunden da vi var borte.", en: "Gladly. They looked after the dog while we were away." },
      { nb: "Når kjører du oppover?", en: "When are you driving up?" },
      { nb: "Fredag ettermiddag, hvis det ikke snør for hardt.", en: "Friday afternoon, if it doesn't snow too hard." },
      { nb: "Send melding når du er framme.", en: "Send a message when you arrive." },
      { nb: "Det gjør jeg. Så sees vi ved peisen.", en: "I will. Then we'll see each other by the fireplace." },
    ],
    glosses: {
      Hytta: "the cabin",
      stenge: "to close / shut",
      frosten: "the frost",
      tømme: "to empty / drain",
      rørene: "the pipes",
      søpla: "the trash",
      vedskjulet: "the woodshed",
      boden: "the shed",
      stearinlysene: "the candles",
      "passet på": "looked after",
      snør: "snows",
      peisen: "the fireplace",
      oppover: "up (the road / inland)",
      ettermiddag: "afternoon",
      nøkkelen: "the key",
      Fredag: "Friday",
      kommer: "comes / is coming",
      vannet: "the water",
      borte: "away / gone",
      Flott: "great / lovely",
      gjøre: "to do",
      greit: "okay / fine / alright"
    },
  },
  {
    id: "nb-nordlys",
    categoryId: "nb-bokmal",
    title: "Nordlys i Tromsø",
    subtitle: "Northern lights in Tromsø",
    trail: "double-black-diamond",
    sentences: [
      { nb: "Vil du bli med til Tromsø i helga?", en: "Do you want to come to Tromsø this weekend?" },
      { nb: "For nordlyset? Er det realistisk nå?", en: "For the northern lights? Is that realistic now?" },
      { nb: "Værmeldingen lover klar himmel to netter.", en: "The forecast promises clear sky two nights." },
      { nb: "Jeg har bare en gammel dunjakke.", en: "I only have an old down jacket." },
      { nb: "Lån den tykke fra meg. Og ta ullundertøy.", en: "Borrow the thick one from me. And bring wool base layers." },
      { nb: "Hvor overnatter vi? Hotell er dyrt midt i sesongen.", en: "Where do we stay? Hotels are expensive mid-season." },
      { nb: "Jeg fant en enkel Airbnb nær sentrum.", en: "I found a simple Airbnb near the centre." },
      { nb: "Kan vi ta nattbussen fra Oslo for å spare?", en: "Can we take the night bus from Oslo to save money?" },
      { nb: "Fly er raskere, men bussen er halv pris.", en: "Flying is faster, but the bus is half price." },
      { nb: "Da tar jeg bussen. Du flyr, så møtes vi der.", en: "Then I'll take the bus. You fly, and we meet there." },
      { nb: "Avtalt. Si ifra når du lander.", en: "Agreed. Let me know when you land." },
      { nb: "Og du melder hvis nordlyset kommer tidlig.", en: "And you report if the lights come early." },
    ],
    glosses: {
      nordlyset: "the northern lights",
      realistisk: "realistic",
      Værmeldingen: "the weather forecast",
      himmel: "sky",
      dunjakke: "down jacket",
      ullundertøy: "wool underwear / base layers",
      overnatter: "stay overnight",
      sesongen: "the season",
      nattbussen: "the night bus",
      "halv pris": "half price",
      Avtalt: "agreed",
      lander: "land",
      sentrum: "downtown / city center",
      gammel: "old",
      kommer: "comes / is coming",
      enkel: "simple / easy",
      møtes: "meet (each other)",
      bare: "only / just",
      fant: "found",
      halv: "half",
      hvis: "if",
      Hvor: "where"
    },
  },
];
