/**
 * Parallel reading texts for the Read tab.
 * Trail marks follow ski-run difficulty (green → double black).
 * Subtitles: short English labels only - no meta, no attribution fluff.
 *
 * Norwegian story pass: natural dialogue first; weave high-frequency core
 * and next-tier theme forms (airport, transit, dining, health, home, campus,
 * work, shopping, social, money) so Read serves the 1,200 teachable set
 * without sounding like a word list.
 */
const READ_TRAIL_ORDER = [
  "green-circle",
  "blue-square",
  "black-diamond",
  "double-black-diamond",
];

const READ_TRAIL_LEVELS = {
  "green-circle": {
    id: "green-circle",
    label: "Beginner",
  },
  "blue-square": {
    id: "blue-square",
    label: "Intermediate",
  },
  "black-diamond": {
    id: "black-diamond",
    label: "Advanced",
  },
  "double-black-diamond": {
    id: "double-black-diamond",
    label: "Expert",
  },
};

function getReadTrailLevel(id) {
  if (id === "Starter") return READ_TRAIL_LEVELS["green-circle"];
  if (id === "blue-circle") return READ_TRAIL_LEVELS["blue-square"];
  return READ_TRAIL_LEVELS[id] || READ_TRAIL_LEVELS["green-circle"];
}

function sortStoriesByTrail(stories) {
  return [...stories].sort(
    (a, b) => READ_TRAIL_ORDER.indexOf(a.trail) - READ_TRAIL_ORDER.indexOf(b.trail)
  );
}

const READ_STORIES = [
  {
    id: "nb-morgen",
    categoryId: "nb-bokmal",
    title: "Morgen i byen",
    subtitle: "Morning in the city",
    trail: "green-circle",
    sentences: [
      { nb: "God morgen!", en: "Good morning!" },
      { nb: "Hei. Jeg har nettopp kommet frem.", en: "Hi. I just arrived." },
      { nb: "Det er kaldt, men sola skinner.", en: "It's cold, but the sun is shining." },
      { nb: "Jeg tar bysykkel langs gågata.", en: "I'm taking a city bike along the pedestrian street." },
      { nb: "Unnskyld, hvor er holdeplassen for trikken?", en: "Excuse me, where is the tram stop?" },
      { nb: "Rett fram, over fortauet ved veikrysset.", en: "Straight ahead, across the sidewalk by the intersection." },
      { nb: "Takk. Går det en rute til sentrum nå?", en: "Thanks. Is there a route into the center now?" },
      { nb: "Ja. Se på rutetabellen, eller ta taxi hvis du har hastverk.", en: "Yes. Check the timetable, or take a taxi if you're in a hurry." },
      { nb: "Tusen takk. Ha en fin dag!", en: "Thank you so much. Have a nice day!" },
      { nb: "Ikke noe problem. Lykke til!", en: "No problem. Good luck!" },
    ],
    glosses: {
      nettopp: "just (recently)",
      "kommet frem": "arrived",
      sola: "the sun",
      skinner: "is shining",
      bysykkel: "city bike",
      gågata: "the pedestrian street",
      holdeplassen: "the (bus/tram) stop",
      trikken: "the tram",
      "rett fram": "straight ahead",
      fortauet: "the sidewalk",
      veikrysset: "the intersection",
      rute: "route",
      sentrum: "the city center",
      rutetabellen: "the timetable",
      taxi: "taxi",
      hastverk: "a hurry",
      "lykke til": "good luck",
    },
  },
  {
    id: "nb-kaffe",
    categoryId: "nb-bokmal",
    title: "En kaffe, takk",
    subtitle: "Ordering coffee",
    trail: "green-circle",
    sentences: [
      { nb: "Hei! Er det ledig her i kafeen?", en: "Hi! Is there a free table here in the café?" },
      { nb: "Ja. Vil du se på menyen?", en: "Yes. Would you like to look at the menu?" },
      { nb: "En kaffe, takk. Uten melk.", en: "One coffee, please. Without milk." },
      { nb: "Vil du bestille frokost også? Vi har te, juice og ostesmørbrød.", en: "Would you also like to order breakfast? We have tea, juice, and cheese sandwiches." },
      { nb: "Hva anbefaler du?", en: "What do you recommend?" },
      { nb: "Vegetarisk suppe er god i dag. Dessert senere hvis du vil.", en: "The vegetarian soup is good today. Dessert later if you want." },
      { nb: "Et ostesmørbrød, takk. Er det krydret?", en: "A cheese sandwich, please. Is it spicy?" },
      { nb: "Nei, mildt. Vi er åpne til tre. Takeaway går fint hvis du har hastverk.", en: "No, mild. We're open until three. Takeaway is fine if you're in a hurry." },
      { nb: "Kan jeg få regningen nå? Tips er greit her, ikke sant?", en: "Can I get the bill now? Tipping is fine here, right?" },
      { nb: "Ja. Det blir førtifem kroner. Ha en fin dag!", en: "Yes. That's forty-five kroner. Have a nice day!" },
    ],
    glosses: {
      ledig: "free / available",
      kafeen: "the café",
      menyen: "the menu",
      "uten melk": "without milk",
      bestille: "to order",
      frokost: "breakfast",
      te: "tea",
      juice: "juice",
      "Hva anbefaler du?": "What do you recommend?",
      vegetarisk: "vegetarian",
      ostesmørbrød: "cheese sandwich",
      dessert: "dessert",
      krydret: "spicy",
      mildt: "mild",
      takeaway: "takeaway",
      hastverk: "a hurry",
      regningen: "the bill",
      tips: "tip (gratuity)",
      førtifem: "forty-five",
      kroner: "kroner (currency)",
    },
  },
  {
    id: "nb-tog",
    categoryId: "nb-bokmal",
    title: "På toget",
    subtitle: "On the train",
    trail: "green-circle",
    sentences: [
      { nb: "Går dette toget til Oslo?", en: "Does this train go to Oslo?" },
      { nb: "Ja, det stemmer. Spor fire. Neste avgang om ti minutter.", en: "Yes, that's right. Track four. Next departure in ten minutes." },
      { nb: "Hvor kjøper jeg billett? Går det an med månedskort?", en: "Where do I buy a ticket? Can I use a monthly pass?" },
      { nb: "I appen eller i billettautomaten. Ellers er enveisbillett greit.", en: "In the app or at the ticket machine. Otherwise a one-way ticket is fine." },
      { nb: "Enveisbillett, takk. Vindu, gjerne. Hvilken sone er det?", en: "One-way ticket, please. A window seat, if possible. Which zone is it?" },
      { nb: "Sone en til tre. Det er litt forsinkelse i rushtiden.", en: "Zones one to three. There's a bit of a delay in rush hour." },
      { nb: "Hvor lang tid tar det da? Jeg må rekke en overgang.", en: "How long does it take then? I need to make a transfer." },
      { nb: "Omtrent to timer. Endestasjonen er Oslo S.", en: "About two hours. The last stop is Oslo Central." },
      { nb: "Fint. Er det parkeringsplass ved stasjonen hvis jeg kommer med bil neste gang?", en: "Good. Is there parking at the station if I come by car next time?" },
      { nb: "Ja, men det koster. Ha en fin tur!", en: "Yes, but it costs. Have a nice trip!" },
    ],
    glosses: {
      stemmer: "that's right / correct",
      spor: "track / platform number",
      avgang: "departure",
      billett: "ticket",
      "går det an": "is it possible / can one",
      månedskort: "monthly pass",
      billettautomaten: "the ticket machine",
      enveisbillett: "one-way ticket",
      sone: "zone (fare)",
      forsinkelse: "delay",
      rushtiden: "rush hour",
      overgang: "transfer (between lines)",
      omtrent: "about / approximately",
      endestasjonen: "the last stop / terminus",
      parkeringsplass: "parking space",
    },
  },
  {
    id: "nb-bibliotek",
    categoryId: "nb-bokmal",
    title: "På biblioteket",
    subtitle: "At the library",
    trail: "blue-square",
    sentences: [
      { nb: "Hei, jeg leter etter et stille sted å studere.", en: "Hi, I'm looking for a quiet place to study." },
      { nb: "Oppe er det ledige bord ved vinduet. Klasserommet er opptatt, og labben også.", en: "Upstairs there are free tables by the window. The classroom is busy, and the lab too." },
      { nb: "Hvor lenge har dere åpent?", en: "How late are you open?" },
      { nb: "Til klokka ni i kveld. Auditoriet stenger tidligere.", en: "Until nine this evening. The lecture hall closes earlier." },
      { nb: "Kan jeg låne bøker med studentbevis? Jeg bor i studentbolig like ved.", en: "Can I borrow books with a student ID? I live in student housing nearby." },
      { nb: "Ja. Trenger du noe fra pensumlista til emnet ditt?", en: "Yes. Do you need anything from the reading list for your course?" },
      { nb: "Kanskje senere. Jeg har gruppearbeid med en medstudent først. Kan du gjenta det?", en: "Maybe later. I have group work with a classmate first. Could you repeat that?" },
      { nb: "Husk å notere. Kontortid hos læreren er i morgen. Oppmelding til lab er online.", en: "Remember to take notes. The teacher's office hours are tomorrow. Lab enrollment is online." },
      { nb: "Takk. Jeg håper jeg skal bestå eksamen. Masteroppgaven kommer senere.", en: "Thanks. I hope I'll pass the exam. The master's thesis comes later." },
      { nb: "Lykke til med eksamen neste uke!", en: "Good luck with the exam next week!" },
    ],
    glosses: {
      leter: "looking for",
      stille: "quiet",
      studere: "to study",
      ledige: "free / available",
      klasserommet: "the classroom",
      opptatt: "busy / occupied",
      labben: "the lab",
      auditoriet: "the lecture hall",
      studentbevis: "student ID",
      studentbolig: "student housing",
      pensumlista: "the reading list",
      emnet: "the course / subject",
      gruppearbeid: "group work",
      medstudent: "classmate",
      "Kan du gjenta det?": "Could you repeat that?",
      notere: "to take notes",
      kontortid: "office hours",
      læreren: "the teacher",
      oppmelding: "enrollment",
      bestå: "to pass (an exam)",
      eksamen: "exam",
      masteroppgaven: "the master's thesis",
    },
  },
  {
    id: "nb-marked",
    categoryId: "nb-bokmal",
    title: "På markedet",
    subtitle: "At the market",
    trail: "blue-square",
    sentences: [
      { nb: "Hei. Er det tilbud i matbutikken i dag?", en: "Hi. Is there a deal at the supermarket today?" },
      { nb: "Ja, grønnsaker er billige. Kylling er på salg også.", en: "Yes, vegetables are cheap. Chicken is on sale too." },
      { nb: "Hva koster den osten?", en: "How much is that cheese?" },
      { nb: "Tretti kroner stykket. Vil du ha en handlepose?", en: "Thirty kroner each. Would you like a shopping bag?" },
      { nb: "Ja, gjerne. Jeg tar to oster og fire epler.", en: "Yes, please. I'll take two cheeses and four apples." },
      { nb: "Handlevogna er der borte hvis du trenger mer. Åpningstidene står på døra.", en: "The shopping cart is over there if you need more. Opening hours are on the door." },
      { nb: "Takk. Kan jeg betale med debetkort i kassen, eller kredittkort?", en: "Thanks. Can I pay with a debit card at the checkout, or a credit card?" },
      { nb: "Begge deler. Vi er nesten kontantløse. Her er vekslepenger hvis du trenger det.", en: "Either. We're almost cashless. Here's change if you need it." },
      { nb: "Supert. Jeg leter også etter en gave. Denne genseren er for stor. Har dere en annen størrelse?", en: "Great. I'm also looking for a gift. This sweater is too big. Do you have another size?" },
      { nb: "Prøverommet er der. Du kan bytte den senere, eller be om refusjon.", en: "The fitting room is there. You can exchange it later, or ask for a refund." },
      { nb: "Blå er fin. Ha det!", en: "Blue is nice. Bye!" },
    ],
    glosses: {
      tilbud: "discount / special offer",
      matbutikken: "the supermarket",
      grønnsaker: "vegetables",
      billige: "cheap",
      kylling: "chicken",
      salg: "sale",
      stykket: "each",
      handlepose: "shopping bag",
      handlevogna: "the shopping cart",
      åpningstidene: "the opening hours",
      betale: "to pay",
      debetkort: "debit card",
      kredittkort: "credit card",
      kassen: "the checkout / register",
      kontantløse: "cashless",
      vekslepenger: "change (money)",
      gave: "gift",
      genseren: "the sweater",
      "for stor": "too big",
      størrelse: "size",
      prøverommet: "the fitting room",
      bytte: "to exchange / return",
      refusjon: "refund",
    },
  },
  {
    id: "nb-venner",
    categoryId: "nb-bokmal",
    title: "Nye venner",
    subtitle: "New friends",
    trail: "blue-square",
    sentences: [
      { nb: "Hei, jeg heter Sam.", en: "Hi, my name is Sam." },
      { nb: "Hyggelig å se deg. Jeg er Noor.", en: "Nice to see you. I'm Noor." },
      { nb: "Hvor kommer du fra?", en: "Where are you from?" },
      { nb: "Fra Canada, men jeg bor her nå. Og du?", en: "From Canada, but I live here now. And you?" },
      { nb: "Herfra. Hva studerer du?", en: "From here. What do you study?" },
      { nb: "Informatikk. Har du planer i helgen?", en: "Computer science. Do you have plans this weekend?" },
      { nb: "Ja, en liten fest hos en kamerat. Er du ledig? Du er invitert hvis du vil.", en: "Yes, a small party at a buddy's place. Are you free? You're invited if you want." },
      { nb: "Gjerne! Jeg liker å henge med nye folk. Hobbyen min er fotografi.", en: "I'd love to! I like hanging out with new people. My hobby is photography." },
      { nb: "Kjempehyggelig. Det er bursdagen hans, så vi sier gratulerer med dagen, og skål!", en: "Really nice. It's his birthday, so we say happy birthday, and cheers!" },
      { nb: "Kaffe etter seminaret i morgen? Eller museum i helgen?", en: "Coffee after the seminar tomorrow? Or the museum this weekend?" },
      { nb: "Ja. Vi ses snart. Ta vare på deg, og hold kontakten!", en: "Yes. See you soon. Take care, and stay in touch!" },
    ],
    glosses: {
      "Hyggelig å se deg": "Nice to see you",
      herfra: "from here",
      planer: "plans",
      helgen: "the weekend",
      fest: "party",
      kamerat: "buddy / mate",
      "Er du ledig?": "Are you free?",
      invitert: "invited",
      henge: "to hang out",
      hobbyen: "the hobby",
      fotografi: "photography",
      kjempehyggelig: "really nice",
      bursdagen: "the birthday",
      "gratulerer med dagen": "happy birthday",
      skål: "cheers",
      seminaret: "the seminar",
      "vi ses snart": "see you soon",
      "Ta vare på deg": "Take care",
      "hold kontakten": "stay in touch",
    },
  },
  {
    id: "nb-jobb",
    categoryId: "nb-bokmal",
    title: "Første arbeidsdag",
    subtitle: "First day at work",
    trail: "black-diamond",
    sentences: [
      { nb: "Velkommen til teamet, Sam. Dette er kontoret.", en: "Welcome to the team, Sam. This is the office." },
      { nb: "Takk. Jeg er litt nervøs. Er det fulltid eller deltid?", en: "Thanks. I'm a bit nervous. Is it full-time or part-time?" },
      { nb: "Fulltid. Etter ansettelsen presenterer sjefen prosjektet.", en: "Full-time. After the hire, the boss presents the project." },
      { nb: "Hvor kan jeg sette tingene mine?", en: "Where can I put my things?" },
      { nb: "Her ved vinduet er pulten din. Passordet får du av en medarbeider.", en: "Here by the window is your desk. You'll get the password from a coworker." },
      { nb: "Hvis du har spørsmål, bare spør. Agendaen ligger i møterommet.", en: "If you have questions, just ask. The agenda is in the meeting room." },
      { nb: "Forstått. Hvem er veilederen min i dag?", en: "Understood. Who is my supervisor today?" },
      { nb: "Det er jeg. Innleveringsfristen for første faktura til kunden er fredag.", en: "That's me. The deadline for the first invoice to the client is Friday." },
      { nb: "Ok. Når kommer lønnen, og kan jeg ha hjemmekontor noen dager?", en: "Ok. When does the salary come, and can I work from home some days?" },
      { nb: "Lønn den 15. Se lønnsslippen. Hjemmekontor etter prøvetiden.", en: "Salary on the 15th. See the payslip. Home office after the trial period." },
      { nb: "Flott. Blir det forretningsreise senere i året?", en: "Great. Will there be a business trip later in the year?" },
      { nb: "Mulig. Lykke til!", en: "Possibly. Good luck!" },
    ],
    glosses: {
      teamet: "the team",
      kontoret: "the office",
      nervøs: "nervous",
      fulltid: "full-time",
      deltid: "part-time",
      ansettelsen: "the employment / hire",
      sjefen: "the boss",
      prosjektet: "the project",
      pulten: "the desk",
      passordet: "the password",
      medarbeider: "coworker",
      agendaen: "the agenda",
      møterommet: "the meeting room",
      veilederen: "the supervisor",
      innleveringsfristen: "the deadline",
      faktura: "invoice",
      kunden: "the customer / client",
      lønnen: "the salary",
      lønnsslippen: "the payslip",
      hjemmekontor: "home office / remote work",
      prøvetiden: "the trial period",
      forretningsreise: "business trip",
    },
  },
  {
    id: "nb-lege",
    categoryId: "nb-bokmal",
    title: "Hos legen",
    subtitle: "At the doctor's",
    trail: "black-diamond",
    sentences: [
      { nb: "God dag. Har du legetime nå?", en: "Good day. Do you have a doctor's appointment now?" },
      { nb: "Ja. Hva er det som er galt?", en: "Yes. What's the matter?" },
      { nb: "Jeg har hatt vondt i halsen i to dager, og hodepine. Smerte i øret også.", en: "I've had a sore throat for two days, and a headache. Pain in the ear too." },
      { nb: "Har du feber, hoste eller andre symptomer?", en: "Do you have a fever, a cough, or other symptoms?" },
      { nb: "Litt feber i morges, og litt hoste. Ingen magesmerter.", en: "A little fever this morning, and a bit of a cough. No stomachache." },
      { nb: "Sykepleieren tar blodtrykk først. Si aaa.", en: "The nurse will take blood pressure first. Say ah." },
      { nb: "Det ser ut som en mild forkjølelse. Har du allergi mot noe?", en: "It looks like a mild cold. Do you have an allergy to anything?" },
      { nb: "Nei. Trenger jeg resept på medisin?", en: "No. Do I need a prescription for medicine?" },
      { nb: "Ikke ennå. Hvile, vann og paracetamol. Kom tilbake hvis det blir verre.", en: "Not yet. Rest, water, and paracetamol. Come back if it gets worse." },
      { nb: "Tusen takk. Kan jeg få sykmelding hvis det blir verre?", en: "Thank you. Can I get a sick note if it gets worse?" },
      { nb: "Ja. Ved nødsituasjon: ring ambulanse, eller gå til akuttmottaket.", en: "Yes. In an emergency: call an ambulance, or go to A&E / the ER." },
    ],
    glosses: {
      legetime: "doctor's appointment",
      "vondt i halsen": "sore throat",
      hodepine: "headache",
      smerte: "pain",
      feber: "fever",
      hoste: "cough",
      symptomer: "symptoms",
      magesmerter: "stomachache",
      sykepleieren: "the nurse",
      blodtrykk: "blood pressure",
      forkjølelse: "cold (illness)",
      allergi: "allergy",
      resept: "prescription",
      medisin: "medicine",
      paracetamol: "paracetamol / acetaminophen",
      sykmelding: "sick note",
      nødsituasjon: "emergency",
      ambulanse: "ambulance",
      akuttmottaket: "the emergency room",
    },
  },
  {
    id: "nb-bolig",
    categoryId: "nb-bokmal",
    title: "Leter etter et rom",
    subtitle: "Looking for a room",
    trail: "black-diamond",
    sentences: [
      { nb: "Hei, jeg ringer om leiligheten på nettet.", en: "Hi, I'm calling about the apartment online." },
      { nb: "Ja, den er fortsatt ledig. Når vil du se den?", en: "Yes, it's still free. When would you like to see it?" },
      { nb: "I ettermiddag går fint, rundt tre.", en: "This afternoon works fine, around three." },
      { nb: "Fint. Den ligger i nabolaget, tredje etasje. Det er et kollektiv. Du blir leietaker.", en: "Fine. It's in the neighborhood, third floor. It's a shared flat. You'll be a tenant." },
      { nb: "Er det heis? Jeg har bare en koffert med klær. Hotell blir for dyrt lenge.", en: "Is there an elevator? I only have a suitcase with clothes. A hotel gets too expensive long-term." },
      { nb: "Nei, bare trapper. Soverommet er lyst, og det er balkong.", en: "No, only stairs. The bedroom is bright, and there is a balcony." },
      { nb: "Hva med stuen og vaskerommet? Noen lekkasje i badet?", en: "What about the living room and the laundry room? Any leak in the bathroom?" },
      { nb: "Felles. Ingen lekkasje. Husleia inkluderer internett; fellesutgifter kommer ekstra.", en: "Shared. No leak. The rent includes internet; shared costs come extra." },
      { nb: "Og er det sikkerhetsdepositum? Når får jeg nøkler?", en: "And is there a security deposit? When do I get keys?" },
      { nb: "Ja, en måned. Utleier møter deg ved postkassen med leiekontrakten.", en: "Yes, one month. The landlord will meet you at the mailbox with the lease." },
      { nb: "Flott. Si ifra hvis naboen klager på støy. Jeg er stille.", en: "Great. Let me know if the neighbor complains about noise. I'm quiet." },
    ],
    glosses: {
      leiligheten: "the apartment",
      ledig: "available",
      nabolaget: "the neighborhood",
      etasje: "floor (of a building)",
      kollektiv: "shared flat / commune",
      leietaker: "tenant",
      heis: "elevator / lift",
      koffert: "suitcase",
      hotell: "hotel",
      soverommet: "the bedroom",
      balkong: "balcony",
      stuen: "the living room",
      vaskerommet: "the laundry room",
      lekkasje: "leak",
      felles: "shared",
      husleia: "the rent",
      fellesutgifter: "shared costs / utilities",
      sikkerhetsdepositum: "security deposit",
      nøkler: "keys",
      utleier: "landlord",
      postkassen: "the mailbox",
      leiekontrakten: "the lease",
      naboen: "the neighbor",
      støy: "noise",
    },
  },
  {
    id: "nb-streik",
    categoryId: "nb-bokmal",
    title: "Streik i T-banen",
    subtitle: "Subway strike",
    trail: "double-black-diamond",
    sentences: [
      { nb: "Så du nyheten i morges?", en: "Did you see the news this morning?" },
      { nb: "Nei, hva har skjedd?", en: "No, what happened?" },
      { nb: "I morgen er det streik i T-banen og på flere ruter.", en: "Tomorrow there's a strike on the subway and on several routes." },
      { nb: "Så går ikke togene i rushtiden?", en: "So the trains won't run in rush hour?" },
      { nb: "Mange stopper. Det blir byttebuss fra endestasjonen.", en: "Many will stop. There will be a replacement bus from the terminus." },
      { nb: "Jeg tar bysykkel, selv om det regner på fortauet.", en: "I'll take a city bike, even if it rains on the sidewalk." },
      { nb: "Smart. Eller tar du hjemmekontor i morgen?", en: "Smart. Or are you working from home tomorrow?" },
      { nb: "Kanskje. Jeg skal snakke med lederen først, og sjekke budsjettet for taxi.", en: "Maybe. I'll talk to the manager first, and check the budget for a taxi." },
      { nb: "Rundkjøringen ved stasjonen blir kaos. Ta trikk hvis den går.", en: "The roundabout by the station will be chaos. Take the tram if it runs." },
      { nb: "Greit. Hold meg oppdatert hvis avgangen blir kansellert.", en: "Alright. Keep me posted if the departure is cancelled." },
    ],
    glosses: {
      nyheten: "the news",
      streik: "strike",
      "T-banen": "the subway",
      ruter: "routes",
      rushtiden: "rush hour",
      byttebuss: "replacement bus",
      endestasjonen: "the last stop / terminus",
      bysykkel: "city bike",
      fortauet: "the sidewalk",
      hjemmekontor: "home office / remote work",
      lederen: "the manager / leader",
      budsjettet: "the budget",
      taxi: "taxi",
      rundkjøringen: "the roundabout",
      trikk: "tram",
      avgangen: "the departure",
      kansellert: "cancelled",
    },
  },
  {
    id: "nb-debatt",
    categoryId: "nb-bokmal",
    title: "En kort debatt",
    subtitle: "A short debate",
    trail: "double-black-diamond",
    sentences: [
      { nb: "Jeg synes kollektivtransport er kjempeviktig.", en: "I think public transport is really important." },
      { nb: "Hvorfor det?", en: "Why?" },
      { nb: "Fordi ikke alle kan ha bil i rushtiden, og gebyrene for parkering er høye.", en: "Because not everyone can have a car in rush hour, and parking fees are high." },
      { nb: "Men bussene er alltid fulle og forsinka. Beløpet på billetten stiger også.", en: "But the buses are always full and late. The ticket price is rising too." },
      { nb: "Hvis vi investerer mer i ruter, blir det bedre. Se på bybudsjettet.", en: "If we invest more in routes, it gets better. Look at the city budget." },
      { nb: "På lang sikt, kanskje. Akkurat nå er det dyrt. Rente og lån presser folk.", en: "In the long run, maybe. Right now it's expensive. Interest and loans put pressure on people." },
      { nb: "Sant. Likevel synes jeg det er verdt det. Man kan overføre mer til kollektiv.", en: "True. Even so, I think it's worth it. You can transfer more to public transport." },
      { nb: "La oss lese mer før vi bestemmer. Jeg sjekker kontoen min etter lunsj.", en: "Let's read more before we decide. I'll check my account after lunch." },
      { nb: "Greit. Vi møtes ved minibanken på stasjonen og snakker videre.", en: "Alright. We'll meet at the ATM at the station and talk more." },
    ],
    glosses: {
      kollektivtransport: "public transport",
      kjempeviktig: "really important",
      rushtiden: "rush hour",
      gebyrene: "the fees",
      forsinka: "delayed / late (spoken)",
      beløpet: "the amount",
      ruter: "routes",
      bybudsjettet: "the city budget",
      rente: "interest / interest rate",
      lån: "loan",
      "verdt det": "worth it",
      overføre: "to transfer",
      kontoen: "the account",
      lunsj: "lunch",
      minibanken: "the ATM",
    },
  },
  {
    id: "nb-planer",
    categoryId: "nb-bokmal",
    title: "Planer for sommeren",
    subtitle: "Summer plans",
    trail: "double-black-diamond",
    sentences: [
      { nb: "Hva skal du gjøre i sommer?", en: "What are you going to do this summer?" },
      { nb: "Jeg vil reise noen uker, hvis det går. Har du planer?", en: "I want to travel a few weeks, if it works out. Do you have plans?" },
      { nb: "Kanskje til Lofoten. Jeg booker tur-retur i appen i kveld.", en: "Maybe to Lofoten. I'm booking a round-trip in the app tonight." },
      { nb: "Har du pass klart? Bagasjen må innom innsjekking og passkontroll.", en: "Is your passport ready? The luggage has to go through check-in and passport control." },
      { nb: "Ja. Bare håndbagasje. Gate og sete står på boardingkortet etter sikkerhetskontrollen.", en: "Yes. Hand luggage only. Gate and seat are on the boarding pass after security." },
      { nb: "Ombordstigning starter tidlig. Etter landing henter du kofferten på bagasjebåndet.", en: "Boarding starts early. After landing you pick up the suitcase on the baggage carousel." },
      { nb: "Jeg blir her og jobber overtid. Sparingen går til budsjettet mitt, og avdrag på lån.", en: "I'm staying and working overtime. The savings go into my budget, and loan installments." },
      { nb: "Praktisk. Flyet mitt kan bli forsinket. Ankomst er sent uansett.", en: "Practical. My flight might be delayed. Arrival is late either way." },
      { nb: "Si ifra når du lander. Terminalen er enkel å finne.", en: "Let me know when you land. The terminal is easy to find." },
      { nb: "Gjerne. Hold meg oppdatert. Ha en fin avgang!", en: "Will do. Keep me posted. Have a good departure!" },
    ],
    glosses: {
      planer: "plans",
      booker: "am booking",
      "tur-retur": "round-trip",
      pass: "passport",
      bagasjen: "the luggage",
      innsjekking: "check-in",
      passkontroll: "passport control",
      håndbagasje: "hand luggage",
      gate: "gate",
      sete: "seat",
      boardingkortet: "the boarding pass",
      sikkerhetskontrollen: "security",
      ombordstigning: "boarding",
      bagasjebåndet: "the baggage carousel",
      overtid: "overtime",
      budsjettet: "the budget",
      avdrag: "installment",
      lån: "loan",
      forsinket: "delayed",
      ankomst: "arrival",
      "si ifra": "let (me) know",
      lander: "land (verb)",
      terminalen: "the terminal",
      avgang: "departure",
    },
  },
];
