/**
 * Parallel reading texts for the Read tab.
 * Trail marks follow ski-run difficulty (green → double black).
 * Subtitles: short English labels only - no meta, no attribution fluff.
 *
 * ---------------------------------------------------------------------------
 * Read difficulty ladder (product law — desirable difficulty, not native lit)
 * ---------------------------------------------------------------------------
 * Stories are for L2 learning with tap-gloss, not pleasure reading alone.
 * Slightly challenging is good; beginner must never feel Expert is unreachable.
 *
 *   green-circle   Beginner      ~A1   Short turns (mostly 3–8 words). Present.
 *                                    Greetings, yes/no, simple where/what/want.
 *                                    High-frequency core only — almost no theme packs.
 *   blue-square    Intermediate  ~A2   Everyday scenes. Light connectors (men, hvis).
 *                                    Core ranks a bit deeper; light café/shop/social.
 *   black-diamond  Advanced      ~B1   Full situations (work, health, home). Past OK.
 *                                    Multi-clause lightly; theme words welcome.
 *   double-black   Expert        ~B1+  Opinion, plans, denser natural dialogue.
 *                                    Theme weave OK; still sounds like people.
 *
 * Norwegian is the template. Keep dialogue human — never a vocab dump.
 */
const READ_TRAIL_ORDER = [
  "green-circle",
  "blue-square",
  "black-diamond",
  "double-black-diamond",
];

const READ_TRAIL_LEVELS = {
  "green-circle": {
    id: "green-circle",
    label: "Beginner",
  },
  "blue-square": {
    id: "blue-square",
    label: "Intermediate",
  },
  "black-diamond": {
    id: "black-diamond",
    label: "Advanced",
  },
  "double-black-diamond": {
    id: "double-black-diamond",
    label: "Expert",
  },
};

function getReadTrailLevel(id) {
  if (id === "Starter") return READ_TRAIL_LEVELS["green-circle"];
  if (id === "blue-circle") return READ_TRAIL_LEVELS["blue-square"];
  return READ_TRAIL_LEVELS[id] || READ_TRAIL_LEVELS["green-circle"];
}

function sortStoriesByTrail(stories) {
  return [...stories].sort(
    (a, b) => READ_TRAIL_ORDER.indexOf(a.trail) - READ_TRAIL_ORDER.indexOf(b.trail)
  );
}

const READ_STORIES = [
  // ── Beginner (green): short, warm, high-frequency only ─────────────────
  {
    id: "nb-morgen",
    categoryId: "nb-bokmal",
    title: "God morgen",
    subtitle: "Good morning",
    trail: "green-circle",
    sentences: [
      { nb: "God morgen!", en: "Good morning!" },
      { nb: "Hei! Hvordan har du det?", en: "Hi! How are you?" },
      { nb: "Bra, takk. Og du?", en: "Good, thanks. And you?" },
      { nb: "Også bra. Det er fint vær i dag.", en: "Also good. The weather is nice today." },
      { nb: "Ja. Sol og ikke for kaldt.", en: "Yes. Sun and not too cold." },
      { nb: "Skal du til byen?", en: "Are you going into town?" },
      { nb: "Ja. Jeg skal kjøpe brød.", en: "Yes. I'm going to buy bread." },
      { nb: "Ha det bra!", en: "Bye! / Take care!" },
      { nb: "Ha det! Vi ses.", en: "Bye! See you." },
      { nb: "God natt!", en: "Good night!" },
      { nb: "Han bor her også.", en: "He lives here too." },
    ],
    glosses: {
      "God natt": "Good night",
      Han: "he",
      bor: "live / lives",
      også: "also / too",
      "God morgen": "Good morning",
      "Hvordan har du det": "How are you",
      Bra: "good / fine",
      vær: "weather",
      Sol: "sun",
      kaldt: "cold",
      byen: "the town / city",
      kjøpe: "to buy",
      brød: "bread",
      "Ha det bra": "goodbye / take care",
      "Vi ses": "see you",
      Hvordan: "how",
      morgen: "morning",
      Også: "also / too",
      takk: "thanks / thank you",
      dag: "day"
    },
  },
  {
    id: "nb-kaffe",
    categoryId: "nb-bokmal",
    title: "En kaffe, takk",
    subtitle: "A coffee, please",
    trail: "green-circle",
    sentences: [
      { nb: "Hei! Hva vil du ha?", en: "Hi! What would you like?" },
      { nb: "En kaffe, takk.", en: "A coffee, please." },
      { nb: "Med melk?", en: "With milk?" },
      { nb: "Nei, svart. Og vann, takk.", en: "No, black. And water, please." },
      { nb: "Vil du ha noe å spise?", en: "Would you like something to eat?" },
      { nb: "Bare kaffe i dag.", en: "Just coffee today." },
      { nb: "Det blir førti kroner.", en: "That's forty kroner." },
      { nb: "Hvor mye koster det?", en: "How much does it cost?" },
      { nb: "Jeg forstår ikke. Snakk saktere.", en: "I don't understand. Speak more slowly." },
      { nb: "Her er pengene. Takk!", en: "Here's the money. Thanks!" },
      { nb: "Takk skal du ha. Ha en fin dag!", en: "Thank you. Have a nice day!" },
    ],
    glosses: {
      koster: "costs",
      forstår: "understand",
      saktere: "more slowly",
      vil: "want / would like",
      kaffe: "coffee",
      melk: "milk",
      svart: "black",
      vann: "water",
      spise: "to eat",
      Bare: "just / only",
      førti: "forty",
      kroner: "kroner",
      pengene: "the money",
      "fin dag": "nice day",
      blir: "become / is (passive)",
      takk: "thanks / thank you",
      dag: "day",
      fin: "fine / nice",
      Hei: "hello / hi"
    },
  },
  {
    id: "nb-tog",
    categoryId: "nb-bokmal",
    title: "Hvor er toget?",
    subtitle: "Where is the train?",
    trail: "green-circle",
    sentences: [
      { nb: "Unnskyld. Hvor er toget?", en: "Excuse me. Where is the train?" },
      { nb: "Der borte. Spor to.", en: "Over there. Platform two." },
      { nb: "Takk. Går det snart?", en: "Thanks. Does it leave soon?" },
      { nb: "Ja, om ti minutter.", en: "Yes, in ten minutes." },
      { nb: "Trenger jeg billett nå?", en: "Do I need a ticket now?" },
      { nb: "Ja. Du kan kjøpe her.", en: "Yes. You can buy here." },
      { nb: "En billett til sentrum, takk.", en: "One ticket to the center, please." },
      { nb: "Kan du hjelpe meg?", en: "Can you help me?" },
      { nb: "En gang til, takk.", en: "Once more, please." },
      { nb: "Vær så god. Ha en fin tur!", en: "Here you are. Have a nice trip!" },
      { nb: "Tusen takk!", en: "Thank you so much!" },
    ],
    glosses: {
      hjelpe: "to help",
      "En gang til": "once more",
      Unnskyld: "excuse me",
      toget: "the train",
      "Der borte": "over there",
      Spor: "track / platform",
      snart: "soon",
      minutter: "minutes",
      Trenger: "need",
      billett: "ticket",
      kjøpe: "to buy",
      sentrum: "the center",
      "Vær så god": "here you are / you're welcome",
      tur: "trip",
      "Tusen takk": "thank you so much",
      borte: "away / gone",
      Hvor: "where",
      Takk: "thanks / thank you"
    },
  },

  // ── Intermediate (blue): everyday life, light connectors ───────────────
  {
    id: "nb-bibliotek",
    categoryId: "nb-bokmal",
    title: "På biblioteket",
    subtitle: "At the library",
    trail: "blue-square",
    sentences: [
      { nb: "Hei. Har dere bøker på engelsk?", en: "Hi. Do you have books in English?" },
      { nb: "Ja. De står der. Vil du låne noen?", en: "Yes. They're over there. Would you like to borrow some?" },
      { nb: "Ja, gjerne. Trenger jeg studentbevis?", en: "Yes, please. Do I need a student ID?" },
      { nb: "Ja. Du kan få det i dag hvis du har ID.", en: "Yes. You can get it today if you have ID." },
      { nb: "Fint. Hvor lenge kan jeg ha bøkene?", en: "Great. How long can I keep the books?" },
      { nb: "Tre uker. Du kan forlenge på nettet.", en: "Three weeks. You can renew online." },
      { nb: "Er det stille her om kvelden?", en: "Is it quiet here in the evening?" },
      { nb: "Ja, etter seks. Da er det fint å lese pensum.", en: "Yes, after six. Then it's nice to read the syllabus." },
      { nb: "Unnskyld, hvor er toalettet?", en: "Excuse me, where is the toilet?" },
      { nb: "Har dere åpent i morgen?", en: "Are you open tomorrow?" },
      { nb: "Takk for hjelpen!", en: "Thanks for the help!" },
      { nb: "Bare hyggelig. Lykke til med emnet!", en: "You're welcome. Good luck with the course!" },
    ],
    glosses: {
      toalettet: "the toilet",
      "åpent": "open",
      Unnskyld: "excuse me",
      "i morgen": "tomorrow",
      bøker: "books",
      engelsk: "English",
      låne: "to borrow",
      gjerne: "gladly / please",
      studentbevis: "student ID",
      ID: "ID",
      lenge: "long",
      uker: "weeks",
      forlenge: "to renew / extend",
      nettet: "the internet / online",
      stille: "quiet",
      kvelden: "the evening",
      lese: "to read",
      pensum: "syllabus / reading list",
      hjelpen: "the help",
      "Bare hyggelig": "you're welcome",
      emnet: "the course / subject",
    },
  },
  {
    id: "nb-marked",
    categoryId: "nb-bokmal",
    title: "I butikken",
    subtitle: "At the shop",
    trail: "blue-square",
    sentences: [
      { nb: "Hei. Hvor er brødet?", en: "Hi. Where is the bread?" },
      { nb: "Rett fram, til venstre.", en: "Straight ahead, to the left." },
      { nb: "Takk. Hva koster eplene?", en: "Thanks. How much are the apples?" },
      { nb: "Tjue kroner kiloen. De er på tilbud i dag.", en: "Twenty kroner a kilo. They're on sale today." },
      { nb: "Jeg tar fire epler og et brød.", en: "I'll take four apples and a loaf of bread." },
      { nb: "Vil du ha handlepose?", en: "Would you like a shopping bag?" },
      { nb: "Ja, takk. Kan jeg betale med kort?", en: "Yes, please. Can I pay by card?" },
      { nb: "Selvfølgelig. Det blir sekstifem kroner i kassen.", en: "Of course. That's sixty-five kroner at the checkout." },
      { nb: "Kan jeg få kvittering?", en: "Can I get a receipt?" },
      { nb: "Har dere noe billigere?", en: "Do you have something cheaper?" },
      { nb: "Her er kortet. Ha en fin dag!", en: "Here's the card. Have a nice day!" },
      { nb: "I like måte. Velkommen igjen!", en: "Same to you. Welcome back anytime!" },
    ],
    glosses: {
      kvittering: "receipt",
      billigere: "cheaper",
      brødet: "the bread",
      "Rett fram": "straight ahead",
      "til venstre": "to the left",
      koster: "costs",
      eplene: "the apples",
      Tjue: "twenty",
      kiloen: "per kilo",
      tilbud: "sale / special offer",
      tar: "take / will take",
      handlepose: "shopping bag",
      betale: "to pay",
      kort: "card",
      Selvfølgelig: "of course",
      sekstifem: "sixty-five",
      kassen: "the checkout",
      "I like måte": "same to you",
      "Velkommen igjen": "welcome again",
    },
  },
  {
    id: "nb-venner",
    categoryId: "nb-bokmal",
    title: "Nye venner",
    subtitle: "New friends",
    trail: "blue-square",
    sentences: [
      { nb: "Hei, jeg heter Sam.", en: "Hi, my name is Sam." },
      { nb: "Hyggelig å se deg! Jeg er Noor.", en: "Nice to see you! I'm Noor." },
      { nb: "Hvor kommer du fra?", en: "Where are you from?" },
      { nb: "Fra Canada, men jeg bor her nå.", en: "From Canada, but I live here now." },
      { nb: "Hva studerer du?", en: "What do you study?" },
      { nb: "Biologi. Og du?", en: "Biology. And you?" },
      { nb: "Jeg jobber på kafé. Har du planer i helgen?", en: "I work at a café. Do you have plans this weekend?" },
      { nb: "Ikke ennå. Er du ledig på lørdag?", en: "Not yet. Are you free on Saturday?" },
      { nb: "Hva er nummeret ditt?", en: "What's your number?" },
      { nb: "Vi ses i morgen!", en: "See you tomorrow!" },
      { nb: "Gjerne kaffe! Vi kan møtes her klokka to.", en: "Coffee sounds good! We can meet here at two o'clock." },
      { nb: "Supert. Vi ses snart!", en: "Great. See you soon!" },
    ],
    glosses: {
      nummeret: "the number",
      ditt: "your",
      "i morgen": "tomorrow",
      heter: "am called / my name is",
      "Hyggelig å se deg": "nice to see you",
      kommer: "come",
      bor: "live",
      studerer: "study",
      jobber: "work",
      kafé: "café",
      planer: "plans",
      helgen: "the weekend",
      "Ikke ennå": "not yet",
      "Er du ledig": "are you free",
      lørdag: "Saturday",
      møtes: "meet (each other)",
      klokka: "o'clock / the clock",
      "Vi ses snart": "see you soon",
      Biologi: "biology"
    },
  },

  // ── Advanced (black): full situations, past OK, theme welcome ──────────
  {
    id: "nb-jobb",
    categoryId: "nb-bokmal",
    title: "Første dag på jobb",
    subtitle: "First day at work",
    trail: "black-diamond",
    sentences: [
      { nb: "Velkommen til teamet, Sam.", en: "Welcome to the team, Sam." },
      { nb: "Takk. Jeg er litt nervøs.", en: "Thanks. I'm a bit nervous." },
      { nb: "Det er vanlig. Her er pulten din ved vinduet.", en: "That's normal. Here's your desk by the window." },
      { nb: "Flott. Hvem er sjefen min?", en: "Great. Who is my boss?" },
      { nb: "Det er jeg i dag. Passordet får du av en medarbeider.", en: "That's me today. You'll get the password from a coworker." },
      { nb: "Når er lunsj, og er det fulltid?", en: "When is lunch, and is it full-time?" },
      { nb: "Lunsj klokka tolv. Agendaen ligger i møterommet.", en: "Lunch at twelve. The agenda is in the meeting room." },
      { nb: "Kan jeg ha hjemmekontor noen dager senere?", en: "Can I work from home some days later?" },
      { nb: "Etter prøvetiden, hvis det går bra.", en: "After the trial period, if things go well." },
      { nb: "Hva er wifi-passordet?", en: "What's the Wi‑Fi password?" },
      { nb: "Hvem kan jeg spørre hvis jeg trenger hjelp?", en: "Who can I ask if I need help?" },
      { nb: "Forstått. Takk for hjelpen!", en: "Understood. Thanks for the help!" },
      { nb: "Bare spør. Lykke til med prosjektet!", en: "Just ask. Good luck with the project!" },
    ],
    glosses: {
      "wifi-passordet": "the Wi‑Fi password",
      Hvem: "who",
      spørre: "to ask",
      trenger: "need",
      teamet: "the team",
      nervøs: "nervous",
      vanlig: "normal / common",
      pulten: "the desk",
      sjefen: "the boss",
      Passordet: "the password",
      medarbeider: "coworker / colleague",
      lunsj: "lunch",
      fulltid: "full-time",
      Agendaen: "the agenda",
      møterommet: "the meeting room",
      hjemmekontor: "home office / remote work",
      prøvetiden: "the trial period",
      Forstått: "understood",
      prosjektet: "the project",
      Velkommen: "welcome"
    },
  },
  {
    id: "nb-lege",
    categoryId: "nb-bokmal",
    title: "Hos legen",
    subtitle: "At the doctor's",
    trail: "black-diamond",
    sentences: [
      { nb: "God dag. Hva er det som er galt?", en: "Good day. What's the matter?" },
      { nb: "Jeg har hatt vondt i halsen i to dager.", en: "I've had a sore throat for two days." },
      { nb: "Har du feber eller hoste også?", en: "Do you have a fever or a cough as well?" },
      { nb: "Litt feber i morges, og litt hoste.", en: "A little fever this morning, and a bit of a cough." },
      { nb: "Si aaa. Det ser ut som en mild forkjølelse.", en: "Say ah. It looks like a mild cold." },
      { nb: "Trenger jeg resept på medisin?", en: "Do I need a prescription for medicine?" },
      { nb: "Ikke ennå. Hvile, vann og paracetamol.", en: "Not yet. Rest, water, and paracetamol." },
      { nb: "Kan jeg få sykmelding hvis det blir verre?", en: "Can I get a sick note if it gets worse?" },
      { nb: "Ja. Book ny legetime da, eller ring.", en: "Yes. Book a new appointment then, or call." },
      { nb: "Jeg er allergisk mot penicillin.", en: "I'm allergic to penicillin." },
      { nb: "Hvor ofte skal jeg ta det?", en: "How often should I take it?" },
      { nb: "Tusen takk for hjelpen.", en: "Thank you so much for the help." },
      { nb: "Bare hyggelig. Bli frisk snart!", en: "You're welcome. Get well soon!" },
    ],
    glosses: {
      allergisk: "allergic",
      penicillin: "penicillin",
      ofte: "often",
      galt: "wrong / the matter",
      "vondt i halsen": "sore throat",
      dager: "days",
      feber: "fever",
      hoste: "cough",
      morges: "this morning",
      mild: "mild",
      forkjølelse: "cold (illness)",
      resept: "prescription",
      medisin: "medicine",
      Hvile: "rest",
      paracetamol: "paracetamol / acetaminophen",
      sykmelding: "sick note",
      verre: "worse",
      legetime: "doctor's appointment",
      frisk: "well / healthy",
    },
  },
  {
    id: "nb-bolig",
    categoryId: "nb-bokmal",
    title: "Leter etter et rom",
    subtitle: "Looking for a room",
    trail: "black-diamond",
    sentences: [
      { nb: "Hei, jeg ringer om rommet på nettet.", en: "Hi, I'm calling about the room online." },
      { nb: "Ja, det er fortsatt ledig. Når vil du se det?", en: "Yes, it's still free. When would you like to see it?" },
      { nb: "I ettermiddag, rundt tre, hvis det går.", en: "This afternoon, around three, if that works." },
      { nb: "Fint. Det er tredje etasje, ingen heis.", en: "Fine. It's the third floor, no elevator." },
      { nb: "Er det et kollektiv, og hva er husleien?", en: "Is it a shared flat, and what's the rent?" },
      { nb: "Ja. Husleien inkluderer internett. Depositum er en måned.", en: "Yes. Rent includes internet. Deposit is one month." },
      { nb: "Når får jeg nøkler hvis jeg tar det?", en: "When do I get keys if I take it?" },
      { nb: "Utleier møter deg med leiekontrakten ved postkassen.", en: "The landlord will meet you with the lease at the mailbox." },
      { nb: "Når kan jeg flytte inn?", en: "When can I move in?" },
      { nb: "Er strøm inkludert i leien?", en: "Is electricity included in the rent?" },
      { nb: "Høres bra ut. Jeg kommer klokka tre.", en: "Sounds good. I'll come at three o'clock." },
      { nb: "Supert. Ring hvis naboen klager over støy!", en: "Great. Call if the neighbor complains about noise!" },
    ],
    glosses: {
      flytte: "to move",
      inn: "in",
      strøm: "electricity",
      inkludert: "included",
      ringer: "am calling",
      rommet: "the room",
      ledig: "available / free",
      ettermiddag: "afternoon",
      etasje: "floor",
      heis: "elevator",
      kollektiv: "shared flat",
      husleien: "the rent",
      inkluderer: "includes",
      Depositum: "deposit",
      nøkler: "keys",
      Utleier: "landlord",
      leiekontrakten: "the lease",
      postkassen: "the mailbox",
      naboen: "the neighbor",
      støy: "noise",
    },
  },

  // ── Expert (double black): denser, opinion, plans, theme weave ─────────
  {
    id: "nb-streik",
    categoryId: "nb-bokmal",
    title: "Streik i morgen",
    subtitle: "Strike tomorrow",
    trail: "double-black-diamond",
    sentences: [
      { nb: "Så du nyheten i morges?", en: "Did you see the news this morning?" },
      { nb: "Nei, hva har skjedd?", en: "No, what happened?" },
      { nb: "I morgen er det streik i T-banen og på flere busser.", en: "Tomorrow there's a strike on the subway and on several buses." },
      { nb: "Så rushtiden blir kaos?", en: "So rush hour will be chaos?" },
      { nb: "Ja. Mange tog stopper, og det blir byttebuss fra endestasjonen.", en: "Yes. Many trains will stop, and there will be a replacement bus from the terminus." },
      { nb: "Jeg tar bysykkel, selv om det regner.", en: "I'll take a city bike, even if it rains." },
      { nb: "Smart. Eller tar du hjemmekontor hvis lederen godtar det?", en: "Smart. Or will you work from home if the manager allows it?" },
      { nb: "Kanskje. Jeg sjekker budsjettet for taxi først.", en: "Maybe. I'll check the taxi budget first." },
      { nb: "Er toget forsinket?", en: "Is the train delayed?" },
      { nb: "Når går neste buss?", en: "When does the next bus leave?" },
      { nb: "Hold meg oppdatert hvis avgangen din blir kansellert.", en: "Keep me posted if your departure is cancelled." },
      { nb: "Greit. Vi snakkes i kveld.", en: "Alright. Talk tonight." },
    ],
    glosses: {
      forsinket: "delayed",
      neste: "next",
      buss: "bus",
      nyheten: "the news",
      skjedd: "happened",
      streik: "strike",
      "T-banen": "the subway",
      rushtiden: "rush hour",
      kaos: "chaos",
      byttebuss: "replacement bus",
      endestasjonen: "the terminus",
      bysykkel: "city bike",
      hjemmekontor: "home office",
      lederen: "the manager",
      godtar: "accepts / allows",
      budsjettet: "the budget",
      oppdatert: "updated",
      avgangen: "the departure",
      kansellert: "cancelled",
      "Vi snakkes": "we'll talk",
    },
  },
  {
    id: "nb-debatt",
    categoryId: "nb-bokmal",
    title: "En kort debatt",
    subtitle: "A short debate",
    trail: "double-black-diamond",
    sentences: [
      { nb: "Jeg synes kollektivtransport er kjempeviktig.", en: "I think public transport is really important." },
      { nb: "Hvorfor det?", en: "Why?" },
      { nb: "Fordi ikke alle kan ha bil, og parkering er dyrt i sentrum.", en: "Because not everyone can have a car, and parking is expensive downtown." },
      { nb: "Men bussene er ofte fulle og forsinka i rushtiden.", en: "But the buses are often full and late in rush hour." },
      { nb: "Hvis byen investerer mer i ruter, blir det bedre over tid.", en: "If the city invests more in routes, it gets better over time." },
      { nb: "På lang sikt, kanskje. Akkurat nå stiger billettene også.", en: "In the long run, maybe. Right now tickets are rising too." },
      { nb: "Sant. Likevel synes jeg det er verdt det for miljøet.", en: "True. Even so, I think it's worth it for the environment." },
      { nb: "La oss lese mer før vi bestemmer oss.", en: "Let's read more before we decide." },
      { nb: "Jeg er enig.", en: "I agree." },
      { nb: "Hva synes du?", en: "What do you think?" },
      { nb: "Greit. Kaffe etter lunsj, så snakker vi videre?", en: "Alright. Coffee after lunch, then we talk more?" },
      { nb: "Ja. Vi møtes ved stasjonen.", en: "Yes. We'll meet at the station." },
    ],
    glosses: {
      enig: "agree",
      synes: "think / find",
      kollektivtransport: "public transport",
      kjempeviktig: "really important",
      parkering: "parking",
      dyrt: "expensive",
      forsinka: "delayed / late (spoken)",
      investerer: "invests",
      ruter: "routes",
      "På lang sikt": "in the long run",
      billettene: "the tickets",
      Likevel: "even so / nevertheless",
      "verdt det": "worth it",
      miljøet: "the environment",
      bestemmer: "decide",
      lunsj: "lunch",
      Akkurat: "exactly / just"
    },
  },
  {
    id: "nb-planer",
    categoryId: "nb-bokmal",
    title: "Planer for sommeren",
    subtitle: "Summer plans",
    trail: "double-black-diamond",
    sentences: [
      { nb: "Hva skal du gjøre i sommer?", en: "What are you going to do this summer?" },
      { nb: "Jeg vil reise noen uker, hvis det går. Og du?", en: "I want to travel a few weeks, if it works out. And you?" },
      { nb: "Kanskje Lofoten. Jeg betaler med Vipps i appen i kveld.", en: "Maybe Lofoten. I'm paying with Vipps in the app tonight." },
      { nb: "Har du pass klart? Bagasjen må gjennom innsjekking.", en: "Is your passport ready? The luggage has to go through check-in." },
      { nb: "Ja. Bare håndbagasje. Boardingkortet får jeg etter sikkerhetskontrollen.", en: "Yes. Hand luggage only. I get the boarding pass after security." },
      { nb: "Jeg blir her og jobber overtid. Sparingen går til ferien neste år.", en: "I'm staying and working overtime. The savings go to next year's holiday." },
      { nb: "Praktisk. Flyet mitt kan bli forsinket, men ankomst er sent uansett.", en: "Practical. My flight might be delayed, but arrival is late either way." },
      { nb: "Si ifra når du lander. Terminalen er grei å finne.", en: "Let me know when you land. The terminal is easy to find." },
      { nb: "Hvor lang tid tar det?", en: "How long does it take?" },
      { nb: "Hvor er utgangen?", en: "Where is the exit?" },
      { nb: "Gjerne. Ha en fin avgang!", en: "Will do. Have a good departure!" },
      { nb: "Takk. Vi holder kontakten.", en: "Thanks. We'll stay in touch." },
    ],
    glosses: {
      "lang tid": "long time",
      tar: "takes",
      utgangen: "the exit",
      planer: "plans",
      reise: "to travel",
      Vipps: "Norwegian mobile payment",
      betaler: "pay / am paying",
      "tur-retur": "round-trip",
      pass: "passport",
      Bagasjen: "the luggage",
      innsjekking: "check-in",
      håndbagasje: "hand luggage",
      Boardingkortet: "the boarding pass",
      sikkerhetskontrollen: "security",
      overtid: "overtime",
      Sparingen: "the savings",
      ferien: "the holiday / vacation",
      forsinket: "delayed",
      ankomst: "arrival",
      "Si ifra": "let (me) know",
      lander: "land",
      Terminalen: "the terminal",
      avgang: "departure",
      "holder kontakten": "stay in touch",
    },
  },
];
