#!/usr/bin/env python3
"""Phase 1: full Read-story ladders (12 stories × 4 trails) for remaining packs."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def S(foreign, en):
    return {"foreign": foreign, "en": en}


def story(sid, title, subtitle, trail, sentences, glosses, cat):
    return {
        "id": sid,
        "title": title,
        "subtitle": subtitle,
        "trail": trail,
        "sentences": sentences,
        "glosses": glosses,
        "categoryId": cat,
    }


# ─── Shared English scenarios (mirrored per language) ─────────────────────────
# green: morning / coffee / train
# blue: library / market / friends
# black: first workday / doctor / room
# double: strike-news / debate / summer plans


def swedish():
    c = "sv"
    return [
        story(
            "sv-morgon",
            "Morgon i stan",
            "Morning in the city",
            "green-circle",
            [
                S("God morgon.", "Good morning."),
                S("Jag har just kommit fram.", "I just arrived."),
                S("Det är kallt, men solen skiner.", "It is cold, but the sun is shining."),
                S("Jag ser folk och cyklar överallt.", "I see people and bikes everywhere."),
                S("Ursäkta, var ligger stationen?", "Excuse me, where is the station?"),
                S("Rakt fram och sen till vänster.", "Straight ahead and then left."),
                S("Tack så mycket. Jag lär mig fortfarande svenska.", "Thank you so much. I am still learning Swedish."),
                S("Inga problem. Lycka till!", "No problem. Good luck!"),
                S("Hej då!", "Goodbye!"),
            ],
            {"kommit fram": "arrived", "överallt": "everywhere"},
            c,
        ),
        story(
            "sv-kaffe",
            "En kaffe, tack",
            "Ordering coffee",
            "green-circle",
            [
                S("Hej! En kaffe, tack.", "Hi! One coffee, please."),
                S("Med mjölk eller utan?", "With milk or without?"),
                S("Med lite mjölk, tack.", "With a little milk, please."),
                S("Vill du ha något att äta också?", "Would you also like something to eat?"),
                S("En ostsmörgås, tack.", "A cheese sandwich, please."),
                S("Det blir femtio kronor.", "That will be fifty kronor."),
                S("Kan jag betala med kort?", "Can I pay by card?"),
                S("Ja, absolut.", "Yes, absolutely."),
                S("Tack. Ha en fin dag!", "Thanks. Have a nice day!"),
            ],
            {"smörgås": "sandwich", "kronor": "kronor (currency)"},
            c,
        ),
        story(
            "sv-tag",
            "På tåget",
            "On the train",
            "green-circle",
            [
                S("Går det här tåget till Stockholm?", "Does this train go to Stockholm?"),
                S("Ja, det stämmer.", "Yes, that's right."),
                S("Var köper jag biljett?", "Where do I buy a ticket?"),
                S("I appen eller i automaten.", "In the app or at the machine."),
                S("En biljett, enkel, tack.", "One ticket, one-way, please."),
                S("Fönster eller mittgång?", "Window or aisle?"),
                S("Fönster, tack. Hur lång tid tar det?", "Window, please. How long does it take?"),
                S("Ungefär två timmar.", "About two hours."),
                S("Tack för hjälpen.", "Thank you for the help."),
            ],
            {"enkel": "one-way", "automat": "ticket machine"},
            c,
        ),
        story(
            "sv-bibliotek",
            "På biblioteket",
            "At the library",
            "blue-square",
            [
                S("Hej, jag letar efter en tyst plats att plugga.", "Hi, I'm looking for a quiet place to study."),
                S("Uppe finns det lediga bord.", "Upstairs there are free tables."),
                S("Hur länge har ni öppet?", "How long are you open?"),
                S("Till nio i kväll.", "Until nine this evening."),
                S("Kan jag låna böcker här också?", "Can I also borrow books here?"),
                S("Ja, med ett universitets-kort.", "Yes, with a university card."),
                S("Perfekt. Jag har tenta nästa vecka.", "Perfect. I have an exam next week."),
                S("Lycka till med pluggandet!", "Good luck with studying!"),
            ],
            {"plugga": "study (informal)", "tenta": "exam"},
            c,
        ),
        story(
            "sv-marknad",
            "På marknaden",
            "At the market",
            "blue-square",
            [
                S("Vad kostar den osten?", "How much is that cheese?"),
                S("Trettio kronor styck.", "Thirty kronor each."),
                S("Jag tar två, tack.", "I'll take two, please."),
                S("Vill du ha en påse?", "Would you like a bag?"),
                S("Ja, gärna. Och lite frukt också.", "Yes, please. And some fruit too."),
                S("Äpplen eller apelsiner?", "Apples or oranges?"),
                S("Äpplen, fyra stycken.", "Apples, four of them."),
                S("Det blir hundra kronor tillsammans.", "That will be a hundred kronor altogether."),
                S("Här är pengarna. Hej då!", "Here's the money. Goodbye!"),
            ],
            {"styck": "each / piece", "påse": "bag"},
            c,
        ),
        story(
            "sv-vanner",
            "Nya vänner",
            "New friends",
            "blue-square",
            [
                S("Hej, jag heter Sam.", "Hi, my name is Sam."),
                S("Trevligt. Jag är Noor.", "Nice to meet you. I'm Noor."),
                S("Var kommer du ifrån?", "Where are you from?"),
                S("Från Kanada, men jag bor här nu.", "From Canada, but I live here now."),
                S("Vad studerar du?", "What do you study?"),
                S("Data. Och du?", "Computer science. And you?"),
                S("Historia. Fika efter lektionen?", "History. Coffee after class?"),
                S("Ja, gärna! Vi ses snart.", "Yes, gladly! See you soon."),
            ],
            {"trevligt": "nice (to meet you)", "fika": "coffee break"},
            c,
        ),
        story(
            "sv-jobb",
            "Första arbetsdagen",
            "First day at work",
            "black-diamond",
            [
                S("Välkommen till teamet, Sam.", "Welcome to the team, Sam."),
                S("Tack. Jag är lite nervös.", "Thanks. I'm a bit nervous."),
                S("Det är normalt. Vi börjar halv nio.", "That's normal. We start at half past eight."),
                S("Var kan jag ställa mina grejer?", "Where can I put my things?"),
                S("Här vid fönstret är ditt skrivbord.", "Here by the window is your desk."),
                S("Om du har frågor, fråga bara.", "If you have questions, just ask."),
                S("Förstått. Vem är min handledare?", "Understood. Who is my supervisor?"),
                S("Det är jag i dag. Kom, jag visar köket.", "That's me today. Come, I'll show you the kitchen."),
            ],
            {"nervös": "nervous", "handledare": "supervisor"},
            c,
        ),
        story(
            "sv-lakare",
            "Hos läkaren",
            "At the doctor's",
            "black-diamond",
            [
                S("Vad är det som är fel?", "What's the matter?"),
                S("Jag har haft ont i halsen i två dagar.", "I've had a sore throat for two days."),
                S("Har du feber också?", "Do you also have a fever?"),
                S("Lite, i morse.", "A little, this morning."),
                S("Jag tittar lite. Säg aaa.", "I'll take a look. Say ah."),
                S("Det ser ut som en mild infektion.", "It looks like a mild infection."),
                S("Behöver jag antibiotika?", "Do I need antibiotics?"),
                S("Inte än. Vila, vatten och alvedon.", "Not yet. Rest, water, and paracetamol."),
                S("Tack så mycket, doktorn.", "Thank you so much, doctor."),
            ],
            {"ont i halsen": "sore throat", "feber": "fever", "infektion": "infection"},
            c,
        ),
        story(
            "sv-bostad",
            "Letar efter ett rum",
            "Looking for a room",
            "black-diamond",
            [
                S("Hej, jag ringer om rummet på nätet.", "Hi, I'm calling about the room online."),
                S("Ja, det är fortfarande ledigt. När vill du titta?", "Yes, it's still free. When would you like to see it?"),
                S("I eftermiddag funkar, runt tre.", "This afternoon works, around three."),
                S("Bra. Det ligger i centrum, tredje våningen.", "Good. It's in the centre, third floor."),
                S("Finns det hiss?", "Is there a lift?"),
                S("Nej, bara trappor. Hyran inkluderar internet.", "No, only stairs. Rent includes internet."),
                S("Och finns det deposition?", "And is there a deposit?"),
                S("Ja, en månad i förskott. Vi ses!", "Yes, one month in advance. See you!"),
            ],
            {"ledigt": "available / free", "hyra": "rent", "deposition": "deposit"},
            c,
        ),
        story(
            "sv-nyheter",
            "Strejk i tunnelbanan",
            "Subway strike",
            "double-black-diamond",
            [
                S("Såg du nyheten?", "Did you see the news?"),
                S("Nej, vad har hänt?", "No, what happened?"),
                S("I morgon blir det strejk i tunnelbanan.", "Tomorrow there's a subway strike."),
                S("Så tågen går inte?", "So the trains won't run?"),
                S("Många stannar, särskilt på morgonen.", "Many will stop, especially in the morning."),
                S("Jag tar cykeln, även om det regnar.", "I'll take the bike, even if it rains."),
                S("Smart. Eller jobbar du hemifrån?", "Smart. Or are you working from home?"),
                S("Kanske. Jag ska prata med chefen först.", "Maybe. I'll talk to the boss first."),
            ],
            {"strejk": "strike", "tunnelbanan": "the subway"},
            c,
        ),
        story(
            "sv-debatt",
            "En kort debatt",
            "A short debate",
            "double-black-diamond",
            [
                S("Jag tycker kollektivtrafik är jätteviktigt.", "I think public transport is really important."),
                S("Varför då?", "Why?"),
                S("För att alla inte kan ha bil.", "Because not everyone can have a car."),
                S("Men bussarna är alltid fulla och sena.", "But the buses are always full and late."),
                S("Om vi investerar mer blir det bättre.", "If we invest more, it gets better."),
                S("På lång sikt, kanske. Just nu kostar det mycket.", "In the long run, maybe. Right now it costs a lot."),
                S("Sant. Ändå tycker jag det är värt det.", "True. Even so I think it's worth it."),
                S("Vi läser mer om det innan vi bestämmer.", "Let's read more about it before we decide."),
            ],
            {"kollektivtrafik": "public transport", "värt det": "worth it"},
            c,
        ),
        story(
            "sv-planer",
            "Planer för sommaren",
            "Summer plans",
            "double-black-diamond",
            [
                S("Vad ska du göra i sommar?", "What are you going to do in the summer?"),
                S("Jag vill resa några veckor, om det går.", "I want to travel a few weeks, if it works out."),
                S("Vart då?", "Where to?"),
                S("Kanske till norra Sverige. Och du?", "Maybe to northern Sweden. And you?"),
                S("Jag stannar och jobbar övertid.", "I'll stay and work overtime."),
                S("Tråkigt? Eller praktiskt?", "Boring? Or practical?"),
                S("Praktiskt. Jag sparar till nästa år.", "Practical. I'm saving for next year."),
                S("Om du vill haka på senare, säg till.", "If you want to join later, say so."),
                S("Gärna. Håll mig uppdaterad.", "Gladly. Keep me posted."),
            ],
            {"övertid": "overtime", "spara": "save (money)"},
            c,
        ),
    ]


def danish():
    c = "da"
    return [
        story(
            "da-morgen",
            "Morgen i byen",
            "Morning in the city",
            "green-circle",
            [
                S("Godmorgen.", "Good morning."),
                S("Jeg er lige ankommet.", "I just arrived."),
                S("Det er koldt, men solen skinner.", "It is cold, but the sun is shining."),
                S("Jeg ser folk og cykler overalt.", "I see people and bikes everywhere."),
                S("Undskyld, hvor er stationen?", "Excuse me, where is the station?"),
                S("Ligeud og så til venstre.", "Straight ahead and then left."),
                S("Mange tak. Jeg lærer stadig dansk.", "Thank you. I am still learning Danish."),
                S("Ingen problem. Held og lykke!", "No problem. Good luck!"),
                S("Farvel!", "Goodbye!"),
            ],
            {"ankommet": "arrived", "overalt": "everywhere"},
            c,
        ),
        story(
            "da-kaffe",
            "En kaffe, tak",
            "Ordering coffee",
            "green-circle",
            [
                S("Hej! En kaffe, tak.", "Hi! One coffee, please."),
                S("Med mælk eller uden?", "With milk or without?"),
                S("Med lidt mælk, tak.", "With a little milk, please."),
                S("Vil du også have noget at spise?", "Would you also like something to eat?"),
                S("En ostemad, tak.", "A cheese sandwich, please."),
                S("Det bliver femogfyrre kroner.", "That will be forty-five kroner."),
                S("Kan jeg betale med kort?", "Can I pay by card?"),
                S("Ja, selvfølgelig.", "Yes, of course."),
                S("Tak. Hav en god dag!", "Thanks. Have a nice day!"),
            ],
            {"ostemad": "cheese sandwich / open sandwich", "kroner": "kroner (currency)"},
            c,
        ),
        story(
            "da-tog",
            "I toget",
            "On the train",
            "green-circle",
            [
                S("Går det her tog til København?", "Does this train go to Copenhagen?"),
                S("Ja, det er rigtigt.", "Yes, that's right."),
                S("Hvor køber jeg billet?", "Where do I buy a ticket?"),
                S("I appen eller ved automaten.", "In the app or at the machine."),
                S("En billet, enkelt, tak.", "One ticket, one-way, please."),
                S("Vindue eller midtergang?", "Window or aisle?"),
                S("Vindue, tak. Hvor lang tid tager det?", "Window, please. How long does it take?"),
                S("Cirka to timer.", "About two hours."),
                S("Tak for hjælpen.", "Thank you for the help."),
            ],
            {"enkelt": "one-way", "automat": "ticket machine"},
            c,
        ),
        story(
            "da-bibliotek",
            "På biblioteket",
            "At the library",
            "blue-square",
            [
                S("Hej, jeg leder efter et stille sted at læse.", "Hi, I'm looking for a quiet place to study."),
                S("Ovenpå er der ledige borde.", "Upstairs there are free tables."),
                S("Hvor længe har I åbent?", "How long are you open?"),
                S("Til klokken ni i aften.", "Until nine o'clock this evening."),
                S("Kan jeg også låne bøger her?", "Can I also borrow books here?"),
                S("Ja, med et studiekort.", "Yes, with a student card."),
                S("Perfekt. Jeg har eksamen i næste uge.", "Perfect. I have an exam next week."),
                S("Held og lykke med læsningen!", "Good luck with studying!"),
            ],
            {"ledige": "free / available", "eksamen": "exam"},
            c,
        ),
        story(
            "da-marked",
            "På markedet",
            "At the market",
            "blue-square",
            [
                S("Hvad koster den ost?", "How much is that cheese?"),
                S("Tredive kroner stykket.", "Thirty kroner each."),
                S("Jeg tager to, tak.", "I'll take two, please."),
                S("Skal du have en pose med?", "Would you like a bag with that?"),
                S("Ja, gerne. Og lidt frugt også.", "Yes, please. And some fruit too."),
                S("Æbler eller appelsiner?", "Apples or oranges?"),
                S("Æbler, fire stykker.", "Apples, four of them."),
                S("Det bliver hundrede kroner i alt.", "That will be a hundred kroner altogether."),
                S("Her er pengene. Farvel!", "Here's the money. Goodbye!"),
            ],
            {"stykket": "each", "pose": "bag"},
            c,
        ),
        story(
            "da-venner",
            "Nye venner",
            "New friends",
            "blue-square",
            [
                S("Hej, jeg hedder Sam.", "Hi, my name is Sam."),
                S("Hyggeligt. Jeg er Noor.", "Nice to meet you. I'm Noor."),
                S("Hvor kommer du fra?", "Where are you from?"),
                S("Fra Canada, men jeg bor her nu.", "From Canada, but I live here now."),
                S("Hvad studerer du?", "What do you study?"),
                S("Informatik. Og dig?", "Computer science. And you?"),
                S("Historie. Kaffe efter timen?", "History. Coffee after class?"),
                S("Ja, det lyder godt! Vi ses snart.", "Yes, that sounds good! See you soon."),
            ],
            {"hyggeligt": "nice (to meet you)", "timen": "the class / hour"},
            c,
        ),
        story(
            "da-job",
            "Første arbejdsdag",
            "First day at work",
            "black-diamond",
            [
                S("Velkommen til teamet, Sam.", "Welcome to the team, Sam."),
                S("Tak. Jeg er lidt nervøs.", "Thanks. I'm a bit nervous."),
                S("Det er normalt. Vi starter halv ni.", "That's normal. We start at half past eight."),
                S("Hvor kan jeg stille mine ting?", "Where can I put my things?"),
                S("Her ved vinduet er dit skrivebord.", "Here by the window is your desk."),
                S("Hvis du har spørgsmål, så spørg bare.", "If you have questions, just ask."),
                S("Forstået. Hvem er min vejleder?", "Understood. Who is my supervisor?"),
                S("Det er mig i dag. Kom, jeg viser dig køkkenet.", "That's me today. Come, I'll show you the kitchen."),
            ],
            {"nervøs": "nervous", "vejleder": "supervisor"},
            c,
        ),
        story(
            "da-laege",
            "Hos lægen",
            "At the doctor's",
            "black-diamond",
            [
                S("Hvad er der galt?", "What's the matter?"),
                S("Jeg har haft ondt i halsen i to dage.", "I've had a sore throat for two days."),
                S("Har du også feber?", "Do you also have a fever?"),
                S("Lidt, i morges.", "A little, this morning."),
                S("Jeg kigger lige. Sig aaa.", "I'll take a look. Say ah."),
                S("Det ligner en mild infektion.", "It looks like a mild infection."),
                S("Skal jeg have antibiotika?", "Do I need antibiotics?"),
                S("Ikke endnu. Hvile, vand og paracetamol.", "Not yet. Rest, water, and paracetamol."),
                S("Mange tak, doktor.", "Thank you, doctor."),
            ],
            {"ondt i halsen": "sore throat", "feber": "fever", "infektion": "infection"},
            c,
        ),
        story(
            "da-bolig",
            "Leder efter et værelse",
            "Looking for a room",
            "black-diamond",
            [
                S("Hej, jeg ringer om værelset på nettet.", "Hi, I'm calling about the room online."),
                S("Ja, det er stadig ledigt. Hvornår vil du se det?", "Yes, it's still free. When would you like to see it?"),
                S("I eftermiddag kan jeg, omkring tre.", "This afternoon works, around three."),
                S("Fint. Det ligger i centrum, tredje sal.", "Fine. It's in the centre, third floor."),
                S("Er der elevator?", "Is there a lift?"),
                S("Nej, kun trapper. Huslejen inkluderer internet.", "No, only stairs. Rent includes internet."),
                S("Og er der depositum?", "And is there a deposit?"),
                S("Ja, en måned forud. Vi ses!", "Yes, one month in advance. See you!"),
            ],
            {"ledigt": "available", "husleje": "rent", "depositum": "deposit"},
            c,
        ),
        story(
            "da-nyheder",
            "Strejke i metroen",
            "Subway strike",
            "double-black-diamond",
            [
                S("Så du nyheden?", "Did you see the news?"),
                S("Nej, hvad er der sket?", "No, what happened?"),
                S("I morgen er der strejke i metroen.", "Tomorrow there's a subway strike."),
                S("Så kører togene ikke?", "So the trains won't run?"),
                S("Mange stopper, især om morgenen.", "Many will stop, especially in the morning."),
                S("Jeg tager cyklen, selv om det regner.", "I'll take the bike, even if it rains."),
                S("Klogt. Eller arbejder du hjemmefra?", "Smart. Or are you working from home?"),
                S("Måske. Jeg skal snakke med chefen først.", "Maybe. I'll talk to the boss first."),
            ],
            {"strejke": "strike", "metroen": "the subway"},
            c,
        ),
        story(
            "da-debat",
            "En kort debat",
            "A short debate",
            "double-black-diamond",
            [
                S("Jeg synes offentlig transport er rigtig vigtig.", "I think public transport is really important."),
                S("Hvorfor?", "Why?"),
                S("Fordi ikke alle kan have bil.", "Because not everyone can have a car."),
                S("Men busserne er altid fulde og forsinkede.", "But the buses are always full and late."),
                S("Hvis vi investerer mere, bliver det bedre.", "If we invest more, it gets better."),
                S("På lang sigt, måske. Lige nu er det dyrt.", "In the long run, maybe. Right now it's expensive."),
                S("Sandt. Alligevel synes jeg, det er det værd.", "True. Even so I think it's worth it."),
                S("Lad os læse mere om det, før vi beslutter.", "Let's read more about it before we decide."),
            ],
            {"offentlig transport": "public transport", "det værd": "worth it"},
            c,
        ),
        story(
            "da-planer",
            "Planer for sommeren",
            "Summer plans",
            "double-black-diamond",
            [
                S("Hvad skal du lave i sommer?", "What are you going to do in the summer?"),
                S("Jeg vil gerne rejse nogle uger, hvis det kan lade sig gøre.", "I want to travel a few weeks, if it works out."),
                S("Hvorhen?", "Where to?"),
                S("Måske til Jylland. Og dig?", "Maybe to Jutland. And you?"),
                S("Jeg bliver og arbejder overtid.", "I'll stay and work overtime."),
                S("Kedeligt? Eller praktisk?", "Boring? Or practical?"),
                S("Praktisk. Jeg sparer op til næste år.", "Practical. I'm saving for next year."),
                S("Hvis du vil med senere, så sig til.", "If you want to join later, say so."),
                S("Gerne. Hold mig opdateret.", "Gladly. Keep me posted."),
            ],
            {"overtid": "overtime", "spare op": "save up"},
            c,
        ),
    ]


def german():
    c = "de"
    return [
        story(
            "de-morgen",
            "Morgen in der Stadt",
            "Morning in the city",
            "green-circle",
            [
                S("Guten Morgen.", "Good morning."),
                S("Ich bin gerade angekommen.", "I just arrived."),
                S("Es ist kalt, aber die Sonne scheint.", "It is cold, but the sun is shining."),
                S("Ich sehe überall Menschen und Fahrräder.", "I see people and bikes everywhere."),
                S("Entschuldigung, wo ist der Bahnhof?", "Excuse me, where is the station?"),
                S("Geradeaus und dann links.", "Straight ahead and then left."),
                S("Vielen Dank. Ich lerne noch Deutsch.", "Thank you. I am still learning German."),
                S("Kein Problem. Viel Erfolg!", "No problem. Good luck!"),
                S("Auf Wiedersehen!", "Goodbye!"),
            ],
            {"angekommen": "arrived", "überall": "everywhere"},
            c,
        ),
        story(
            "de-kaffee",
            "Einen Kaffee, bitte",
            "Ordering coffee",
            "green-circle",
            [
                S("Hallo! Einen Kaffee, bitte.", "Hi! One coffee, please."),
                S("Mit Milch oder ohne?", "With milk or without?"),
                S("Mit etwas Milch, bitte.", "With a little milk, please."),
                S("Möchten Sie auch etwas zu essen?", "Would you also like something to eat?"),
                S("Ein Käsebrötchen, bitte.", "A cheese roll, please."),
                S("Das macht vier Euro fünfzig.", "That is four euros fifty."),
                S("Kann ich mit Karte zahlen?", "Can I pay by card?"),
                S("Ja, natürlich.", "Yes, of course."),
                S("Danke. Schönen Tag noch!", "Thanks. Have a nice day!"),
            ],
            {"Brötchen": "roll / bun", "Karte": "card"},
            c,
        ),
        story(
            "de-zug",
            "Im Zug",
            "On the train",
            "green-circle",
            [
                S("Fährt dieser Zug nach Berlin?", "Does this train go to Berlin?"),
                S("Ja, genau.", "Yes, exactly."),
                S("Wo kaufe ich ein Ticket?", "Where do I buy a ticket?"),
                S("In der App oder am Automaten.", "In the app or at the machine."),
                S("Ein Ticket, einfach, bitte.", "One ticket, one-way, please."),
                S("Fenster oder Gang?", "Window or aisle?"),
                S("Fenster, bitte. Wie lange dauert es?", "Window, please. How long does it take?"),
                S("Etwa zwei Stunden.", "About two hours."),
                S("Danke für die Hilfe.", "Thank you for the help."),
            ],
            {"einfach": "one-way", "Automat": "ticket machine"},
            c,
        ),
        story(
            "de-bibliothek",
            "In der Bibliothek",
            "At the library",
            "blue-square",
            [
                S("Hallo, ich suche einen ruhigen Platz zum Lernen.", "Hi, I'm looking for a quiet place to study."),
                S("Oben gibt es freie Tische.", "Upstairs there are free tables."),
                S("Wie lange habt ihr geöffnet?", "How long are you open?"),
                S("Bis neun Uhr heute Abend.", "Until nine o'clock this evening."),
                S("Kann ich hier auch Bücher ausleihen?", "Can I also borrow books here?"),
                S("Ja, mit einem Uni-Ausweis.", "Yes, with a university card."),
                S("Perfekt. Nächste Woche habe ich eine Prüfung.", "Perfect. I have an exam next week."),
                S("Viel Erfolg beim Lernen!", "Good luck with studying!"),
            ],
            {"ausleihen": "borrow", "Prüfung": "exam"},
            c,
        ),
        story(
            "de-markt",
            "Auf dem Markt",
            "At the market",
            "blue-square",
            [
                S("Was kostet der Käse?", "How much is that cheese?"),
                S("Drei Euro das Stück.", "Three euros each."),
                S("Ich nehme zwei, bitte.", "I'll take two, please."),
                S("Möchten Sie eine Tüte dazu?", "Would you like a bag with that?"),
                S("Ja, gerne. Und auch etwas Obst.", "Yes, please. And some fruit too."),
                S("Äpfel oder Orangen?", "Apples or oranges?"),
                S("Äpfel, vier Stück.", "Apples, four of them."),
                S("Das macht zusammen zehn Euro.", "That will be ten euros altogether."),
                S("Hier ist das Geld. Auf Wiedersehen!", "Here's the money. Goodbye!"),
            ],
            {"Stück": "piece / each", "Tüte": "bag"},
            c,
        ),
        story(
            "de-freunde",
            "Neue Freunde",
            "New friends",
            "blue-square",
            [
                S("Hi, ich heiße Sam.", "Hi, my name is Sam."),
                S("Freut mich. Ich bin Noor.", "Nice to meet you. I'm Noor."),
                S("Woher kommst du?", "Where are you from?"),
                S("Aus Kanada, aber ich wohne jetzt hier.", "From Canada, but I live here now."),
                S("Was studierst du?", "What do you study?"),
                S("Informatik. Und du?", "Computer science. And you?"),
                S("Geschichte. Lust auf Kaffee nach dem Seminar?", "History. Fancy coffee after the seminar?"),
                S("Ja, super! Bis gleich.", "Yes, great! See you in a bit."),
            ],
            {"freut mich": "pleased to meet you", "Lust auf": "feel like"},
            c,
        ),
        story(
            "de-job",
            "Erster Arbeitstag",
            "First day at work",
            "black-diamond",
            [
                S("Willkommen im Team, Sam.", "Welcome to the team, Sam."),
                S("Danke. Ich bin ein bisschen nervös.", "Thanks. I'm a bit nervous."),
                S("Das ist normal. Wir fangen um halb neun an.", "That's normal. We start at half past eight."),
                S("Wo kann ich meine Sachen hinlegen?", "Where can I put my things?"),
                S("Hier am Fenster ist dein Schreibtisch.", "Here by the window is your desk."),
                S("Wenn du Fragen hast, frag einfach.", "If you have questions, just ask."),
                S("Verstanden. Wer ist meine Betreuerin?", "Understood. Who is my supervisor?"),
                S("Das bin ich heute. Komm, ich zeige dir die Küche.", "That's me today. Come, I'll show you the kitchen."),
            ],
            {"nervös": "nervous", "Betreuerin": "supervisor (f.)"},
            c,
        ),
        story(
            "de-arzt",
            "Beim Arzt",
            "At the doctor's",
            "black-diamond",
            [
                S("Was fehlt Ihnen?", "What's the matter?"),
                S("Ich habe seit zwei Tagen Halsschmerzen.", "I've had a sore throat for two days."),
                S("Haben Sie auch Fieber?", "Do you also have a fever?"),
                S("Ein bisschen, heute Morgen.", "A little, this morning."),
                S("Ich schaue kurz. Sagen Sie aaa.", "I'll take a look. Say ah."),
                S("Es sieht nach einer leichten Infektion aus.", "It looks like a mild infection."),
                S("Brauche ich Antibiotika?", "Do I need antibiotics?"),
                S("Noch nicht. Ruhe, Wasser und Paracetamol.", "Not yet. Rest, water, and paracetamol."),
                S("Vielen Dank, Herr Doktor.", "Thank you, doctor."),
            ],
            {"Halsschmerzen": "sore throat", "Fieber": "fever", "Infektion": "infection"},
            c,
        ),
        story(
            "de-wohnung",
            "Ein Zimmer suchen",
            "Looking for a room",
            "black-diamond",
            [
                S("Hallo, ich rufe wegen des Zimmers im Internet an.", "Hi, I'm calling about the room online."),
                S("Ja, es ist noch frei. Wann möchten Sie es ansehen?", "Yes, it's still free. When would you like to see it?"),
                S("Heute Nachmittag geht, gegen drei.", "This afternoon works, around three."),
                S("Gut. Es liegt im Zentrum, dritter Stock.", "Good. It's in the centre, third floor."),
                S("Gibt es einen Aufzug?", "Is there a lift?"),
                S("Nein, nur Treppen. Die Miete inklusiv Internet.", "No, only stairs. Rent includes internet."),
                S("Und gibt es eine Kaution?", "And is there a deposit?"),
                S("Ja, einen Monat im Voraus. Bis gleich!", "Yes, one month in advance. See you!"),
            ],
            {"Miete": "rent", "Kaution": "deposit", "Aufzug": "lift / elevator"},
            c,
        ),
        story(
            "de-news",
            "Streik bei der Bahn",
            "Rail strike",
            "double-black-diamond",
            [
                S("Hast du die Nachricht gesehen?", "Did you see the news?"),
                S("Nein, was ist passiert?", "No, what happened?"),
                S("Morgen streikt die Bahn.", "Tomorrow there's a rail strike."),
                S("Also fahren die Züge nicht?", "So the trains won't run?"),
                S("Viele fallen aus, vor allem morgens.", "Many will be cancelled, especially in the morning."),
                S("Ich fahre mit dem Rad, auch wenn es regnet.", "I'll go by bike, even if it rains."),
                S("Klug. Oder arbeitest du von zu Hause?", "Smart. Or are you working from home?"),
                S("Vielleicht. Ich spreche noch mit dem Chef.", "Maybe. I'll still talk to the boss."),
            ],
            {"streikt": "is on strike", "fallen aus": "are cancelled"},
            c,
        ),
        story(
            "de-debatte",
            "Eine kurze Debatte",
            "A short debate",
            "double-black-diamond",
            [
                S("Ich finde öffentlichen Verkehr sehr wichtig.", "I think public transport is very important."),
                S("Warum?", "Why?"),
                S("Weil nicht jeder ein Auto haben kann.", "Because not everyone can have a car."),
                S("Aber die Busse sind immer voll und verspätet.", "But the buses are always full and late."),
                S("Wenn wir mehr investieren, wird es besser.", "If we invest more, it gets better."),
                S("Langfristig vielleicht. Gerade ist es teuer.", "In the long run, maybe. Right now it's expensive."),
                S("Stimmt. Trotzdem lohnt es sich, finde ich.", "True. Even so I think it's worth it."),
                S("Lass uns mehr darüber lesen, bevor wir entscheiden.", "Let's read more about it before we decide."),
            ],
            {"öffentlichen Verkehr": "public transport", "lohnt sich": "is worth it"},
            c,
        ),
        story(
            "de-plaene",
            "Pläne für den Sommer",
            "Summer plans",
            "double-black-diamond",
            [
                S("Was machst du im Sommer?", "What are you going to do in the summer?"),
                S("Ich möchte ein paar Wochen reisen, wenn es klappt.", "I want to travel a few weeks, if it works out."),
                S("Wohin?", "Where to?"),
                S("Vielleicht an die Ostsee. Und du?", "Maybe to the Baltic Sea. And you?"),
                S("Ich bleibe und mache Überstunden.", "I'll stay and work overtime."),
                S("Langweilig? Oder praktisch?", "Boring? Or practical?"),
                S("Praktisch. Ich spare für nächstes Jahr.", "Practical. I'm saving for next year."),
                S("Wenn du später mitkommen willst, sag Bescheid.", "If you want to join later, say so."),
                S("Gerne. Halte mich auf dem Laufenden.", "Gladly. Keep me posted."),
            ],
            {"klappt": "works out", "Überstunden": "overtime"},
            c,
        ),
    ]


def french():
    c = "fr"
    return [
        story(
            "fr-matin",
            "Matin en ville",
            "Morning in the city",
            "green-circle",
            [
                S("Bonjour.", "Good morning."),
                S("Je viens d'arriver.", "I just arrived."),
                S("Il fait froid, mais le soleil brille.", "It is cold, but the sun is shining."),
                S("Je vois des gens et des vélos partout.", "I see people and bikes everywhere."),
                S("Pardon, où est la gare ?", "Excuse me, where is the station?"),
                S("Tout droit, puis à gauche.", "Straight ahead and then left."),
                S("Merci beaucoup. J'apprends encore le français.", "Thank you. I am still learning French."),
                S("Pas de problème. Bonne chance !", "No problem. Good luck!"),
                S("Au revoir !", "Goodbye!"),
            ],
            {"viens d'arriver": "just arrived", "partout": "everywhere"},
            c,
        ),
        story(
            "fr-cafe",
            "Un café, s'il vous plaît",
            "Ordering coffee",
            "green-circle",
            [
                S("Bonjour ! Un café, s'il vous plaît.", "Hi! One coffee, please."),
                S("Avec du lait ou sans ?", "With milk or without?"),
                S("Avec un peu de lait, s'il vous plaît.", "With a little milk, please."),
                S("Vous voulez aussi quelque chose à manger ?", "Would you also like something to eat?"),
                S("Un sandwich au fromage, s'il vous plaît.", "A cheese sandwich, please."),
                S("Ça fait quatre euros cinquante.", "That is four euros fifty."),
                S("Je peux payer par carte ?", "Can I pay by card?"),
                S("Oui, bien sûr.", "Yes, of course."),
                S("Merci. Bonne journée !", "Thanks. Have a nice day!"),
            ],
            {"s'il vous plaît": "please (formal)", "carte": "card"},
            c,
        ),
        story(
            "fr-train",
            "Dans le train",
            "On the train",
            "green-circle",
            [
                S("Ce train va à Paris ?", "Does this train go to Paris?"),
                S("Oui, c'est ça.", "Yes, that's right."),
                S("Où est-ce que j'achète un billet ?", "Where do I buy a ticket?"),
                S("Dans l'application ou à l'automate.", "In the app or at the machine."),
                S("Un billet, aller simple, s'il vous plaît.", "One ticket, one-way, please."),
                S("Fenêtre ou couloir ?", "Window or aisle?"),
                S("Fenêtre, s'il vous plaît. Combien de temps ça prend ?", "Window, please. How long does it take?"),
                S("Environ deux heures.", "About two hours."),
                S("Merci pour votre aide.", "Thank you for your help."),
            ],
            {"aller simple": "one-way", "automate": "ticket machine"},
            c,
        ),
        story(
            "fr-bibliotheque",
            "À la bibliothèque",
            "At the library",
            "blue-square",
            [
                S("Bonjour, je cherche un endroit calme pour étudier.", "Hi, I'm looking for a quiet place to study."),
                S("En haut, il y a des tables libres.", "Upstairs there are free tables."),
                S("Vous êtes ouverts jusqu'à quelle heure ?", "Until what time are you open?"),
                S("Jusqu'à vingt et une heures ce soir.", "Until nine o'clock this evening."),
                S("Je peux aussi emprunter des livres ici ?", "Can I also borrow books here?"),
                S("Oui, avec une carte d'étudiant.", "Yes, with a student card."),
                S("Parfait. J'ai un examen la semaine prochaine.", "Perfect. I have an exam next week."),
                S("Bonne chance pour vos révisions !", "Good luck with studying!"),
            ],
            {"emprunter": "borrow", "révisions": "revision / studying"},
            c,
        ),
        story(
            "fr-marche",
            "Au marché",
            "At the market",
            "blue-square",
            [
                S("C'est combien, ce fromage ?", "How much is that cheese?"),
                S("Trois euros la pièce.", "Three euros each."),
                S("J'en prends deux, s'il vous plaît.", "I'll take two, please."),
                S("Vous voulez un sac ?", "Would you like a bag?"),
                S("Oui, s'il vous plaît. Et un peu de fruit aussi.", "Yes, please. And some fruit too."),
                S("Des pommes ou des oranges ?", "Apples or oranges?"),
                S("Des pommes, quatre.", "Apples, four of them."),
                S("Ça fait dix euros en tout.", "That will be ten euros altogether."),
                S("Voici l'argent. Au revoir !", "Here's the money. Goodbye!"),
            ],
            {"la pièce": "each", "sac": "bag"},
            c,
        ),
        story(
            "fr-amis",
            "Nouveaux amis",
            "New friends",
            "blue-square",
            [
                S("Salut, je m'appelle Sam.", "Hi, my name is Sam."),
                S("Enchanté. Moi c'est Noor.", "Nice to meet you. I'm Noor."),
                S("Tu viens d'où ?", "Where are you from?"),
                S("Du Canada, mais j'habite ici maintenant.", "From Canada, but I live here now."),
                S("Tu étudies quoi ?", "What do you study?"),
                S("L'informatique. Et toi ?", "Computer science. And you?"),
                S("L'histoire. Un café après le cours ?", "History. Coffee after class?"),
                S("Oui, avec plaisir ! À tout à l'heure.", "Yes, gladly! See you in a bit."),
            ],
            {"enchanté": "pleased to meet you", "avec plaisir": "gladly"},
            c,
        ),
        story(
            "fr-travail",
            "Premier jour de travail",
            "First day at work",
            "black-diamond",
            [
                S("Bienvenue dans l'équipe, Sam.", "Welcome to the team, Sam."),
                S("Merci. Je suis un peu nerveux.", "Thanks. I'm a bit nervous."),
                S("C'est normal. On commence à huit heures et demie.", "That's normal. We start at half past eight."),
                S("Où est-ce que je peux poser mes affaires ?", "Where can I put my things?"),
                S("Ici près de la fenêtre, c'est ton bureau.", "Here by the window is your desk."),
                S("Si tu as des questions, demande simplement.", "If you have questions, just ask."),
                S("Compris. Qui est mon responsable ?", "Understood. Who is my supervisor?"),
                S("C'est moi aujourd'hui. Viens, je te montre la cuisine.", "That's me today. Come, I'll show you the kitchen."),
            ],
            {"nerveux": "nervous", "responsable": "supervisor / manager"},
            c,
        ),
        story(
            "fr-medecin",
            "Chez le médecin",
            "At the doctor's",
            "black-diamond",
            [
                S("Qu'est-ce qui ne va pas ?", "What's the matter?"),
                S("J'ai mal à la gorge depuis deux jours.", "I've had a sore throat for two days."),
                S("Vous avez aussi de la fièvre ?", "Do you also have a fever?"),
                S("Un peu, ce matin.", "A little, this morning."),
                S("Je vais regarder. Dites aaa.", "I'll take a look. Say ah."),
                S("Ça ressemble à une infection légère.", "It looks like a mild infection."),
                S("Il me faut des antibiotiques ?", "Do I need antibiotics?"),
                S("Pas encore. Du repos, de l'eau et du paracétamol.", "Not yet. Rest, water, and paracetamol."),
                S("Merci beaucoup, docteur.", "Thank you, doctor."),
            ],
            {"gorge": "throat", "fièvre": "fever", "repos": "rest"},
            c,
        ),
        story(
            "fr-logement",
            "Chercher une chambre",
            "Looking for a room",
            "black-diamond",
            [
                S("Bonjour, j'appelle pour la chambre sur Internet.", "Hi, I'm calling about the room online."),
                S("Oui, elle est encore libre. Quand voulez-vous la voir ?", "Yes, it's still free. When would you like to see it?"),
                S("Cet après-midi, vers trois heures.", "This afternoon, around three."),
                S("Parfait. C'est au centre, au troisième étage.", "Perfect. It's in the centre, third floor."),
                S("Il y a un ascenseur ?", "Is there a lift?"),
                S("Non, seulement des escaliers. Le loyer inclut Internet.", "No, only stairs. Rent includes internet."),
                S("Et il y a une caution ?", "And is there a deposit?"),
                S("Oui, un mois d'avance. À tout à l'heure !", "Yes, one month in advance. See you!"),
            ],
            {"loyer": "rent", "caution": "deposit", "étage": "floor"},
            c,
        ),
        story(
            "fr-greve",
            "Grève dans le métro",
            "Subway strike",
            "double-black-diamond",
            [
                S("Tu as vu la nouvelle ?", "Did you see the news?"),
                S("Non, qu'est-ce qui s'est passé ?", "No, what happened?"),
                S("Demain, il y a une grève dans le métro.", "Tomorrow there's a subway strike."),
                S("Donc les trains ne circulent pas ?", "So the trains won't run?"),
                S("Beaucoup vont s'arrêter, surtout le matin.", "Many will stop, especially in the morning."),
                S("Je prends le vélo, même s'il pleut.", "I'll take the bike, even if it rains."),
                S("Malin. Ou tu travailles de chez toi ?", "Smart. Or are you working from home?"),
                S("Peut-être. Je dois encore parler au chef.", "Maybe. I'll still talk to the boss."),
            ],
            {"grève": "strike", "circulent": "run / circulate"},
            c,
        ),
        story(
            "fr-debat",
            "Un court débat",
            "A short debate",
            "double-black-diamond",
            [
                S("Je trouve les transports en commun très importants.", "I think public transport is very important."),
                S("Pourquoi ?", "Why?"),
                S("Parce que tout le monde ne peut pas avoir de voiture.", "Because not everyone can have a car."),
                S("Mais les bus sont toujours pleins et en retard.", "But the buses are always full and late."),
                S("Si on investit plus, ça s'améliore.", "If we invest more, it improves."),
                S("À long terme, peut-être. Pour l'instant, c'est cher.", "In the long run, maybe. Right now it's expensive."),
                S("C'est vrai. Quand même, je pense que ça vaut le coup.", "True. Even so I think it's worth it."),
                S("Lisons-en plus avant de décider.", "Let's read more about it before deciding."),
            ],
            {"transports en commun": "public transport", "vaut le coup": "is worth it"},
            c,
        ),
        story(
            "fr-plans",
            "Projets pour l'été",
            "Summer plans",
            "double-black-diamond",
            [
                S("Tu fais quoi cet été ?", "What are you going to do this summer?"),
                S("Je veux voyager quelques semaines, si ça marche.", "I want to travel a few weeks, if it works out."),
                S("Où ça ?", "Where to?"),
                S("Peut-être en Bretagne. Et toi ?", "Maybe to Brittany. And you?"),
                S("Je reste et je fais des heures supplémentaires.", "I'll stay and work overtime."),
                S("Ennuyeux ? Ou pratique ?", "Boring? Or practical?"),
                S("Pratique. J'économise pour l'année prochaine.", "Practical. I'm saving for next year."),
                S("Si tu veux venir plus tard, dis-le-moi.", "If you want to come later, tell me."),
                S("Avec plaisir. Tiens-moi au courant.", "Gladly. Keep me posted."),
            ],
            {"heures supplémentaires": "overtime", "économise": "save (money)"},
            c,
        ),
    ]


def spanish():
    c = "es"
    return [
        story(
            "es-manana",
            "Mañana en la ciudad",
            "Morning in the city",
            "green-circle",
            [
                S("Buenos días.", "Good morning."),
                S("Acabo de llegar.", "I just arrived."),
                S("Hace frío, pero brilla el sol.", "It is cold, but the sun is shining."),
                S("Veo gente y bicicletas por todas partes.", "I see people and bikes everywhere."),
                S("Perdone, ¿dónde está la estación?", "Excuse me, where is the station?"),
                S("Todo recto y luego a la izquierda.", "Straight ahead and then left."),
                S("Muchas gracias. Todavía estoy aprendiendo español.", "Thank you. I am still learning Spanish."),
                S("Ningún problema. ¡Buena suerte!", "No problem. Good luck!"),
                S("¡Hasta luego!", "Goodbye!"),
            ],
            {"acabo de llegar": "I just arrived", "por todas partes": "everywhere"},
            c,
        ),
        story(
            "es-cafe",
            "Un café, por favor",
            "Ordering coffee",
            "green-circle",
            [
                S("¡Hola! Un café, por favor.", "Hi! One coffee, please."),
                S("¿Con leche o solo?", "With milk or black?"),
                S("Con un poco de leche, por favor.", "With a little milk, please."),
                S("¿Quiere algo de comer también?", "Would you also like something to eat?"),
                S("Un bocadillo de queso, por favor.", "A cheese sandwich, please."),
                S("Son cuatro euros cincuenta.", "That is four euros fifty."),
                S("¿Puedo pagar con tarjeta?", "Can I pay by card?"),
                S("Sí, claro.", "Yes, of course."),
                S("Gracias. ¡Que tenga un buen día!", "Thanks. Have a nice day!"),
            ],
            {"bocadillo": "sandwich", "tarjeta": "card"},
            c,
        ),
        story(
            "es-tren",
            "En el tren",
            "On the train",
            "green-circle",
            [
                S("¿Este tren va a Madrid?", "Does this train go to Madrid?"),
                S("Sí, exacto.", "Yes, exactly."),
                S("¿Dónde compro un billete?", "Where do I buy a ticket?"),
                S("En la app o en la máquina.", "In the app or at the machine."),
                S("Un billete, de ida, por favor.", "One ticket, one-way, please."),
                S("¿Ventana o pasillo?", "Window or aisle?"),
                S("Ventana, por favor. ¿Cuánto tarda?", "Window, please. How long does it take?"),
                S("Unas dos horas.", "About two hours."),
                S("Gracias por la ayuda.", "Thank you for the help."),
            ],
            {"de ida": "one-way", "máquina": "machine"},
            c,
        ),
        story(
            "es-biblioteca",
            "En la biblioteca",
            "At the library",
            "blue-square",
            [
                S("Hola, busco un sitio tranquilo para estudiar.", "Hi, I'm looking for a quiet place to study."),
                S("Arriba hay mesas libres.", "Upstairs there are free tables."),
                S("¿Hasta qué hora están abiertos?", "Until what time are you open?"),
                S("Hasta las nueve de la noche.", "Until nine o'clock this evening."),
                S("¿También puedo sacar libros aquí?", "Can I also borrow books here?"),
                S("Sí, con el carné de la universidad.", "Yes, with a university card."),
                S("Perfecto. La semana que viene tengo un examen.", "Perfect. I have an exam next week."),
                S("¡Mucha suerte con el estudio!", "Good luck with studying!"),
            ],
            {"sacar": "borrow / take out", "carné": "card / ID"},
            c,
        ),
        story(
            "es-mercado",
            "En el mercado",
            "At the market",
            "blue-square",
            [
                S("¿Cuánto cuesta ese queso?", "How much is that cheese?"),
                S("Tres euros la unidad.", "Three euros each."),
                S("Me llevo dos, por favor.", "I'll take two, please."),
                S("¿Quiere una bolsa?", "Would you like a bag?"),
                S("Sí, por favor. Y un poco de fruta también.", "Yes, please. And some fruit too."),
                S("¿Manzanas o naranjas?", "Apples or oranges?"),
                S("Manzanas, cuatro.", "Apples, four of them."),
                S("Son diez euros en total.", "That will be ten euros altogether."),
                S("Aquí tiene el dinero. ¡Hasta luego!", "Here's the money. Goodbye!"),
            ],
            {"unidad": "unit / each", "bolsa": "bag"},
            c,
        ),
        story(
            "es-amigos",
            "Nuevos amigos",
            "New friends",
            "blue-square",
            [
                S("Hola, me llamo Sam.", "Hi, my name is Sam."),
                S("Encantada. Yo soy Noor.", "Nice to meet you. I'm Noor."),
                S("¿De dónde eres?", "Where are you from?"),
                S("De Canadá, pero ahora vivo aquí.", "From Canada, but I live here now."),
                S("¿Qué estudias?", "What do you study?"),
                S("Informática. ¿Y tú?", "Computer science. And you?"),
                S("Historia. ¿Un café después de clase?", "History. Coffee after class?"),
                S("¡Sí, genial! Hasta luego.", "Yes, great! See you later."),
            ],
            {"encantada": "pleased to meet you (f.)", "después de clase": "after class"},
            c,
        ),
        story(
            "es-trabajo",
            "Primer día de trabajo",
            "First day at work",
            "black-diamond",
            [
                S("Bienvenido al equipo, Sam.", "Welcome to the team, Sam."),
                S("Gracias. Estoy un poco nervioso.", "Thanks. I'm a bit nervous."),
                S("Es normal. Empezamos a las ocho y media.", "That's normal. We start at half past eight."),
                S("¿Dónde puedo dejar mis cosas?", "Where can I put my things?"),
                S("Aquí junto a la ventana está tu mesa.", "Here by the window is your desk."),
                S("Si tienes preguntas, solo pregunta.", "If you have questions, just ask."),
                S("Entendido. ¿Quién es mi supervisor?", "Understood. Who is my supervisor?"),
                S("Soy yo hoy. Ven, te enseño la cocina.", "That's me today. Come, I'll show you the kitchen."),
            ],
            {"nervioso": "nervous", "mesa": "desk / table"},
            c,
        ),
        story(
            "es-medico",
            "En el médico",
            "At the doctor's",
            "black-diamond",
            [
                S("¿Qué le pasa?", "What's the matter?"),
                S("Llevo dos días con dolor de garganta.", "I've had a sore throat for two days."),
                S("¿También tiene fiebre?", "Do you also have a fever?"),
                S("Un poco, esta mañana.", "A little, this morning."),
                S("Voy a mirar. Diga aaa.", "I'll take a look. Say ah."),
                S("Parece una infección leve.", "It looks like a mild infection."),
                S("¿Necesito antibióticos?", "Do I need antibiotics?"),
                S("Todavía no. Reposo, agua y paracetamol.", "Not yet. Rest, water, and paracetamol."),
                S("Muchas gracias, doctor.", "Thank you, doctor."),
            ],
            {"garganta": "throat", "fiebre": "fever", "reposo": "rest"},
            c,
        ),
        story(
            "es-piso",
            "Buscando una habitación",
            "Looking for a room",
            "black-diamond",
            [
                S("Hola, llamo por la habitación de Internet.", "Hi, I'm calling about the room online."),
                S("Sí, todavía está libre. ¿Cuándo quiere verla?", "Yes, it's still free. When would you like to see it?"),
                S("Esta tarde puedo, hacia las tres.", "This afternoon works, around three."),
                S("Perfecto. Está en el centro, tercer piso.", "Perfect. It's in the centre, third floor."),
                S("¿Hay ascensor?", "Is there a lift?"),
                S("No, solo escaleras. El alquiler incluye Internet.", "No, only stairs. Rent includes internet."),
                S("¿Y hay fianza?", "And is there a deposit?"),
                S("Sí, un mes por adelantado. ¡Hasta luego!", "Yes, one month in advance. See you!"),
            ],
            {"alquiler": "rent", "fianza": "deposit", "piso": "floor / flat"},
            c,
        ),
        story(
            "es-huelga",
            "Huelga en el metro",
            "Subway strike",
            "double-black-diamond",
            [
                S("¿Viste la noticia?", "Did you see the news?"),
                S("No, ¿qué ha pasado?", "No, what happened?"),
                S("Mañana hay huelga en el metro.", "Tomorrow there's a subway strike."),
                S("¿Entonces no circulan los trenes?", "So the trains won't run?"),
                S("Muchos se paran, sobre todo por la mañana.", "Many will stop, especially in the morning."),
                S("Voy en bici, aunque llueva.", "I'll go by bike, even if it rains."),
                S("Listo. ¿O trabajas desde casa?", "Smart. Or are you working from home?"),
                S("Quizá. Todavía tengo que hablar con el jefe.", "Maybe. I'll still talk to the boss."),
            ],
            {"huelga": "strike", "circulan": "run / circulate"},
            c,
        ),
        story(
            "es-debate",
            "Un debate corto",
            "A short debate",
            "double-black-diamond",
            [
                S("Creo que el transporte público es muy importante.", "I think public transport is very important."),
                S("¿Por qué?", "Why?"),
                S("Porque no todo el mundo puede tener coche.", "Because not everyone can have a car."),
                S("Pero los autobuses siempre van llenos y con retraso.", "But the buses are always full and late."),
                S("Si invertimos más, mejora.", "If we invest more, it improves."),
                S("A largo plazo, quizá. Ahora sale caro.", "In the long run, maybe. Right now it's expensive."),
                S("Es verdad. Aun así, creo que merece la pena.", "True. Even so I think it's worth it."),
                S("Leamos más sobre esto antes de decidir.", "Let's read more about it before deciding."),
            ],
            {"retraso": "delay", "merece la pena": "is worth it"},
            c,
        ),
        story(
            "es-planes",
            "Planes para el verano",
            "Summer plans",
            "double-black-diamond",
            [
                S("¿Qué vas a hacer en verano?", "What are you going to do in the summer?"),
                S("Quiero viajar unas semanas, si sale bien.", "I want to travel a few weeks, if it works out."),
                S("¿Adónde?", "Where to?"),
                S("Quizá a Andalucía. ¿Y tú?", "Maybe to Andalusia. And you?"),
                S("Me quedo y hago horas extra.", "I'll stay and work overtime."),
                S("¿Aburrido? ¿O práctico?", "Boring? Or practical?"),
                S("Práctico. Estoy ahorrando para el año que viene.", "Practical. I'm saving for next year."),
                S("Si quieres venir después, dímelo.", "If you want to come later, tell me."),
                S("Hecho. Mantente en contacto.", "Deal. Keep in touch."),
            ],
            {"horas extra": "overtime", "ahorrando": "saving"},
            c,
        ),
    ]


def italian():
    c = "it"
    return [
        story(
            "it-mattina",
            "Mattina in città",
            "Morning in the city",
            "green-circle",
            [
                S("Buongiorno.", "Good morning."),
                S("Sono appena arrivato.", "I just arrived."),
                S("Fa freddo, ma c'è il sole.", "It is cold, but the sun is shining."),
                S("Vedo persone e biciclette ovunque.", "I see people and bikes everywhere."),
                S("Scusi, dov'è la stazione?", "Excuse me, where is the station?"),
                S("Dritto e poi a sinistra.", "Straight ahead and then left."),
                S("Grazie mille. Sto ancora imparando l'italiano.", "Thank you. I am still learning Italian."),
                S("Nessun problema. Buona fortuna!", "No problem. Good luck!"),
                S("Arrivederci!", "Goodbye!"),
            ],
            {"appena": "just", "ovunque": "everywhere"},
            c,
        ),
        story(
            "it-caffe",
            "Un caffè, per favore",
            "Ordering coffee",
            "green-circle",
            [
                S("Ciao! Un caffè, per favore.", "Hi! One coffee, please."),
                S("Con latte o senza?", "With milk or without?"),
                S("Con un po' di latte, grazie.", "With a little milk, please."),
                S("Vuole anche qualcosa da mangiare?", "Would you also like something to eat?"),
                S("Un panino al formaggio, per favore.", "A cheese sandwich, please."),
                S("Sono quattro euro e cinquanta.", "That is four euros fifty."),
                S("Posso pagare con la carta?", "Can I pay by card?"),
                S("Sì, certo.", "Yes, of course."),
                S("Grazie. Buona giornata!", "Thanks. Have a nice day!"),
            ],
            {"panino": "sandwich / roll", "carta": "card"},
            c,
        ),
        story(
            "it-treno",
            "Sul treno",
            "On the train",
            "green-circle",
            [
                S("Questo treno va a Roma?", "Does this train go to Rome?"),
                S("Sì, esatto.", "Yes, exactly."),
                S("Dove compro un biglietto?", "Where do I buy a ticket?"),
                S("Nell'app o alla macchinetta.", "In the app or at the machine."),
                S("Un biglietto, andata, per favore.", "One ticket, one-way, please."),
                S("Finestrino o corridoio?", "Window or aisle?"),
                S("Finestrino, grazie. Quanto ci vuole?", "Window, please. How long does it take?"),
                S("Circa due ore.", "About two hours."),
                S("Grazie per l'aiuto.", "Thank you for the help."),
            ],
            {"andata": "one-way", "macchinetta": "ticket machine"},
            c,
        ),
        story(
            "it-biblioteca",
            "In biblioteca",
            "At the library",
            "blue-square",
            [
                S("Ciao, cerco un posto tranquillo per studiare.", "Hi, I'm looking for a quiet place to study."),
                S("Di sopra ci sono tavoli liberi.", "Upstairs there are free tables."),
                S("Fino a che ora siete aperti?", "Until what time are you open?"),
                S("Fino alle nove di sera.", "Until nine o'clock this evening."),
                S("Posso anche prendere in prestito dei libri?", "Can I also borrow books here?"),
                S("Sì, con la tessera universitaria.", "Yes, with a university card."),
                S("Perfetto. La prossima settimana ho un esame.", "Perfect. I have an exam next week."),
                S("In bocca al lupo con lo studio!", "Good luck with studying!"),
            ],
            {"prendere in prestito": "borrow", "tessera": "card"},
            c,
        ),
        story(
            "it-mercato",
            "Al mercato",
            "At the market",
            "blue-square",
            [
                S("Quanto costa quel formaggio?", "How much is that cheese?"),
                S("Tre euro l'uno.", "Three euros each."),
                S("Ne prendo due, per favore.", "I'll take two, please."),
                S("Vuole un sacchetto?", "Would you like a bag?"),
                S("Sì, grazie. E anche un po' di frutta.", "Yes, please. And some fruit too."),
                S("Mele o arance?", "Apples or oranges?"),
                S("Mele, quattro.", "Apples, four of them."),
                S("Sono dieci euro in tutto.", "That will be ten euros altogether."),
                S("Ecco i soldi. Arrivederci!", "Here's the money. Goodbye!"),
            ],
            {"l'uno": "each", "sacchetto": "bag"},
            c,
        ),
        story(
            "it-amici",
            "Nuovi amici",
            "New friends",
            "blue-square",
            [
                S("Ciao, mi chiamo Sam.", "Hi, my name is Sam."),
                S("Piacere. Io sono Noor.", "Nice to meet you. I'm Noor."),
                S("Di dove sei?", "Where are you from?"),
                S("Dal Canada, ma ora abito qui.", "From Canada, but I live here now."),
                S("Cosa studi?", "What do you study?"),
                S("Informatica. E tu?", "Computer science. And you?"),
                S("Storia. Un caffè dopo la lezione?", "History. Coffee after class?"),
                S("Sì, volentieri! A dopo.", "Yes, gladly! See you later."),
            ],
            {"piacere": "pleased to meet you", "volentieri": "gladly"},
            c,
        ),
        story(
            "it-lavoro",
            "Primo giorno di lavoro",
            "First day at work",
            "black-diamond",
            [
                S("Benvenuto nella squadra, Sam.", "Welcome to the team, Sam."),
                S("Grazie. Sono un po' nervoso.", "Thanks. I'm a bit nervous."),
                S("È normale. Iniziamo alle otto e mezza.", "That's normal. We start at half past eight."),
                S("Dove posso mettere le mie cose?", "Where can I put my things?"),
                S("Qui vicino alla finestra c'è la tua scrivania.", "Here by the window is your desk."),
                S("Se hai domande, chiedi pure.", "If you have questions, just ask."),
                S("Capito. Chi è il mio supervisore?", "Understood. Who is my supervisor?"),
                S("Sono io oggi. Vieni, ti mostro la cucina.", "That's me today. Come, I'll show you the kitchen."),
            ],
            {"nervoso": "nervous", "scrivania": "desk"},
            c,
        ),
        story(
            "it-medico",
            "Dal medico",
            "At the doctor's",
            "black-diamond",
            [
                S("Cosa non va?", "What's the matter?"),
                S("Ho mal di gola da due giorni.", "I've had a sore throat for two days."),
                S("Ha anche la febbre?", "Do you also have a fever?"),
                S("Un po', stamattina.", "A little, this morning."),
                S("Guardo un attimo. Dica aaa.", "I'll take a look. Say ah."),
                S("Sembra un'infezione leggera.", "It looks like a mild infection."),
                S("Mi servono gli antibiotici?", "Do I need antibiotics?"),
                S("Non ancora. Riposo, acqua e paracetamolo.", "Not yet. Rest, water, and paracetamol."),
                S("Grazie mille, dottore.", "Thank you, doctor."),
            ],
            {"gola": "throat", "febbre": "fever", "riposo": "rest"},
            c,
        ),
        story(
            "it-stanza",
            "Cerco una stanza",
            "Looking for a room",
            "black-diamond",
            [
                S("Buongiorno, chiamo per la stanza su Internet.", "Hi, I'm calling about the room online."),
                S("Sì, è ancora libera. Quando vuole vederla?", "Yes, it's still free. When would you like to see it?"),
                S("Questo pomeriggio va bene, verso le tre.", "This afternoon works, around three."),
                S("Perfetto. È in centro, al terzo piano.", "Perfect. It's in the centre, third floor."),
                S("C'è l'ascensore?", "Is there a lift?"),
                S("No, solo scale. L'affitto include Internet.", "No, only stairs. Rent includes internet."),
                S("E c'è una cauzione?", "And is there a deposit?"),
                S("Sì, un mese anticipato. A dopo!", "Yes, one month in advance. See you!"),
            ],
            {"affitto": "rent", "cauzione": "deposit", "piano": "floor"},
            c,
        ),
        story(
            "it-sciopero",
            "Sciopero della metro",
            "Subway strike",
            "double-black-diamond",
            [
                S("Hai visto la notizia?", "Did you see the news?"),
                S("No, cos'è successo?", "No, what happened?"),
                S("Domani c'è lo sciopero della metro.", "Tomorrow there's a subway strike."),
                S("Quindi i treni non circolano?", "So the trains won't run?"),
                S("Molti si fermano, soprattutto al mattino.", "Many will stop, especially in the morning."),
                S("Vado in bici, anche se piove.", "I'll go by bike, even if it rains."),
                S("Furbo. O lavori da casa?", "Smart. Or are you working from home?"),
                S("Forse. Devo ancora parlare col capo.", "Maybe. I'll still talk to the boss."),
            ],
            {"sciopero": "strike", "circolano": "run / circulate"},
            c,
        ),
        story(
            "it-dibattito",
            "Un breve dibattito",
            "A short debate",
            "double-black-diamond",
            [
                S("Penso che i trasporti pubblici siano molto importanti.", "I think public transport is very important."),
                S("Perché?", "Why?"),
                S("Perché non tutti possono avere la macchina.", "Because not everyone can have a car."),
                S("Ma gli autobus sono sempre pieni e in ritardo.", "But the buses are always full and late."),
                S("Se investiamo di più, migliora.", "If we invest more, it improves."),
                S("A lungo termine, forse. Adesso costa tanto.", "In the long run, maybe. Right now it's expensive."),
                S("Vero. Comunque penso che ne valga la pena.", "True. Even so I think it's worth it."),
                S("Leggiamo di più prima di decidere.", "Let's read more about it before deciding."),
            ],
            {"in ritardo": "late", "ne valga la pena": "is worth it"},
            c,
        ),
        story(
            "it-piani",
            "Piani per l'estate",
            "Summer plans",
            "double-black-diamond",
            [
                S("Cosa fai in estate?", "What are you going to do in the summer?"),
                S("Voglio viaggiare qualche settimana, se va bene.", "I want to travel a few weeks, if it works out."),
                S("Dove?", "Where to?"),
                S("Forse in Toscana. E tu?", "Maybe to Tuscany. And you?"),
                S("Resto e faccio straordinari.", "I'll stay and work overtime."),
                S("Noioso? O pratico?", "Boring? Or practical?"),
                S("Pratico. Sto mettendo da parte soldi per l'anno prossimo.", "Practical. I'm saving money for next year."),
                S("Se vuoi venire dopo, dimmelo.", "If you want to come later, tell me."),
                S("Volentieri. Tienimi aggiornato.", "Gladly. Keep me posted."),
            ],
            {"straordinari": "overtime", "mettere da parte": "put aside / save"},
            c,
        ),
    ]


def norwegian():
    """Bokmål stories using nb field (read-stories.js format)."""
    c = "nb-bokmal"

    def N(nb, en):
        return {"nb": nb, "en": en}

    def st(sid, title, subtitle, trail, sentences, glosses):
        return {
            "id": sid,
            "categoryId": c,
            "title": title,
            "subtitle": subtitle,
            "trail": trail,
            "sentences": sentences,
            "glosses": glosses,
        }

    return [
        st(
            "nb-morgen",
            "Morgen i byen",
            "Morning in the city",
            "green-circle",
            [
                N("God morgen.", "Good morning."),
                N("Jeg har nettopp kommet fram.", "I just arrived."),
                N("Det er kaldt, men sola skinner.", "It is cold, but the sun is shining."),
                N("Jeg ser folk og sykler overalt.", "I see people and bikes everywhere."),
                N("Unnskyld, hvor er stasjonen?", "Excuse me, where is the station?"),
                N("Rett fram og så til venstre.", "Straight ahead and then left."),
                N("Tusen takk. Jeg lærer fortsatt norsk.", "Thank you. I am still learning Norwegian."),
                N("Ingen problem. Lykke til!", "No problem. Good luck!"),
                N("Ha det!", "Goodbye!"),
            ],
            {"kommet fram": "arrived", "overalt": "everywhere"},
        ),
        st(
            "nb-kaffe",
            "En kaffe, takk",
            "Ordering coffee",
            "green-circle",
            [
                N("Hei! En kaffe, takk.", "Hi! One coffee, please."),
                N("Med melk eller uten?", "With milk or without?"),
                N("Med litt melk, takk.", "With a little milk, please."),
                N("Vil du ha noe å spise også?", "Would you also like something to eat?"),
                N("Et ostesmørbrød, takk.", "A cheese sandwich, please."),
                N("Det blir førtifem kroner.", "That will be forty-five kroner."),
                N("Kan jeg betale med kort?", "Can I pay by card?"),
                N("Ja, selvfølgelig.", "Yes, of course."),
                N("Takk. Ha en fin dag!", "Thanks. Have a nice day!"),
            ],
            {"ostesmørbrød": "cheese sandwich", "kroner": "kroner (currency)"},
        ),
        st(
            "nb-tog",
            "På toget",
            "On the train",
            "green-circle",
            [
                N("Går dette toget til Oslo?", "Does this train go to Oslo?"),
                N("Ja, det stemmer.", "Yes, that's right."),
                N("Hvor kjøper jeg billett?", "Where do I buy a ticket?"),
                N("I appen eller i automaten.", "In the app or at the machine."),
                N("En billett, en vei, takk.", "One ticket, one-way, please."),
                N("Vindu eller midtgang?", "Window or aisle?"),
                N("Vindu, takk. Hvor lang tid tar det?", "Window, please. How long does it take?"),
                N("Omtrent to timer.", "About two hours."),
                N("Takk for hjelpen.", "Thank you for the help."),
            ],
            {"en vei": "one-way", "automat": "ticket machine"},
        ),
        st(
            "nb-bibliotek",
            "På biblioteket",
            "At the library",
            "blue-square",
            [
                N("Hei, jeg leter etter et stille sted å studere.", "Hi, I'm looking for a quiet place to study."),
                N("Oppe er det ledige bord.", "Upstairs there are free tables."),
                N("Hvor lenge har dere åpent?", "How long are you open?"),
                N("Til klokka ni i kveld.", "Until nine o'clock this evening."),
                N("Kan jeg også låne bøker her?", "Can I also borrow books here?"),
                N("Ja, med studentkort.", "Yes, with a student card."),
                N("Perfekt. Jeg har eksamen neste uke.", "Perfect. I have an exam next week."),
                N("Lykke til med lesingen!", "Good luck with studying!"),
            ],
            {"ledige": "free / available", "eksamen": "exam"},
        ),
        st(
            "nb-marked",
            "På markedet",
            "At the market",
            "blue-square",
            [
                N("Hva koster den osten?", "How much is that cheese?"),
                N("Tretti kroner stykket.", "Thirty kroner each."),
                N("Jeg tar to, takk.", "I'll take two, please."),
                N("Vil du ha en pose?", "Would you like a bag?"),
                N("Ja, gjerne. Og litt frukt også.", "Yes, please. And some fruit too."),
                N("Epler eller appelsiner?", "Apples or oranges?"),
                N("Epler, fire stykker.", "Apples, four of them."),
                N("Det blir hundre kroner til sammen.", "That will be a hundred kroner altogether."),
                N("Her er pengene. Ha det!", "Here's the money. Goodbye!"),
            ],
            {"stykket": "each", "pose": "bag"},
        ),
        st(
            "nb-venner",
            "Nye venner",
            "New friends",
            "blue-square",
            [
                N("Hei, jeg heter Sam.", "Hi, my name is Sam."),
                N("Hyggelig. Jeg er Noor.", "Nice to meet you. I'm Noor."),
                N("Hvor kommer du fra?", "Where are you from?"),
                N("Fra Canada, men jeg bor her nå.", "From Canada, but I live here now."),
                N("Hva studerer du?", "What do you study?"),
                N("Informatikk. Og du?", "Computer science. And you?"),
                N("Historie. Kaffe etter timen?", "History. Coffee after class?"),
                N("Ja, gjerne! Vi ses snart.", "Yes, gladly! See you soon."),
            ],
            {"hyggelig": "nice (to meet you)", "timen": "the class"},
        ),
        st(
            "nb-jobb",
            "Første arbeidsdag",
            "First day at work",
            "black-diamond",
            [
                N("Velkommen til teamet, Sam.", "Welcome to the team, Sam."),
                N("Takk. Jeg er litt nervøs.", "Thanks. I'm a bit nervous."),
                N("Det er normalt. Vi starter halv ni.", "That's normal. We start at half past eight."),
                N("Hvor kan jeg sette tingene mine?", "Where can I put my things?"),
                N("Her ved vinduet er pulten din.", "Here by the window is your desk."),
                N("Hvis du har spørsmål, bare spør.", "If you have questions, just ask."),
                N("Forstått. Hvem er veilederen min?", "Understood. Who is my supervisor?"),
                N("Det er jeg i dag. Kom, jeg viser deg kjøkkenet.", "That's me today. Come, I'll show you the kitchen."),
            ],
            {"nervøs": "nervous", "veileder": "supervisor"},
        ),
        st(
            "nb-lege",
            "Hos legen",
            "At the doctor's",
            "black-diamond",
            [
                N("Hva er det som er galt?", "What's the matter?"),
                N("Jeg har hatt vondt i halsen i to dager.", "I've had a sore throat for two days."),
                N("Har du feber også?", "Do you also have a fever?"),
                N("Litt, i morges.", "A little, this morning."),
                N("Jeg ser litt på det. Si aaa.", "I'll take a look. Say ah."),
                N("Det ser ut som en mild infeksjon.", "It looks like a mild infection."),
                N("Trenger jeg antibiotika?", "Do I need antibiotics?"),
                N("Ikke ennå. Hvile, vann og paracetamol.", "Not yet. Rest, water, and paracetamol."),
                N("Tusen takk, doktor.", "Thank you, doctor."),
            ],
            {"vondt i halsen": "sore throat", "feber": "fever", "infeksjon": "infection"},
        ),
        st(
            "nb-bolig",
            "Leter etter et rom",
            "Looking for a room",
            "black-diamond",
            [
                N("Hei, jeg ringer om rommet på nettet.", "Hi, I'm calling about the room online."),
                N("Ja, det er fortsatt ledig. Når vil du se det?", "Yes, it's still free. When would you like to see it?"),
                N("I ettermiddag går, rundt tre.", "This afternoon works, around three."),
                N("Fint. Det ligger i sentrum, tredje etasje.", "Fine. It's in the centre, third floor."),
                N("Er det heis?", "Is there a lift?"),
                N("Nei, bare trapper. Leia inkluderer internett.", "No, only stairs. Rent includes internet."),
                N("Og er det depositum?", "And is there a deposit?"),
                N("Ja, en måned på forskudd. Vi ses!", "Yes, one month in advance. See you!"),
            ],
            {"ledig": "available", "leie": "rent", "depositum": "deposit"},
        ),
        st(
            "nb-streik",
            "Streik i T-banen",
            "Subway strike",
            "double-black-diamond",
            [
                N("Så du nyheten?", "Did you see the news?"),
                N("Nei, hva har skjedd?", "No, what happened?"),
                N("I morgen er det streik i T-banen.", "Tomorrow there's a subway strike."),
                N("Så går ikke togene?", "So the trains won't run?"),
                N("Mange stopper, særlig om morgenen.", "Many will stop, especially in the morning."),
                N("Jeg tar sykkelen, selv om det regner.", "I'll take the bike, even if it rains."),
                N("Smart. Eller jobber du hjemmefra?", "Smart. Or are you working from home?"),
                N("Kanskje. Jeg skal snakke med sjefen først.", "Maybe. I'll talk to the boss first."),
            ],
            {"streik": "strike", "T-banen": "the subway"},
        ),
        st(
            "nb-debatt",
            "En kort debatt",
            "A short debate",
            "double-black-diamond",
            [
                N("Jeg synes kollektivtransport er kjempeviktig.", "I think public transport is really important."),
                N("Hvorfor det?", "Why?"),
                N("Fordi ikke alle kan ha bil.", "Because not everyone can have a car."),
                N("Men bussene er alltid fulle og forsinka.", "But the buses are always full and late."),
                N("Hvis vi investerer mer, blir det bedre.", "If we invest more, it gets better."),
                N("På lang sikt, kanskje. Akkurat nå er det dyrt.", "In the long run, maybe. Right now it's expensive."),
                N("Sant. Likevel synes jeg det er verdt det.", "True. Even so I think it's worth it."),
                N("La oss lese mer om det før vi bestemmer.", "Let's read more about it before we decide."),
            ],
            {"kollektivtransport": "public transport", "verdt det": "worth it"},
        ),
        st(
            "nb-planer",
            "Planer for sommeren",
            "Summer plans",
            "double-black-diamond",
            [
                N("Hva skal du gjøre i sommer?", "What are you going to do in the summer?"),
                N("Jeg vil reise noen uker, hvis det går.", "I want to travel a few weeks, if it works out."),
                N("Hvor da?", "Where to?"),
                N("Kanskje til Lofoten. Og du?", "Maybe to Lofoten. And you?"),
                N("Jeg blir og jobber overtid.", "I'll stay and work overtime."),
                N("Kjedelig? Eller praktisk?", "Boring? Or practical?"),
                N("Praktisk. Jeg sparer til neste år.", "Practical. I'm saving for next year."),
                N("Hvis du vil bli med senere, si ifra.", "If you want to join later, say so."),
                N("Gjerne. Hold meg oppdatert.", "Gladly. Keep me posted."),
            ],
            {"overtid": "overtime", "spare": "save (money)"},
        ),
    ]


def replace_extra_stories(pack_path: Path, stories: list) -> None:
    text = pack_path.read_text(encoding="utf-8")
    marker = "window.EXTRA_READ_STORIES = window.EXTRA_READ_STORIES || [];"
    idx = text.find(marker)
    if idx < 0:
        raise SystemExit(f"No EXTRA_READ_STORIES marker in {pack_path}")
    prefix = text[:idx]
    payload = json.dumps(stories, ensure_ascii=False, separators=(",", ":"))
    new_tail = (
        f"{marker}\n"
        f"  window.EXTRA_READ_STORIES.push(...{payload});\n"
        f"}})();\n"
    )
    pack_path.write_text(prefix + new_tail, encoding="utf-8")
    print(f"wrote {pack_path.name}: {len(stories)} stories")


def replace_norwegian_stories(path: Path, stories: list) -> None:
    text = path.read_text(encoding="utf-8")
    start = text.find("const READ_STORIES = [")
    if start < 0:
        raise SystemExit("READ_STORIES not found")
    # Find end of array assignment
    end_m = re.search(r"\];\s*\n", text[start:])
    if not end_m:
        raise SystemExit("end of READ_STORIES not found")
    end = start + end_m.end()
    # Pretty-ish but compact JS objects
    def js_obj(obj, indent=2):
        sp = " " * indent
        lines = ["{"]
        for i, (k, v) in enumerate(obj.items()):
            comma = "," if i < len(obj) - 1 else ""
            if k == "sentences":
                lines.append(f"{sp}{k}: [")
                for j, s in enumerate(v):
                    sc = "," if j < len(v) - 1 else ""
                    lines.append(
                        f'{sp}  {{ nb: {json.dumps(s["nb"], ensure_ascii=False)}, '
                        f'en: {json.dumps(s["en"], ensure_ascii=False)} }}{sc}'
                    )
                lines.append(f"{sp}],")
            elif k == "glosses":
                lines.append(f"{sp}{k}: {json.dumps(v, ensure_ascii=False)}{comma}")
            elif isinstance(v, str):
                lines.append(f"{sp}{k}: {json.dumps(v, ensure_ascii=False)}{comma}")
            else:
                lines.append(f"{sp}{k}: {json.dumps(v, ensure_ascii=False)}{comma}")
        lines.append("  }")
        return "\n".join(lines)

    parts = []
    for i, st in enumerate(stories):
        comma = "," if i < len(stories) - 1 else ""
        parts.append("  " + js_obj(st) + comma)
    block = "const READ_STORIES = [\n" + "\n".join(parts) + "\n];\n"
    path.write_text(text[:start] + block + text[end:], encoding="utf-8")
    print(f"wrote {path.name}: {len(stories)} Norwegian stories")


def main():
    packs = {
        "sv": swedish,
        "da": danish,
        "de": german,
        "fr": french,
        "es": spanish,
        "it": italian,
    }
    for lang, fn in packs.items():
        replace_extra_stories(ROOT / "lang" / f"{lang}-pack.js", fn())
    replace_norwegian_stories(ROOT / "read-stories.js", norwegian())
    print("Phase 1 story rewrites complete.")


if __name__ == "__main__":
    main()
